"use client"

/**
 * Workflow Automations Phase 2 — list row card.
 *
 * Compact row with name, summary, trigger group badge, enable switch,
 * last run, recent stats, and per-row actions (edit, duplicate,
 * archive/delete, run test, run history). The summary is generated by
 * `lib/workflows/human-summary.ts` so each row reads as a single
 * sentence.
 */

import {
  AlertTriangle,
  Copy,
  FlaskConical,
  History,
  Pencil,
  Trash2,
} from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Switch } from "@/components/ui/switch"
import { TRIGGER_CATALOG, TRIGGER_GROUP_LABELS, triggerLabel } from "@/lib/workflows/trigger-catalog"
import { buildAutomationSummary } from "@/lib/workflows/human-summary"
import { cn } from "@/lib/utils"
import type { AutomationRow } from "./types"

type Props = {
  row: AutomationRow
  onEdit: (row: AutomationRow) => void
  onToggle: (row: AutomationRow, next: boolean) => void
  onDuplicate: (row: AutomationRow) => void
  onArchive: (row: AutomationRow) => void
  onRunTest: (row: AutomationRow) => void
  onRunHistory: (row: AutomationRow) => void
  pendingId: string | null
}

export function AutomationListRow({
  row,
  onEdit,
  onToggle,
  onDuplicate,
  onArchive,
  onRunTest,
  onRunHistory,
  pendingId,
}: Props) {
  const meta = TRIGGER_CATALOG[row.trigger_type]
  const groupLabel = meta ? TRIGGER_GROUP_LABELS[meta.group] : "Other"
  const failures = row.recent_failure_count ?? 0
  const total = row.recent_runs_count ?? 0
  const summary = buildAutomationSummary({
    trigger_type: row.trigger_type,
    condition_config: row.condition_config,
    action_config: row.action_config,
  })
  const actionCount = ((row.action_config as { actions?: unknown[] })?.actions ?? []).length
  const lastRunStarted = row.last_run?.started_at
  const lastRunFailed = row.last_run?.status === "failed"
  const lastRunErr = row.last_run?.error_message ?? null
  const pending = pendingId === row.id

  return (
    <div
      className={cn(
        "rounded-xl border bg-card p-4 flex flex-col gap-3 transition-colors",
        "shadow-[0_1px_3px_rgba(0,0,0,0.04)]",
        failures > 0 ? "border-destructive/40" : "border-border",
      )}
    >
      <div className="flex items-start gap-3 min-w-0">
        <Switch
          checked={row.enabled}
          onCheckedChange={(v) => onToggle(row, v)}
          aria-label={row.enabled ? "Disable automation" : "Enable automation"}
          disabled={pending}
          className="mt-1"
        />
        <div className="flex flex-col gap-1 min-w-0 flex-1">
          <div className="flex flex-wrap items-center gap-2">
            <p className="text-sm font-semibold text-foreground truncate">{row.name}</p>
            <Badge variant="outline" className="text-[10px]">
              {groupLabel}
            </Badge>
            <Badge
              variant="outline"
              className={cn(
                "text-[10px] capitalize",
                row.enabled
                  ? "border-emerald-500/40 text-emerald-700 dark:text-emerald-300"
                  : "border-border text-muted-foreground",
              )}
            >
              {row.enabled ? "On" : "Off"}
            </Badge>
            {failures > 0 ? (
              <Badge variant="outline" className="text-[10px] border-destructive/40 text-destructive gap-1">
                <AlertTriangle className="w-3 h-3" /> {failures} failed
              </Badge>
            ) : null}
          </div>
          <p className="text-xs text-muted-foreground leading-relaxed">{summary}</p>
          {row.description ? (
            <p className="text-[11px] text-muted-foreground/80 italic line-clamp-2">{row.description}</p>
          ) : null}
        </div>
      </div>

      <div className="flex flex-wrap items-center gap-x-4 gap-y-2 text-[11px] text-muted-foreground border-t border-border/60 pt-2.5">
        <span>
          Trigger: <span className="text-foreground/80 font-medium">{triggerLabel(row.trigger_type)}</span>
        </span>
        <span>
          Actions: <span className="text-foreground/80 font-medium tabular-nums">{actionCount}</span>
        </span>
        <span>
          Last run:{" "}
          <span className="text-foreground/80 font-medium tabular-nums">
            {lastRunStarted
              ? new Date(lastRunStarted).toLocaleString(undefined, {
                  month: "short",
                  day: "numeric",
                  hour: "2-digit",
                  minute: "2-digit",
                })
              : "—"}
          </span>
        </span>
        <span>
          Runs (14d):{" "}
          <span className="text-foreground/80 font-medium tabular-nums">{total}</span>
        </span>
      </div>

      {lastRunFailed && lastRunErr ? (
        <div className="rounded-md border border-destructive/30 bg-destructive/[0.04] px-2.5 py-1.5 text-[11px] text-destructive">
          <span className="font-semibold uppercase tracking-wider text-[10px] mr-1.5">Last error</span>
          {lastRunErr}
        </div>
      ) : null}

      <div className="flex flex-wrap items-center gap-1 -mb-1">
        <Button
          type="button"
          variant="outline"
          size="sm"
          className="h-8 gap-1 text-xs"
          onClick={() => onEdit(row)}
          disabled={pending}
        >
          <Pencil className="w-3 h-3" /> Edit
        </Button>
        <Button
          type="button"
          variant="outline"
          size="sm"
          className="h-8 gap-1 text-xs"
          onClick={() => onRunTest(row)}
          disabled={pending}
        >
          <FlaskConical className="w-3 h-3" /> Run test
        </Button>
        <Button
          type="button"
          variant="ghost"
          size="sm"
          className="h-8 gap-1 text-xs text-muted-foreground"
          onClick={() => onRunHistory(row)}
          disabled={pending}
        >
          <History className="w-3 h-3" /> History
        </Button>
        <Button
          type="button"
          variant="ghost"
          size="sm"
          className="h-8 gap-1 text-xs text-muted-foreground"
          onClick={() => onDuplicate(row)}
          disabled={pending}
        >
          <Copy className="w-3 h-3" /> Duplicate
        </Button>
        <Button
          type="button"
          variant="ghost"
          size="sm"
          className="h-8 gap-1 text-xs text-muted-foreground hover:text-destructive ml-auto"
          onClick={() => onArchive(row)}
          disabled={pending}
        >
          <Trash2 className="w-3 h-3" /> Delete
        </Button>
      </div>
    </div>
  )
}
