/**
 * Workflow Automations Phase 1 — manager-friendly trigger catalog.
 *
 * Single source of truth for:
 *   - the human label shown in the trigger dropdown
 *   - the short description that explains *when* the trigger fires
 *   - the field paths managers can reference in conditions for that
 *     trigger (so we can render an inline cheat sheet beside the JSON
 *     editor instead of asking them to read a wiki)
 *   - a starter sample condition snippet they can paste / extend
 *
 * Keep aligned with `WorkflowTriggerType` in `lib/workflows/types.ts` and
 * the dispatch sites (e.g. `lib/workflows/dispatch.ts`,
 * `lib/prospects/status-events.ts`).
 */

import type { WorkflowTriggerType } from "@/lib/workflows/types"

export type TriggerFieldRef = {
  /** Field path the condition rule should reference. */
  path: string
  /** Short, user-facing description (no jargon). */
  description: string
  /** "string" | "number" | "boolean" | "datetime" | "enum" — informational only. */
  kind: "string" | "number" | "boolean" | "datetime" | "enum"
  /** When `kind === "enum"`, the allowed values. */
  enumValues?: string[]
}

export type TriggerCatalogEntry = {
  id: WorkflowTriggerType
  /** Concise menu label. */
  label: string
  /** "When" sentence — explains the trigger in plain English. */
  description: string
  /** Manager-friendly grouping (used by the future grouped dropdown). */
  group: "prospects" | "work-orders" | "quotes-invoices" | "maintenance" | "certificates" | "ai" | "equipment"
  /**
   * Phase availability. `"experimental"` is rendered with a small
   * "experimental — UI rules coming soon" caveat. Phase 1 marks the
   * prospect trigger as `"new"` so managers know it's freshly available.
   */
  availability: "stable" | "new" | "experimental"
  /**
   * Whether this trigger fires automatically today (i.e. there's an
   * existing emit site). When `false`, we mark it "Coming soon" and
   * disable saving rules against it. Always defaults to `true` for
   * existing triggers.
   */
  autoFiringToday: boolean
  /** Field paths usable in condition rules. */
  fieldRefs: TriggerFieldRef[]
  /** Example condition JSON the user can copy. */
  sampleCondition: string
}

const SAMPLE_AND = (rules: Array<{ field: string; op: string; value: unknown }>) =>
  JSON.stringify({ operator: "and", rules }, null, 2)

export const TRIGGER_CATALOG: Record<WorkflowTriggerType, TriggerCatalogEntry> = {
  prospect_status_changed: {
    id: "prospect_status_changed",
    label: "Prospect status changed",
    description:
      "Fires whenever a prospect moves through the pipeline — new → contacted, contacted → quoted, quoted → won/lost, and so on. Great for follow-up nudges and converted-customer onboarding.",
    group: "prospects",
    availability: "new",
    autoFiringToday: true,
    fieldRefs: [
      {
        path: "prospect.previous_status",
        kind: "enum",
        description: "The status the prospect just left.",
        enumValues: [
          "new",
          "attempting_contact",
          "contacted",
          "qualified",
          "proposal_sent",
          "won",
          "lost",
          "nurture",
        ],
      },
      {
        path: "prospect.next_status",
        kind: "enum",
        description: "The new pipeline status.",
        enumValues: [
          "new",
          "attempting_contact",
          "contacted",
          "qualified",
          "proposal_sent",
          "won",
          "lost",
          "nurture",
        ],
      },
      { path: "prospect.company_name", kind: "string", description: "Prospect company (read-only context)." },
      { path: "prospect.reason", kind: "string", description: 'Why the change fired — e.g. "manual_edit", "follow_up", "converted_to_customer".' },
    ],
    sampleCondition: SAMPLE_AND([
      { field: "prospect.next_status", op: "in", value: ["proposal_sent", "won"] },
    ]),
  },
  work_order_created: {
    id: "work_order_created",
    label: "Work order created",
    description: "Fires immediately after a new work order is created (manual, dispatched, or generated by maintenance plans).",
    group: "work-orders",
    availability: "stable",
    autoFiringToday: true,
    fieldRefs: [
      { path: "work_order.priority", kind: "enum", description: "Priority assigned at creation.", enumValues: ["low", "medium", "high", "urgent"] },
      { path: "work_order.status", kind: "string", description: "Current work order status." },
      { path: "work_order.customer_id", kind: "string", description: "Linked customer id (for routing)." },
    ],
    sampleCondition: SAMPLE_AND([{ field: "work_order.priority", op: "in", value: ["high", "urgent"] }]),
  },
  work_order_completed: {
    id: "work_order_completed",
    label: "Work order completed",
    description: "Fires when a work order is marked completed. Useful for completion-day customer summaries or invoice nudges.",
    group: "work-orders",
    availability: "stable",
    autoFiringToday: true,
    fieldRefs: [
      { path: "work_order.duration_minutes", kind: "number", description: "Total on-site duration (when tracked)." },
      { path: "work_order.equipment_id", kind: "string", description: "Linked equipment id." },
    ],
    sampleCondition: SAMPLE_AND([{ field: "work_order.duration_minutes", op: "gte", value: 60 }]),
  },
  work_order_status_changed: {
    id: "work_order_status_changed",
    label: "Work order status changed",
    description: "Fires whenever a work order status moves (scheduled → in-progress, in-progress → completed, etc.). Pair with conditions to target a specific transition.",
    group: "work-orders",
    availability: "stable",
    autoFiringToday: true,
    fieldRefs: [
      { path: "work_order.status", kind: "string", description: "The new status." },
      { path: "previous_work_order.status", kind: "string", description: "The status the work order left." },
    ],
    sampleCondition: SAMPLE_AND([
      { field: "previous_work_order.status", op: "eq", value: "scheduled" },
      { field: "work_order.status", op: "eq", value: "in_progress" },
    ]),
  },
  maintenance_due: {
    id: "maintenance_due",
    label: "Maintenance due (PM)",
    description: "Fires from the daily maintenance cron when a maintenance plan reaches its lead-time window. Great for customer reminders or auto-creating PM work orders.",
    group: "maintenance",
    availability: "stable",
    autoFiringToday: true,
    fieldRefs: [
      { path: "maintenance_plan.next_due", kind: "datetime", description: "Next due date for the plan (ISO)." },
      { path: "maintenance_plan.equipment_id", kind: "string", description: "Equipment the plan covers." },
      { path: "today", kind: "datetime", description: "Cron run date (ISO)." },
    ],
    sampleCondition: SAMPLE_AND([{ field: "maintenance_plan.next_due", op: "lte", value: "{{today}}" }]),
  },
  invoice_overdue: {
    id: "invoice_overdue",
    label: "Invoice overdue",
    description: "Fires from the daily billing cron when an unpaid invoice passes its due date. Use with conditions to escalate after N days.",
    group: "quotes-invoices",
    availability: "stable",
    autoFiringToday: true,
    fieldRefs: [
      { path: "invoice.days_overdue", kind: "number", description: "Days past due." },
      { path: "invoice.amount_cents", kind: "number", description: "Invoice total in cents." },
      { path: "invoice.balance_cents", kind: "number", description: "Outstanding balance in cents." },
    ],
    sampleCondition: SAMPLE_AND([
      { field: "invoice.days_overdue", op: "gte", value: 7 },
      { field: "invoice.balance_cents", op: "gt", value: 0 },
    ]),
  },
  quote_accepted: {
    id: "quote_accepted",
    label: "Quote accepted",
    description: "Fires when a customer accepts a quote (portal or staff-side). Useful for kicking off scheduling or onboarding sequences.",
    group: "quotes-invoices",
    availability: "stable",
    autoFiringToday: true,
    fieldRefs: [
      { path: "quote.total_cents", kind: "number", description: "Quote total in cents." },
      { path: "quote.customer_id", kind: "string", description: "Linked customer id." },
    ],
    sampleCondition: SAMPLE_AND([{ field: "quote.total_cents", op: "gte", value: 100000 }]),
  },
  equipment_warranty_expiring: {
    id: "equipment_warranty_expiring",
    label: "Equipment warranty expiring",
    description: "Fires from the warranty cron when covered equipment is approaching its warranty end. Ideal for customer extend-warranty offers.",
    group: "equipment",
    availability: "stable",
    autoFiringToday: true,
    fieldRefs: [
      { path: "equipment.warranty_end", kind: "datetime", description: "Warranty end date (ISO)." },
      { path: "equipment_category", kind: "string", description: "Equipment category, when known." },
    ],
    sampleCondition: SAMPLE_AND([{ field: "equipment.warranty_end", op: "lte", value: "{{today_plus_30}}" }]),
  },
  certificate_uploaded: {
    id: "certificate_uploaded",
    label: "Certificate released",
    description:
      "Fires when a calibration / compliance certificate is released to the portal (or uploaded and auto-released by the configured rule). Useful for customer notifications.",
    group: "certificates",
    availability: "stable",
    autoFiringToday: true,
    fieldRefs: [
      { path: "calibration_record.equipment_id", kind: "string", description: "Equipment the certificate belongs to." },
      { path: "calibration_record.released_at", kind: "datetime", description: "Release timestamp." },
    ],
    sampleCondition: SAMPLE_AND([]),
  },
  ai_assistant_digest_ready: {
    id: "ai_assistant_digest_ready",
    label: "AI operational digest ready",
    description:
      "Fires when an operational AI assistant finishes generating a daily digest. Useful for routing the digest to the right manager.",
    group: "ai",
    availability: "stable",
    autoFiringToday: true,
    fieldRefs: [
      { path: "ai_assistant.assistant_id", kind: "string", description: "Which assistant produced the digest." },
      { path: "ai_assistant.digest_summary", kind: "string", description: "Short digest summary text." },
    ],
    sampleCondition: SAMPLE_AND([]),
  },
}

export const TRIGGER_GROUP_LABELS: Record<TriggerCatalogEntry["group"], string> = {
  prospects: "Prospects & follow-ups",
  "work-orders": "Work orders",
  "quotes-invoices": "Quotes & invoices",
  maintenance: "Maintenance",
  certificates: "Certificates",
  equipment: "Equipment",
  ai: "AI assistants",
}

/** Ordered list for grouped dropdown rendering. */
export const TRIGGER_CATALOG_ORDER: WorkflowTriggerType[] = [
  "prospect_status_changed",
  "work_order_created",
  "work_order_completed",
  "work_order_status_changed",
  "maintenance_due",
  "invoice_overdue",
  "quote_accepted",
  "equipment_warranty_expiring",
  "certificate_uploaded",
  "ai_assistant_digest_ready",
]

/** Convenience: trigger label fallback (used by list rows). */
export function triggerLabel(trigger: WorkflowTriggerType | string): string {
  if (trigger in TRIGGER_CATALOG) return TRIGGER_CATALOG[trigger as WorkflowTriggerType].label
  return String(trigger).replace(/_/g, " ")
}
