"use client"

import { useState, useCallback, useEffect } from "react"
import { useRouter } from "next/navigation"
import {
  AlertTriangle,
  Repeat2,
  UserMinus,
  Wrench,
  ChevronRight,
  X,
  Clock,
  DollarSign,
  ClipboardList,
} from "lucide-react"
import { cn } from "@/lib/utils"
import { useTenant } from "@/lib/tenant-store"

import type { AiInsight, InsightCategory, InsightSeverity } from "@/lib/mock-data"

type Insight = AiInsight

const CATEGORY_META: Record<
  InsightCategory,
  { label: string; icon: React.ElementType; color: string; bg: string; border: string }
> = {
  "overdue_client": {
    label: "Overdue Service",
    icon: Clock,
    color: "text-destructive",
    bg: "bg-destructive/10",
    border: "border-l-destructive",
  },
  "repeat_failure": {
    label: "Repeat Failures",
    icon: Repeat2,
    color: "text-[color:var(--status-warning)]",
    bg: "bg-[color:var(--status-warning)]/10",
    border: "border-l-[color:var(--status-warning)]",
  },
  "expiring_warranty": {
    label: "Expiring Warranties",
    icon: UserMinus,
    color: "text-destructive",
    bg: "bg-destructive/10",
    border: "border-l-destructive",
  },
  "revenue_opportunity": {
    label: "Revenue",
    icon: DollarSign,
    color: "text-[color:var(--status-success)]",
    bg: "bg-[color:var(--status-success)]/10",
    border: "border-l-[color:var(--status-success)]",
  },
  "upsell": {
    label: "Operations",
    icon: Wrench,
    color: "text-[color:var(--ds-info-subtle)]",
    bg: "bg-[color:var(--ds-info-bg)]",
    border: "border-l-[color:var(--ds-info-subtle)]",
  },
}

const SEVERITY_DOT: Record<InsightSeverity, string> = {
  critical: "bg-destructive",
  high: "bg-[color:var(--status-warning)]",
  medium: "bg-[color:var(--ds-info-subtle)]",
  low: "bg-muted-foreground",
}

const ALL_CATEGORIES: InsightCategory[] = [
  "overdue_client",
  "repeat_failure",
  "expiring_warranty",
  "revenue_opportunity",
  "upsell",
]

export function OperationalInsightsWidget({
  insights,
  loading,
  error,
}: {
  insights: Insight[]
  loading?: boolean
  error?: string | null
}) {
  const router = useRouter()
  const { workspace } = useTenant()
  const [activeCategory, setActiveCategory] = useState<InsightCategory | null>(null)
  const [dismissed, setDismissed] = useState<Set<string>>(new Set())

  useEffect(() => {
    setDismissed(new Set())
    setActiveCategory(null)
  }, [workspace.id])

  const handleDismiss = useCallback((id: string) => {
    setDismissed((prev) => new Set([...prev, id]))
  }, [])

  const filtered = insights.filter(
    (i) =>
      !dismissed.has(i.id) &&
      (activeCategory === null || i.category === activeCategory),
  )

  const counts = Object.fromEntries(
    ALL_CATEGORIES.map((cat) => [
      cat,
      insights.filter((i) => !dismissed.has(i.id) && i.category === cat).length,
    ]),
  ) as Record<InsightCategory, number>

  const totalActive = insights.filter((i) => !dismissed.has(i.id)).length

  return (
    <div className="bg-card rounded-xl border border-[color:var(--ds-info-border)] overflow-hidden shadow-[0_1px_3px_rgba(0,0,0,0.06),0_1px_2px_rgba(0,0,0,0.04)]">

      <div className="flex items-center justify-between gap-3 px-5 py-4 border-b border-[color:var(--ds-info-border)] bg-[color:var(--ds-info-bg)]">
        <div className="flex items-center gap-2.5">
          <div className="w-7 h-7 rounded-lg bg-[color:var(--ds-info-subtle)] flex items-center justify-center shrink-0">
            <ClipboardList className="w-3.5 h-3.5 text-white" aria-hidden="true" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-sm font-semibold text-[color:var(--ds-info-text)]">Operational Insights</h2>
              {totalActive > 0 && (
                <span className="text-[10px] font-bold px-1.5 py-0.5 rounded-full bg-[color:var(--ds-info-subtle)] text-white tabular-nums">
                  {totalActive}
                </span>
              )}
            </div>
            <p className="text-[11px] text-[color:var(--ds-info-text)] opacity-70 leading-snug mt-0.5">
              Rule-based signals from your live metrics (not generated by AI)
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={() => router.push("/work-orders")}
          className={cn(
            "inline-flex items-center gap-1.5 h-8 px-3 rounded-lg text-xs font-medium border transition-colors shrink-0",
            "bg-white/60 border-[color:var(--ds-info-border)] text-[color:var(--ds-info-text)]",
            "hover:bg-white",
          )}
        >
          Work queue
          <ChevronRight className="w-3.5 h-3.5 opacity-60" />
        </button>
      </div>

      {error && (
        <div className="px-5 py-2 text-xs text-destructive border-b border-border flex items-center gap-2 bg-destructive/5">
          <AlertTriangle className="w-3.5 h-3.5 shrink-0" aria-hidden />
          Some metrics may be incomplete. Try refreshing the page.
        </div>
      )}

      <div className="flex items-center gap-1.5 px-5 py-3 border-b border-border overflow-x-auto scrollbar-none">
        <button
          type="button"
          onClick={() => setActiveCategory(null)}
          className={cn(
            "inline-flex items-center gap-1 h-7 px-2.5 rounded-md text-[11px] font-semibold whitespace-nowrap transition-colors shrink-0",
            activeCategory === null
              ? "bg-[color:var(--ds-info-subtle)] text-white"
              : "bg-muted text-muted-foreground hover:text-foreground hover:bg-muted/80",
          )}
        >
          All
          <span className="tabular-nums opacity-70">{totalActive}</span>
        </button>
        {ALL_CATEGORIES.map((cat) => {
          const meta = CATEGORY_META[cat]
          const Icon = meta.icon
          const count = counts[cat]
          return (
            <button
              key={cat}
              type="button"
              onClick={() => setActiveCategory(activeCategory === cat ? null : cat)}
              className={cn(
                "inline-flex items-center gap-1 h-7 px-2.5 rounded-md text-[11px] font-semibold whitespace-nowrap transition-colors shrink-0",
                activeCategory === cat
                  ? "bg-[color:var(--ds-info-subtle)] text-white"
                  : "bg-muted text-muted-foreground hover:text-foreground hover:bg-muted/80",
                count === 0 && "opacity-40",
              )}
              disabled={count === 0}
            >
              <Icon className="w-3 h-3" aria-hidden="true" />
              {meta.label}
              <span className="tabular-nums opacity-70">{count}</span>
            </button>
          )
        })}
      </div>

      {loading && insights.length === 0 ? (
        <ul className="divide-y divide-border" role="list" aria-label="Loading operational insights">
          {Array.from({ length: 3 }).map((_, i) => (
            <li key={i} className="px-5 py-4 flex gap-3">
              <div className="w-8 h-8 rounded-lg bg-muted animate-pulse shrink-0" />
              <div className="flex-1 space-y-2 pt-1">
                <div className="h-3 rounded bg-muted animate-pulse w-3/4" />
                <div className="h-2.5 rounded bg-muted animate-pulse w-full" />
                <div className="h-2.5 rounded bg-muted animate-pulse w-2/3" />
              </div>
            </li>
          ))}
        </ul>
      ) : filtered.length > 0 ? (
        <ul className="divide-y divide-border" role="list" aria-label="Operational insights">
          {filtered.map((insight) => (
            <InsightRow
              key={insight.id}
              insight={insight}
              onDismiss={handleDismiss}
              onAction={(href) => router.push(href)}
            />
          ))}
        </ul>
      ) : (
        <div className="flex flex-col items-center justify-center gap-2 py-10 text-center px-5">
          <div className="w-10 h-10 rounded-full bg-[color:var(--ds-info-bg)] border border-[color:var(--ds-info-border)] flex items-center justify-center">
            <ClipboardList className="w-4 h-4 text-[color:var(--ds-info-subtle)]" />
          </div>
          <p className="text-sm font-semibold text-foreground">No insights in this view</p>
          <p className="text-xs text-muted-foreground max-w-[320px] leading-relaxed">
            {insights.length === 0 && !loading
              ? "There are no rule-based alerts right now — for example, no overdue service, open work orders, expiring warranties, or repeat repair patterns that match your current data."
              : activeCategory
                ? "Nothing left in this category, or items were dismissed. Choose &ldquo;All&rdquo; or another category."
                : "All items were dismissed for this session. Refresh the page to see them again."}
          </p>
        </div>
      )}

      <div className="flex items-center justify-between gap-2 px-5 py-3 border-t border-border bg-muted/30">
        <p className="text-[10px] text-muted-foreground">
          Numbers come from equipment, work orders, and warranty dates in Supabase.
        </p>
        <button
          type="button"
          onClick={() => router.push("/equipment")}
          className="inline-flex items-center gap-1 text-[10px] font-semibold text-primary hover:underline transition-colors"
        >
          Equipment
          <ChevronRight className="w-3 h-3" />
        </button>
      </div>
    </div>
  )
}

function InsightRow({
  insight,
  onDismiss,
  onAction,
}: {
  insight: Insight
  onDismiss: (id: string) => void
  onAction: (href: string) => void
}) {
  const meta = CATEGORY_META[insight.category]
  const Icon = meta.icon

  return (
    <li
      className={cn(
        "flex items-start gap-3 px-5 py-4 border-l-2 transition-colors",
        meta.border,
      )}
      style={{ backgroundColor: "var(--card)" }}
      onMouseEnter={(e) =>
        (e.currentTarget.style.backgroundColor =
          "color-mix(in oklch, var(--primary) 2.5%, var(--card))")
      }
      onMouseLeave={(e) =>
        (e.currentTarget.style.backgroundColor = "var(--card)")
      }
    >
      <div
        className={cn(
          "w-8 h-8 rounded-lg flex items-center justify-center shrink-0 mt-0.5",
          meta.bg,
        )}
      >
        <Icon className={cn("w-4 h-4", meta.color)} aria-hidden="true" />
      </div>

      <div className="flex-1 min-w-0">
        <div className="flex items-start justify-between gap-2">
          <div className="flex items-center gap-1.5 flex-wrap">
            <span
              className={cn(
                "inline-block w-1.5 h-1.5 rounded-full shrink-0 mt-[3px]",
                SEVERITY_DOT[insight.severity],
              )}
              aria-label={`${insight.severity} severity`}
            />
            <p className="text-sm font-semibold text-foreground leading-snug">
              {insight.title}
            </p>
          </div>
          <button
            type="button"
            onClick={() => onDismiss(insight.id)}
            aria-label={`Dismiss: ${insight.title}`}
            className="shrink-0 p-0.5 rounded opacity-30 hover:opacity-70 transition-opacity text-muted-foreground"
          >
            <X className="w-3.5 h-3.5" />
          </button>
        </div>

        <p className="text-xs text-muted-foreground mt-1 leading-relaxed">
          {insight.description}
        </p>

        <div className="flex items-center gap-3 mt-2 flex-wrap">
          {insight.value && (
            <span className="inline-flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded-full border bg-card text-foreground border-border tabular-nums">
              {insight.value}
            </span>
          )}
          {insight.meta && (
            <span className="inline-flex items-center gap-1 text-[10px] text-muted-foreground">
              <Clock className="w-2.5 h-2.5" aria-hidden="true" />
              {insight.meta}
            </span>
          )}
          <button
            type="button"
            onClick={() => onAction(insight.actionHref)}
            className="inline-flex items-center gap-0.5 text-[10px] font-semibold text-primary hover:underline underline-offset-2 transition-all ml-auto"
          >
            {insight.actionLabel}
            <ChevronRight className="w-3 h-3" />
          </button>
        </div>
      </div>
    </li>
  )
}

/** @deprecated Use OperationalInsightsWidget */
export const AIInsightsWidget = OperationalInsightsWidget
