/** GE-AIOS-INSTITUTIONAL-LEARNING-TRUTHFULNESS-1A — Validated institutional learning. Delegates to @fuzor/memory. */

export {
  PLATFORM_INSTITUTIONAL_LEARNING_EMPTY_MESSAGE as GROWTH_INSTITUTIONAL_LEARNING_EMPTY_MESSAGE,
  PLATFORM_INSTITUTIONAL_LEARNING_FORBIDDEN_DEMO_STRINGS as GROWTH_INSTITUTIONAL_LEARNING_FORBIDDEN_DEMO_STRINGS,
  PLATFORM_INSTITUTIONAL_LEARNING_TRUTHFULNESS_QA_MARKER as GROWTH_INSTITUTIONAL_LEARNING_TRUTHFULNESS_1A_QA_MARKER,
  PLATFORM_INSTITUTIONAL_LEARNING_VALIDATED_LABEL as GROWTH_INSTITUTIONAL_LEARNING_VALIDATED_LABEL,
  buildPlatformValidatedInstitutionalLearningBullets as buildValidatedInstitutionalLearningBullets,
  containsPlatformForbiddenDemoInstitutionalLearning as containsForbiddenDemoInstitutionalLearning,
  filterPlatformValidatedInstitutionalLearnings as filterValidatedInstitutionalLearnings,
  isPlatformValidatedInstitutionalLearningItem as isValidatedInstitutionalLearningItem,
} from "@fuzor/memory"
