/** Client-safe Growth Engine timeline types. */

export const GROWTH_LEAD_TIMELINE_EVENT_TYPES = [
  "lead_created",
  "research_started",
  "research_completed",
  "research_failed",
  "website_fetch_failed",
  "website_fetch_fixed",
  "decision_maker_added",
  "decision_maker_confirmed",
  "decision_maker_rejected",
  "call_started",
  "call_attempted",
  "voicemail_left",
  "voice_drop_queued",
  "voice_drop_attempted",
  "voice_drop_delivered",
  "voice_drop_failed",
  "voice_drop_answered",
  "interested",
  "follow_up_created",
  "follow_up_completed",
  "notes_updated",
  "priority_changed",
  "override_changed",
  "next_best_action_changed",
  "website_changed",
  "status_changed",
  "import_created",
  "import_updated",
  "manual_touch",
  "email_sent",
  "email_delivered",
  "email_opened",
  "email_clicked",
  "email_replied",
  "email_bounced",
  "email_unsubscribed",
  "email_failed",
  "email_spam_complaint",
  "email_suppressed",
  "email_unmatched",
  "engagement_score_changed",
  "engagement_tier_changed",
  "engagement_increased",
  "high_engagement_detected",
  "bounce_detected",
  "hard_bounce_detected",
  "unsubscribe_detected",
  "complaint_detected",
  "suppression_applied",
  "sender_reputation_declined",
  "lead_became_hot",
  "lead_became_dormant",
  "relationship_strength_changed",
  "relationship_became_trusted",
  "relationship_became_strategic",
  "relationship_cooled",
  "opportunity_readiness_changed",
  "lead_became_sales_ready",
  "lead_became_priority_opportunity",
  "opportunity_blocker_added",
  "opportunity_blocker_resolved",
  "revenue_probability_changed",
  "lead_became_forecasted",
  "lead_became_commit_candidate",
  "forecast_confidence_changed",
  "forecast_regression_detected",
  "executive_priority_changed",
  "executive_intervention_recommended",
  "operational_capacity_changed",
  "capacity_constraint_added",
  "capacity_constraint_resolved",
  "operational_risk_detected",
  "ai_copilot_generation_created",
  "ai_copilot_generation_approved",
  "outreach_queued",
  "outreach_approved",
  "outreach_executed",
  "outreach_failed",
  "outreach_cancelled",
  "call_copilot_session_started",
  "call_copilot_objection_captured",
  "call_copilot_session_completed",
  "call_copilot_summary_approved",
  "conversation_health_changed",
  "buying_intent_detected",
  "competitor_detected",
  "urgency_detected",
  "conversation_risk_detected",
  "sequence_pattern_detected",
  "sequence_recommendation_changed",
  "sequence_enrollment_created",
  "sequence_step_created",
  "sequence_step_queued",
  "sequence_step_executed",
  "sequence_enrollment_completed",
  "sequence_enrollment_cancelled",
  "sequence_step_due",
  "sequence_step_skipped",
  "sequence_step_scheduled",
  "sequence_step_approved",
  "sequence_step_blocked",
  "sequence_step_sent",
  "sequence_step_failed",
  "sequence_scheduler_run",
  "qa_schedule_step_now",
  "qa_force_due_now",
  "qa_scheduler_run",
  "lead_assigned",
  "lead_reassigned",
  "lead_unassigned",
  "assignment_rule_applied",
  "assignment_skipped",
  "notification_created",
  "notification_acknowledged",
  "notification_completed",
  "notification_expired",
  "live_call_started",
  "buying_signal_detected",
  "objection_detected",
  "discovery_gap_detected",
  "call_risk_detected",
  "live_call_completed",
  "live_guidance_generated",
  "live_guidance_used",
  "opportunity_created",
  "opportunity_draft_created",
  "opportunity_draft_approved",
  "opportunity_created_from_draft",
  "opportunity_stage_changed",
  "stage_changed",
  "forecast_changed",
  "owner_changed",
  "amount_changed",
  "stale_detected",
  "opportunity_closed_won",
  "opportunity_closed_lost",
  "reply_received",
  "reply_classified",
  "reply_assigned",
  "reply_overdue",
  "meeting_requested",
  "meeting_created",
  "meeting_scheduled",
  "meeting_completed",
  "meeting_no_show",
  "meeting_canceled",
  "meeting_followup_due",
  "meeting_outcome_recorded",
  "meeting_reminder_configured",
  "cadence_task_created",
  "cadence_task_due",
  "cadence_task_completed",
  "cadence_task_skipped",
  "cadence_step_completed",
  "cadence_step_skipped",
  "customer_created",
  "onboarding_started",
  "onboarding_completed",
  "activation_recorded",
  "review_requested",
  "review_received",
  "referral_requested",
  "referral_received",
  "renewal_window_opened",
  "renewal_due",
  "expansion_candidate_detected",
  "churn_risk_detected",
  "inbox_sync_started",
  "inbox_sync_completed",
  "inbox_reply_imported",
  "inbox_thread_matched",
  "inbox_thread_created",
  "inbox_duplicate_skipped",
  "reply_draft_generated",
  "reply_draft_approved",
  "reply_draft_discarded",
  "reply_draft_sent",
  "reply_draft_blocked",
] as const

export type GrowthLeadTimelineEventType = (typeof GROWTH_LEAD_TIMELINE_EVENT_TYPES)[number]

export type GrowthLeadTimelineEvent = {
  id: string
  leadId: string
  eventType: GrowthLeadTimelineEventType
  title: string
  summary: string | null
  actorUserId: string | null
  actorEmail: string | null
  researchRunId: string | null
  callEventId: string | null
  decisionMakerId: string | null
  outboundMessageId: string | null
  messageEventId: string | null
  outboundReplyId: string | null
  payload: Record<string, unknown>
  occurredAt: string
  createdAt: string
}
