/** GS-AI-PLAYBOOK-5A hotfix — server-safe Growth workspace / AIden inset tokens (no React). */

export {
  AIDEN_CSS_VARS,
  BR_STACK_CLEAR_AIDEN,
  GROWTH_AIDEN_SAFE_AREA_PB_SCROLL,
  GROWTH_AIDEN_SAFE_AREA_PR,
  GROWTH_FLOATING_INSET_QA_MARKER,
  GROWTH_STICKY_ACTION_BAR,
  GROWTH_STICKY_ACTION_BAR_INNER,
  GROWTH_STICKY_ACTION_BAR_INNER_LAYOUT,
  GROWTH_STICKY_ACTION_BAR_SURFACE,
  GROWTH_WIZARD_ACTION_ROW,
  GROWTH_WORKSPACE_PAGE_CONTENT_QA_MARKER,
  GROWTH_WORKSPACE_SAFE_AREA,
  GROWTH_WORKSPACE_SAFE_AREA_STICKY_FOOTER,
} from "@/lib/layout/aiden-safe-area"
