import type { WorkspaceIndustryKey } from "@/lib/workspace-industry-registry"
import type { DemoIndustryProfile } from "@/lib/demo-seeding/demo-profile-model"

function mp(
  rows: Array<{ name: string; intervalValue: number; intervalUnit: "month" | "year" }>
): DemoIndustryProfile["maintenancePlanExamples"] {
  return rows
}

/**
 * Dense demo packs keyed by canonical workspace industry.
 * Merged in `buildDemoProfiles` — anything not listed uses `starterProfileFromDefinition`.
 */
export const DEMO_PROFILE_OVERRIDES: Partial<Record<WorkspaceIndustryKey, DemoIndustryProfile>> = {
  biomedical_medical_equipment: {
    industry: "biomedical_medical_equipment",
    demoCompanyName: "Precision Biomedical Services",
    customerTypes: [
      "Valley Regional Hospital",
      "Summit Surgical Center",
      "Greenview Family Clinic",
      "Riverstone Imaging Center",
      "Oak Ridge Dental Group",
      "Blue Harbor Rehab Center",
      "Starlight Urgent Care",
      "Northside Pediatrics",
      "Cedar Grove Endoscopy Center",
      "Maple Street Dialysis Clinic",
      "Lakeside Cardiology Associates",
      "Horizon Women's Health Pavilion",
      "Redwood Community Hospital",
      "Clearwater Veterans Clinic",
      "Pinecrest Sleep Disorders Lab",
      "Meadowbrook Outpatient Surgery",
      "Cascade Orthopedic Institute",
      "Silverline Oncology Infusion Center",
      "Pacific Coast Orthopedic Surgery Center",
      "Harborview Community Health Center",
      "Sierra Peak Ambulatory Surgery",
      "Golden State Wound & Hyperbaric",
      "Mission View Imaging Partners",
      "Westgate Medical Plaza",
      "Coastal Pediatric Specialty Center",
    ],
    equipmentAssetTypes: [
      { name: "IntelliVue MX750 Patient Monitor", category: "Patient Monitoring", manufacturer: "Philips" },
      { name: "CARESCAPE B850 Monitor", category: "Patient Monitoring", manufacturer: "GE HealthCare" },
      { name: "BeneVision N17 OR Monitor", category: "Patient Monitoring", manufacturer: "Mindray" },
      { name: "MA 27 / MA 28 Audiometer", category: "Diagnostics / Audiology", manufacturer: "Maico" },
      { name: "AMSCO 400 Steam Sterilizer", category: "Sterilization", manufacturer: "STERIS" },
      { name: "HSG-A 9102 Autoclave", category: "Sterilization", manufacturer: "Getinge" },
      { name: "V-PRO maX Low-Temperature Sterilizer", category: "Sterilization", manufacturer: "STERIS" },
      { name: "Alaris 8100 Pump Module", category: "Infusion", manufacturer: "BD" },
      { name: "Plum 360 Large Volume Pump", category: "Infusion", manufacturer: "ICU Medical" },
      { name: "Spectrum IQ Infusion System", category: "Infusion", manufacturer: "Baxter" },
      { name: "X Series Defibrillator", category: "Emergency Care", manufacturer: "ZOLL" },
      { name: "LIFEPAK 15 Defibrillator", category: "Emergency Care", manufacturer: "Physio-Control" },
      { name: "MAC 5500 HD ECG", category: "Diagnostics", manufacturer: "GE HealthCare" },
      { name: "AT-102 Plus ECG", category: "Diagnostics", manufacturer: "Schiller" },
      { name: "LOGIQ E10 Ultrasound", category: "Imaging", manufacturer: "GE HealthCare" },
      { name: "Mobilett Elara Max Portable X-Ray", category: "Imaging QA", manufacturer: "Siemens Healthineers" },
      { name: "TOR DEN Digital QA Phantom Suite", category: "Imaging QA", manufacturer: "Fluke Biomedical" },
      { name: "UniPulse Defib Analyzer", category: "Biomedical Test Equipment", manufacturer: "Rigel Medical" },
      { name: "Allegra X-30R Centrifuge", category: "Laboratory", manufacturer: "Beckman Coulter" },
      { name: "5702 Series General Purpose Centrifuge", category: "Laboratory", manufacturer: "Eppendorf" },
    ],
    workOrderTitleExamples: [
      "Annual electrical safety & performance verification",
      "Quarterly infusion pump calibration",
      "Sterilizer chamber temperature variance investigation",
      "Patient monitor arrhythmia alarm verification",
      "Portable X-ray QA detector calibration",
      "Audiometer daily bioacoustic calibration check",
      "Defibrillator battery replacement",
      "Sterilizer Bowie-Dick / BI failure investigation",
      "Imaging phantom QA — mammography flat panel",
      "ECG lead noise troubleshooting — ICU telemetry",
      "Low-temp sterilizer vaporizer maintenance",
      "Biomed analyzer annual verification (defib energy)",
    ],
    maintenancePlanExamples: mp([
      { name: "Annual Electrical Safety Verification", intervalValue: 1, intervalUnit: "year" },
      { name: "Quarterly Infusion Pump PM", intervalValue: 3, intervalUnit: "month" },
      { name: "Monthly Monitor Inspection", intervalValue: 1, intervalUnit: "month" },
      { name: "Semi-Annual Sterilizer QA", intervalValue: 6, intervalUnit: "month" },
    ]),
    technicianSpecialties: [
      "Biomedical Equipment",
      "Calibration",
      "Imaging QA",
      "Sterilization Systems",
      "Electrical Safety",
      "Infusion Systems",
    ],
    dashboardMetricTargets: { customers: 25, equipment: 68, workOrders: 150, maintenancePlans: 22 },
  },

  equipment_rental: {
    industry: "equipment_rental",
    demoCompanyName: "BlueRidge Equipment Rental",
    customerTypes: [
      "Northwind Constructors LLC",
      "Lakeshore Event Productions",
      "Summit Industrial Fabrication",
      "Harbor Municipal Works Dept",
      "Redwood Film & Stage Services",
      "Granite Peak Mining Support",
      "Willow Creek School District",
      "Bayline Marine Services Co-op",
      "Ironhorse Rail Maintenance JV",
      "Cedar Ridge Landscaping Group",
      "Pioneer Wind Field Services",
      "Aspen Ridge Cold Storage Build",
      "Copperfield Demo & Abatement",
      "Silverton Highway Expansion JV",
      "Meadowlark Sports Arena Ops",
      "BlueSprings Water Treatment Upgrade",
      "Trailhead Forestry Services",
      "Ridgeline Telecom Tower Crews",
      "Evergreen Property Restoration",
      "Stonebridge Commercial Interiors",
      "Foxtrot Logistics Cross-Dock",
      "Highline Airport Support Services",
      "Driftwood Resort Renovation",
      "Blackrock Substation Contractors",
    ],
    equipmentAssetTypes: [
      { name: "JLG 1055 Telehandler", category: "Aerial & Telehandlers", manufacturer: "JLG" },
      { name: "Genie GS-3232 Scissor Lift", category: "Aerial & Telehandlers", manufacturer: "Genie" },
      { name: "Wacker Neuson BPU 4045 Plate Compactor", category: "Compaction", manufacturer: "Wacker Neuson" },
      { name: "Multiquip DCA-70SSI Towable Generator", category: "Power & Lighting", manufacturer: "Multiquip" },
      { name: "Allmand Night-Lite Pro II Light Tower", category: "Power & Lighting", manufacturer: "Allmand" },
      { name: "Hilti TE 2000-AVR Demo Hammer", category: "Concrete & Demo", manufacturer: "Hilti" },
      { name: "Bobcat S650 Skid-Steer Loader", category: "Earthmoving", manufacturer: "Bobcat" },
      { name: "Ditch Witch JT20 Directional Drill", category: "Underground", manufacturer: "Ditch Witch" },
      { name: "Magnum Pro 4000 Towable Heater", category: "Climate", manufacturer: "Flagro" },
      { name: "York Rents 20-ton Chiller Trailer", category: "HVAC Rental", manufacturer: "York" },
      { name: "SkyTrak 6042 Rough-Terrain Forklift", category: "Material Handling", manufacturer: "SkyTrak" },
      { name: "Towmaster T-40 Equipment Trailer", category: "Trailers", manufacturer: "Towmaster" },
      { name: "Smalley 8x20 Mobile Office", category: "Site Services", manufacturer: "Smalley" },
      { name: "United Site Services 500-gal Holding Tank", category: "Site Services", manufacturer: "United Site Services" },
      { name: "Wanco WTLMB Arrow Board Trailer", category: "Traffic Safety", manufacturer: "Wanco" },
      { name: "Atlas Copco XAS 185 Air Compressor", category: "Air", manufacturer: "Atlas Copco" },
      { name: "Subaru R1700X Water Pump 6-inch", category: "Pumps", manufacturer: "Subaru" },
      { name: "Honda EU7000is Inverter Generator", category: "Power & Lighting", manufacturer: "Honda" },
      { name: "Miller Big Blue 400 Pro Welder", category: "Welding", manufacturer: "Miller" },
      { name: "Chicago Pneumatic RX22 Breaker", category: "Concrete & Demo", manufacturer: "Chicago Pneumatic" },
    ],
    workOrderTitleExamples: [
      "Post-rental inspection — telehandler #T-1042",
      "Turnaround: hydraulic leak on scissor lift GS-881",
      "Delivery checklist — generator trailer G-220",
      "Damage documentation — skid-steer bucket & coupler",
      "Rental-ready QA — light tower after refit",
      "Customer pickup inspection — plate compactor set",
      "PM before dispatch — air compressor XAS-044",
      "Emergency field swap — failed starter on towable pump",
      "Return audit — directional drill fluid system flush",
      "PM interval due — trailer brakes & bearings",
      "Rental contract extension PM — telehandler annual",
      "Yard turnaround — pressure wash & decal touch-up",
      "Customer site delivery — chiller trailer hookup assist",
      "Post-storm inspection — arrow board solar charge fault",
      "Utilization PM — 250-hour service on skid-steer",
      "Damage repair quote — mast wear pads replacement",
    ],
    maintenancePlanExamples: mp([
      { name: "Every-return rental inspection", intervalValue: 1, intervalUnit: "month" },
      { name: "Monthly fleet PM sweep", intervalValue: 1, intervalUnit: "month" },
      { name: "Quarterly trailer safety inspection", intervalValue: 3, intervalUnit: "month" },
      { name: "Annual high-hour telehandler service", intervalValue: 1, intervalUnit: "year" },
    ]),
    technicianSpecialties: ["Rental inspections", "Turnaround shop", "Field delivery support", "Fleet PM"],
    dashboardMetricTargets: { customers: 24, equipment: 52, workOrders: 42, maintenancePlans: 16 },
  },

  refrigeration_service: {
    industry: "refrigeration_service",
    demoCompanyName: "PolarLine Refrigeration Service",
    customerTypes: [
      "Harborview Grocery Cooperative",
      "Summit Cold Storage 3PL",
      "Riverside Bistro Group",
      "Northlake School Nutrition Center",
      "Copper Kettle Food Hall",
      "Willowbrook Pharmacy Chain",
      "Bluefin Seafood Processing",
      "Granite City Beer Distribution",
      "Aspen Ski Lodge Hospitality",
      "Meadowlark Hospital Nutrition",
      "Trailhead Catering Commissary",
      "Foxtrot Convenience Stores",
      "Evergreen Floral Distribution",
      "Stonebridge Hotel Kitchens",
      "Ironwood Meat Packers LLC",
      "Silverline Dairy Processing",
      "Lakeshore Campus Dining Services",
      "Pioneer Stadium Concessions",
      "Ridgeline Biotech Cold Rooms",
      "Cedarcrest Winery Cellar",
      "Blackrock Data Hall CRAC vendor",
      "Highline Airport Lounge Kitchen",
    ],
    equipmentAssetTypes: [
      { name: "Hillphoenix Walk-In Freezer — Low Temp", category: "Walk-in", manufacturer: "Hillphoenix" },
      { name: "Heatcraft Walk-In Cooler Evaporator", category: "Walk-in", manufacturer: "Heatcraft" },
      { name: "Copeland Scroll Rack Compressor Group", category: "Rack Systems", manufacturer: "Copeland" },
      { name: "Bitzer Semi-Hermetic Compressor", category: "Compressors", manufacturer: "Bitzer" },
      { name: "Lennox Condensing Unit — Remote", category: "Condensers", manufacturer: "Lennox" },
      { name: "Danfoss AK-CC55 Case Controller", category: "Controls", manufacturer: "Danfoss" },
      { name: "Heatcraft Fluid Cooler — Glycol", category: "Fluid Cooling", manufacturer: "Heatcraft" },
      { name: "Tecumseh Hermetic Condensing Unit", category: "Condensers", manufacturer: "Tecumseh" },
      { name: "KeepRite Reach-In Freezer Line", category: "Reach-in", manufacturer: "KeepRite" },
      { name: "Traulsen Pass-Through Blast Chiller", category: "Kitchen", manufacturer: "Traulsen" },
      { name: "Hoshizaki Ice Machine KM-1301", category: "Ice", manufacturer: "Hoshizaki" },
      { name: "Manitowoc Indigo NXT Ice Maker", category: "Ice", manufacturer: "Manitowoc" },
      { name: "Spiral freezer conveyor drive motor", category: "Conveyance", manufacturer: "Dorner" },
      { name: "Evaporator fan motor assembly — walk-in", category: "Walk-in", manufacturer: "ECM" },
      { name: "Electronic expansion valve rack", category: "Controls", manufacturer: "Sporlan" },
      { name: "Low-temp suction accumulator", category: "Rack Systems", manufacturer: "Parker" },
      { name: "Hot gas defrost valve station", category: "Rack Systems", manufacturer: "Alco" },
      { name: "Receiver tank — high-pressure", category: "Rack Systems", manufacturer: "Hansen" },
    ],
    workOrderTitleExamples: [
      "Emergency call — walk-in cooler not holding 38°F",
      "Scheduled leak check — rack suction circuit",
      "Compressor changeout — Copeland scroll trio",
      "Condenser coil chemical clean — remote Lennox",
      "Evaporator drain pan heater failure",
      "TXV hunting diagnosis — reach-in line",
      "Ice machine harvest fault — Hoshizaki KM-1301",
      "Blast chiller post-alarm verification",
      "Monthly rack PM — oil levels & vibration log",
      "Refrigerant recovery & pressure test — planned retrofit",
      "Case controller reprogram — Danfoss AK-CC55",
      "Hot gas defrost valve stuck open — after hours",
      "Glycol fluid cooler fan VFD fault",
      "Temperature mapping study — pharmacy walk-in",
      "Door gasket replacement — low temp freezer",
      "High superheat diagnosis — liquid line restriction suspected",
    ],
    maintenancePlanExamples: mp([
      { name: "Monthly rack PM & oil log", intervalValue: 1, intervalUnit: "month" },
      { name: "Quarterly leak inspection rounds", intervalValue: 3, intervalUnit: "month" },
      { name: "Semi-annual walk-in hinge & heater check", intervalValue: 6, intervalUnit: "month" },
      { name: "Annual ice machine descale program", intervalValue: 1, intervalUnit: "year" },
    ]),
    technicianSpecialties: ["Commercial refrigeration", "Leak detection", "Rack controls", "Emergency response"],
    dashboardMetricTargets: { customers: 22, equipment: 48, workOrders: 44, maintenancePlans: 15 },
  },

  fleet_mobile_equipment: {
    industry: "fleet_mobile_equipment",
    demoCompanyName: "RoadLink Fleet Maintenance",
    customerTypes: [
      "Summit Utility Services Fleet",
      "Harborline Mechanical Contractors",
      "Northwind Plumbing Co-op Fleet",
      "Redwood HVAC Rapid Response",
      "Granite Electric Service Trucks",
      "Aspen Arborist Mobile Crew",
      "Willow Creek Cable Splicers",
      "BlueSprings Water District Field Ops",
      "Ironhorse Crane & Rigging",
      "Trailhead Survey Instruments Pool",
      "Foxtrot Restoration Rapid Response",
      "Evergreen Landscaping Fleet",
      "Stonebridge Security Patrol",
      "Silverline Generator Rentals Field",
      "Lakeshore Towing & Recovery",
      "Pioneer Concrete Pump Trucks",
      "Ridgeline Pipeline Inspection Unit",
      "Cedarcrest Film Generator Truck",
      "Blackrock Mine Shuttle Service",
      "Highline Airport Ground Support",
      "Meadowlark School Bus Contractor",
      "Driftwood Marine Launch Support",
    ],
    equipmentAssetTypes: [
      { name: "Ford Transit 350HD Service Van #214", category: "Service Vehicles", manufacturer: "Ford" },
      { name: "Chevrolet Silverado 3500HD Service #118", category: "Service Vehicles", manufacturer: "Chevrolet" },
      { name: "Mercedes Sprinter 144 Crew Van #305", category: "Service Vehicles", manufacturer: "Mercedes-Benz" },
      { name: "Isuzu NPR-HD Box Truck #412", category: "Service Vehicles", manufacturer: "Isuzu" },
      { name: "PJ Trailers 20' Tilt Equipment Trailer T-77", category: "Trailers", manufacturer: "PJ Trailers" },
      { name: "Big Tex 14LP Dump Trailer #D-09", category: "Trailers", manufacturer: "Big Tex" },
      { name: "Wells Cargo 16' Enclosed Tool Trailer", category: "Trailers", manufacturer: "Wells Cargo" },
      { name: "Tommy Gate G2 Series Liftgate", category: "Liftgates", manufacturer: "Tommy Gate" },
      { name: "Multiquip WhisperWatt DA-7000SS Generator Skid", category: "Mobile Power", manufacturer: "Multiquip" },
      { name: "Magnum MLG8K Portable Light Tower", category: "Mobile Power", manufacturer: "Magnum" },
      { name: "Boss Snowrider V-Plow — F550 mount", category: "Attachments", manufacturer: "Boss" },
      { name: "Stellar TMAX 1 Service Body Compressor", category: "Upfits", manufacturer: "Stellar" },
      { name: "Vanair Air N Arc 300 Welder/Compressor", category: "Upfits", manufacturer: "Vanair" },
      { name: "Reading Classic II Service Body", category: "Upfits", manufacturer: "Reading" },
      { name: "CM Truck Beds SK Model Flatbed", category: "Upfits", manufacturer: "CM" },
      { name: "Hino 268A Cabover Box #501", category: "Service Vehicles", manufacturer: "Hino" },
      { name: "Great Dane 53' Dry Van — mobile tool crib", category: "Trailers", manufacturer: "Great Dane" },
      { name: "Wabash National Refrigerated Trailer", category: "Trailers", manufacturer: "Wabash" },
    ],
    workOrderTitleExamples: [
      "DOT annual inspection prep — Transit #214",
      "Trailer brake adjustment — PJ tilt T-77",
      "Liftgate hydraulic leak — Tommy Gate G2",
      "Scheduled PM — Sprinter DEF system service",
      "Road call — NPR alternator failure",
      "Trailer bearing repack — Wells Cargo 16'",
      "Mobile welder/compressor belt replacement — Vanair unit",
      "Snow plow controller fault — Boss V after storm",
      "Service body latch repair — Reading Classic II",
      "Generator exercise log review — WhisperWatt skid",
      "Light tower engine service — Magnum MLG8K",
      "Hino DPF regen fault — forced regen & doc",
      "Reefer trailer pretrip — Wabash unit R-12",
      "Flatbed stake pocket weld repair — CM SK",
      "Silverado transfer case noise diagnosis",
      "Sprinter AdBlue heater circuit — winter prep",
    ],
    maintenancePlanExamples: mp([
      { name: "Monthly fleet fluid & tire inspection", intervalValue: 1, intervalUnit: "month" },
      { name: "Quarterly trailer safety walkaround", intervalValue: 3, intervalUnit: "month" },
      { name: "Semi-annual liftgate hydraulic service", intervalValue: 6, intervalUnit: "month" },
      { name: "Annual DOT inspection package", intervalValue: 1, intervalUnit: "year" },
    ]),
    technicianSpecialties: ["Fleet PM", "DOT inspections", "Trailers & liftgates", "Roadside support"],
    dashboardMetricTargets: { customers: 22, equipment: 46, workOrders: 40, maintenancePlans: 14 },
  },

  material_handling: {
    industry: "material_handling",
    demoCompanyName: "LiftPath Material Handling",
    customerTypes: [
      "Granite Ridge Distribution Center",
      "Summit Beverage Bottling Plant",
      "Harborline Cold Chain Logistics",
      "Northwind Aerospace Components",
      "Willowbrook Retail Fulfillment Hub",
      "Aspen Lumber Processing",
      "BlueSprings Parcel Sort Facility",
      "Ironhorse Foundry Shipping",
      "Trailhead 3PL Cross-Dock",
      "Foxtrot Grocery Regional DC",
      "Evergreen Pharma Wholesale",
      "Stonebridge Building Supply DC",
      "Silverline Tire Distribution",
      "Lakeshore Port Container Yard",
      "Pioneer Electronics Inbound Hub",
      "Ridgeline Furniture Outlet DC",
      "Cedarcrest Food Co-Packing",
      "Blackrock Mining Concentrate Shed",
      "Highline Airport Cargo Building C",
      "Meadowlark School District Warehouse",
      "Driftwood Marine Parts Storeroom",
      "Copperfield Print & Mail Fulfillment",
    ],
    equipmentAssetTypes: [
      { name: "Toyota 8FGU25 Sit-Down Forklift", category: "Forklifts", manufacturer: "Toyota" },
      { name: "Raymond 4250 Reach Truck", category: "Forklifts", manufacturer: "Raymond" },
      { name: "Crown WP 3000 Electric Pallet Jack", category: "Pallet Jacks", manufacturer: "Crown" },
      { name: "Yale MPB045VG Walkie Stacker", category: "Stackers", manufacturer: "Yale" },
      { name: "Hytrol TA Belt Conveyor Section", category: "Conveyors", manufacturer: "Hytrol" },
      { name: "Dematic Sortation Diverter Module", category: "Conveyors", manufacturer: "Dematic" },
      { name: "Kelley HFX Hydraulic Dock Leveler", category: "Loading Dock", manufacturer: "Kelley" },
      { name: "Serco AB Air-Powered Dock Shelter", category: "Loading Dock", manufacturer: "Serco" },
      { name: "Rite-Hite Dok-Lok Vehicle Restraint", category: "Loading Dock", manufacturer: "Rite-Hite" },
      { name: "Blue Giant Mechanical Dock Leveler", category: "Loading Dock", manufacturer: "Blue Giant" },
      { name: "Enersys Ironhawk Forklift Battery — 48V", category: "Power", manufacturer: "Enersys" },
      { name: "Delta-Q QuiQ Onboard Charger", category: "Power", manufacturer: "Delta-Q" },
      { name: "Cascade Push Pull Slip Sheet Attachment", category: "Attachments", manufacturer: "Cascade" },
      { name: "TVH Roller Spare Kit — Reach Truck Mast", category: "Parts", manufacturer: "TVH" },
      { name: "Interroll Motor Roller Conveyor Zone", category: "Conveyors", manufacturer: "Interroll" },
      { name: "Mitsubishi FBC15N Electric Forklift", category: "Forklifts", manufacturer: "Mitsubishi" },
      { name: "Raymond 5300 Orderpicker", category: "Order Picking", manufacturer: "Raymond" },
      { name: "Southworth Pallet Lift Table", category: "Lifts", manufacturer: "Southworth" },
    ],
    workOrderTitleExamples: [
      "Annual forklift inspection — Toyota 8FGU25",
      "Reach truck mast leak — Raymond 4250",
      "Dock leveler lip cylinder weeping — Kelley HFX",
      "Conveyor motor overtemp — Hytrol TA zone 4",
      "Battery watering & equalize charge — 48V pack",
      "Dock restraint fault — Rite-Hite Dok-Lok sensor",
      "Pallet jack drive wheel replacement — Crown WP3000",
      "Sortation diverter air solenoid replacement",
      "Dock shelter curtain tear repair — Serco AB",
      "Forklift chain wear measurement & replacement",
      "Walkie stacker brake adjustment — Yale MPB045",
      "Charger fault code — Delta-Q QuiQ",
      "Loading dock bump plate weld repair",
      "Conveyor tracking adjustment — Interroll zone",
      "Hydraulic oil sample — leveler annual PM",
      "Order picker rail height calibration — OP30",
    ],
    maintenancePlanExamples: mp([
      { name: "Monthly forklift PM route", intervalValue: 1, intervalUnit: "month" },
      { name: "Quarterly dock equipment inspection", intervalValue: 3, intervalUnit: "month" },
      { name: "Semi-annual battery PM & watering", intervalValue: 6, intervalUnit: "month" },
      { name: "Annual OSHA lift inspection package", intervalValue: 1, intervalUnit: "year" },
    ]),
    technicianSpecialties: ["Forklifts", "Dock equipment", "Conveyors", "Battery & charger"],
    dashboardMetricTargets: { customers: 22, equipment: 50, workOrders: 38, maintenancePlans: 15 },
  },

  facility_maintenance: {
    industry: "facility_maintenance",
    demoCompanyName: "Harborline Facility Maintenance",
    customerTypes: [
      "Summit Corporate Center — Tower A",
      "Riverside Medical Pavilion",
      "Northlake University Main Campus",
      "Willowbrook High School District",
      "Granite Peak Data Hall 2",
      "Aspen Resort & Conference Center",
      "BlueSprings Wastewater Campus",
      "Ironhorse Industrial Park Phase III",
      "Trailhead Logistics Office Park",
      "Foxtrot Regional Airport Terminal B",
      "Evergreen County Courthouse Annex",
      "Stonebridge Retail Commons",
      "Silverline Biotech Campus",
      "Lakeshore Convention Center",
      "Pioneer Sports Arena",
      "Ridgeline Telecom Headend Building",
      "Cedarcrest Senior Living Village",
      "Blackrock R&D Laboratory Wing",
      "Highline Hotel & Tower",
      "Meadowlark Public Library System",
      "Driftwood Marina Operations Building",
      "Copperfield Distribution Annex",
    ],
    equipmentAssetTypes: [
      { name: "BAC Cooling Tower Cell #2", category: "HVAC Plant", manufacturer: "BAC" },
      { name: "Trane Intellipak RTU — Roof Zone East", category: "Rooftop HVAC", manufacturer: "Trane" },
      { name: "Cummins 500kW Standby Generator", category: "Life Safety", manufacturer: "Cummins" },
      { name: "Taco Domestic Water Booster Skid", category: "Plumbing", manufacturer: "Taco" },
      { name: "Schneider Square D Switchboard — MDP", category: "Electrical", manufacturer: "Schneider" },
      { name: "Notifier NFS2-3030 Fire Panel", category: "Fire / Life Safety", manufacturer: "Notifier" },
      { name: "Johnson Controls Metasys BMS Head End", category: "Controls", manufacturer: "Johnson Controls" },
      { name: "Sterling Steam-to-Steam Humidifier", category: "HVAC", manufacturer: "Sterling" },
      { name: "Armstrong Design Envelope Pump", category: "Hydronics", manufacturer: "Armstrong" },
      { name: "Siemens Desigo Room Automation Panel", category: "Controls", manufacturer: "Siemens" },
      { name: "Price SDV Terminal Unit Bank — VAV", category: "Air Distribution", manufacturer: "Price" },
      { name: "Triumph AHU — Penthouse MEA-1", category: "Air Handling", manufacturer: "Trane" },
      { name: "Elevator machine room HVAC unit", category: "Vertical transport support", manufacturer: "Carrier" },
      { name: "Backflow Preventer RP — Main Domestic", category: "Plumbing", manufacturer: "Watts" },
      { name: "Emergency eyewash / shower station skid", category: "Safety", manufacturer: "Haws" },
      { name: "Building automation expansion module", category: "Controls", manufacturer: "Honeywell" },
    ],
    workOrderTitleExamples: [
      "Tenant service request — conference room overcooling",
      "Cooling tower water treatment visit — log sheets",
      "Generator monthly exercise review — Cummins 500kW",
      "Fire panel point trouble — NOTIFIER NFS2 zone 12",
      "BMS trend review — hot/cold complaints floor 14",
      "Booster pump vibration follow-up — Taco skid",
      "Switchboard IR scan — annual thermography",
      "VAV box rebalancing — east wing pneumatic",
      "AHU prefilter & bag change — MEA-1",
      "Domestic backflow annual test — Watts RP",
      "Humidifier steam trap failure — Sterling unit",
      "Vendor corrective — dock leveler weld repair oversight",
      "Seasonal cooling tower startup checklist",
      "Eyewash station flow test — quarterly program",
      "Pump seal replacement — secondary chilled loop",
      "BMS graphics update — new lab occupancy schedule",
    ],
    maintenancePlanExamples: mp([
      { name: "Monthly building rounds & filter change", intervalValue: 1, intervalUnit: "month" },
      { name: "Quarterly life-safety device test batch", intervalValue: 3, intervalUnit: "month" },
      { name: "Semi-annual cooling tower treatment audit", intervalValue: 6, intervalUnit: "month" },
      { name: "Annual generator load test coordination", intervalValue: 1, intervalUnit: "year" },
    ]),
    technicianSpecialties: ["Building systems", "Vendor coordination", "BMS", "Life safety support"],
    dashboardMetricTargets: { customers: 22, equipment: 48, workOrders: 36, maintenancePlans: 16 },
  },

  commercial_equipment: {
    industry: "commercial_equipment",
    demoCompanyName: "Copperline Commercial Kitchen Services",
    customerTypes: [
      "Harborview Bistro Collective",
      "Summit School District Nutrition",
      "Northwind Stadium Concessions",
      "Willowbrook Hotel Banquet Kitchens",
      "Granite Peak Casino Food Court",
      "Aspen Ski Lodge Restaurants",
      "BlueSprings Hospital Cafeteria",
      "Ironhorse Corporate Cafeteria",
      "Trailhead Coffee Roastery Chain",
      "Foxtrot Grocery Deli Kitchens",
      "Evergreen Catering Commissary",
      "Stonebridge Country Club",
      "Silverline Movie Theater Snack Bars",
      "Lakeshore Airport Lounge Kitchen",
      "Pioneer University Dining Hall",
      "Ridgeline Ghost Kitchen Hub",
      "Cedarcrest Bakery Production",
      "Blackrock Tech Campus Café",
      "Highline Convention Center Banquets",
      "Meadowlark Prison Food Service Unit",
      "Driftwood Marina Galley",
      "Copperfield Food Truck Pod",
    ],
    equipmentAssetTypes: [
      { name: "Vulcan VC4GD Convection Oven", category: "Cooking", manufacturer: "Vulcan" },
      { name: "Frymaster PF50 Split-Vat Fryer", category: "Cooking", manufacturer: "Frymaster" },
      { name: "Hobart AM16 Base Dishmachine", category: "Warewash", manufacturer: "Hobart" },
      { name: "True T-49-HC Reach-In Refrigerator", category: "Refrigeration", manufacturer: "True" },
      { name: "Traulsen RHT232WUT-HHS Reach-In", category: "Refrigeration", manufacturer: "Traulsen" },
      { name: "Hoshizaki KM-515MAH Ice Machine", category: "Ice", manufacturer: "Hoshizaki" },
      { name: "CaptiveAire hood exhaust fan VFD bank", category: "Ventilation", manufacturer: "CaptiveAire" },
      { name: "Ansul R-102 Wet Chemical Fire System", category: "Fire suppression", manufacturer: "Ansul" },
      { name: "Middleby Marshall PS360 Conveyor Oven", category: "Cooking", manufacturer: "Middleby Marshall" },
      { name: "Globe SP20 Mixer", category: "Prep", manufacturer: "Globe" },
      { name: "Rational iCombi Pro 10-1/1", category: "Cooking", manufacturer: "Rational" },
      { name: "Scotsman C1848 Prodigy Ice Maker", category: "Ice", manufacturer: "Scotsman" },
      { name: "Blodgett Zephaire Convection Stack", category: "Cooking", manufacturer: "Blodgett" },
      { name: "TurboChef Sota Rapid Cook Oven", category: "Cooking", manufacturer: "TurboChef" },
      { name: "Perlick Underbar Refrigeration", category: "Bar", manufacturer: "Perlick" },
      { name: "Alto-Shaam Cook & Hold Smoker Oven", category: "Cooking", manufacturer: "Alto-Shaam" },
      { name: "Champion Moyer Diebel Glasswasher", category: "Warewash", manufacturer: "Champion" },
      { name: "Walk-in freezer evaporator — low temp", category: "Refrigeration", manufacturer: "Heatcraft" },
    ],
    workOrderTitleExamples: [
      "Hood exhaust fan vibration — CaptiveAire VFD fault",
      "Fryer high-limit tripping — Frymaster PF50 vat B",
      "Dishmachine rinse pressure low — Hobart AM16",
      "Reach-in not holding temp — True T-49 HC",
      "Ice machine harvest fault — Hoshizaki KM-515",
      "Combi oven steam generator descale — Rational iCombi",
      "Ansul system inspection — fusible link verification",
      "Conveyor oven belt tracking — Middleby Marshall",
      "Mixer gear oil leak — Globe SP20",
      "TurboChef magnetron replacement — Sota",
      "Walk-in defrost clock stuck — Traulsen RHT",
      "Scotsman bin thermostat erratic",
      "Blodgett stack ignition fault — lower deck",
      "Perlick glycol system bubble noise",
      "Alto-Shaam smoker probe calibration",
      "Champion glasswasher rinse booster fault",
    ],
    maintenancePlanExamples: mp([
      { name: "Monthly hood & ansul inspection", intervalValue: 1, intervalUnit: "month" },
      { name: "Quarterly ice machine descale program", intervalValue: 3, intervalUnit: "month" },
      { name: "Semi-annual fryer boil-out & vat PM", intervalValue: 6, intervalUnit: "month" },
      { name: "Annual fire suppression inspection coordination", intervalValue: 1, intervalUnit: "year" },
    ]),
    technicianSpecialties: ["Commercial cooking", "Refrigeration", "Ventilation", "Warewash"],
    dashboardMetricTargets: { customers: 22, equipment: 50, workOrders: 40, maintenancePlans: 15 },
  },

  calibration_inspection: {
    industry: "calibration_inspection",
    demoCompanyName: "TraceLine Calibration Partners",
    customerTypes: [
      "Summit Pharma QA Laboratory",
      "Harborview Municipal Water Lab",
      "Northwind Aerospace NDT Cell",
      "Willowbrook Power Generation QA",
      "Granite Peak Food Safety Lab",
      "Aspen Environmental Field Services",
      "BlueSprings OEM Sensor Line",
      "Ironhorse Pipeline Metering Station",
      "Trailhead University Research Lab",
      "Foxtrot Automotive Proving Ground",
      "Evergreen Hospital Lab Services",
      "Stonebridge Building Commissioning",
      "Silverline Solar Field Metrology",
      "Lakeshore Port Weighbridge Authority",
      "Pioneer Defense Contractor QA",
      "Ridgeline Chemical Process Plant",
      "Cedarcrest Independent Test House",
      "Blackrock Battery Test Chamber",
      "Highline Telecom Fiber Lab",
      "Meadowlark School District CTE Lab",
      "Driftwood Marine Survey Instruments",
      "Copperfield Legal Metrology Services",
    ],
    equipmentAssetTypes: [
      { name: "Fluke 7526A Process Calibrator", category: "Electrical Standards", manufacturer: "Fluke" },
      { name: "Druck DPI 620 Genii Pressure Calibrator", category: "Pressure Standards", manufacturer: "Druck" },
      { name: "Mitutoyo SJ-410 Surface Roughness Tester", category: "Dimensional", manufacturer: "Mitutoyo" },
      { name: "Keysight 34465A Digital Multimeter", category: "Electrical Standards", manufacturer: "Keysight" },
      { name: "Ashcroft Test Gauge — Class 3A", category: "Pressure Reference", manufacturer: "Ashcroft" },
      { name: "Hart Scientific 9103 Dry-Well Field Calibrator", category: "Temperature", manufacturer: "Fluke Calibration" },
      { name: "OMICRON CPC 100 Primary Test Set", category: "Electrical Safety", manufacturer: "OMICRON" },
      { name: "Transmille 8000 Multifunction Calibrator", category: "Electrical Standards", manufacturer: "Transmille" },
      { name: "GE Druck PV624 Pressure Controller", category: "Pressure Automation", manufacturer: "GE" },
      { name: "Meriam M200-DI Smart Manometer", category: "Pressure Field", manufacturer: "Meriam" },
      { name: "Extech HD350 Sound Level Calibrator", category: "Acoustics", manufacturer: "Extech" },
      { name: "Testo 350 Flue Gas Analyzer", category: "Combustion", manufacturer: "Testo" },
      { name: "Rigel UNI-PULSE Defibrillator Analyzer", category: "Biomedical Test", manufacturer: "Rigel" },
      { name: "Simco FMX-004 Electrostatic Field Meter", category: "ESD", manufacturer: "Simco" },
      { name: "Chatillon DFS2 Digital Force Gauge", category: "Mechanical", manufacturer: "Chatillon" },
      { name: "Omega CL540ZA Thermocouple Calibrator", category: "Temperature", manufacturer: "Omega" },
      { name: "Yokogawa CA700 Pressure Calibrator", category: "Pressure Field", manufacturer: "Yokogawa" },
    ],
    workOrderTitleExamples: [
      "As-found / as-left calibration — Fluke 7526A",
      "Pressure standard comparison — Ashcroft deadweight witness",
      "Temperature dry-well verification — Hart 9103",
      "Multimeter annual calibration — Keysight 34465A",
      "Surface roughness gauge linearity check",
      "Certificate renewal batch — lab week 14",
      "On-site gauge calibration — cooling tower instruments",
      "OMICRON CPC 100 protective relay test file review",
      "Biomed analyzer verification — UNI-PULSE energy test",
      "Combustion analyzer pre-season linearity — Testo 350",
      "ESD survey meter annual verification",
      "Force gauge calibration — Chatillon DFS2",
      "Manometer drift investigation — Meriam M200",
      "Sound level calibrator level check — Extech HD350",
      "Pressure controller automation loop test — PV624",
      "Traceability audit prep — certificate binder QC",
    ],
    maintenancePlanExamples: mp([
      { name: "Monthly internal cross-check standards", intervalValue: 1, intervalUnit: "month" },
      { name: "Quarterly recall & due-list scrub", intervalValue: 3, intervalUnit: "month" },
      { name: "Semi-annual lab environment monitoring review", intervalValue: 6, intervalUnit: "month" },
      { name: "Annual accreditation surveillance prep", intervalValue: 1, intervalUnit: "year" },
    ]),
    technicianSpecialties: ["Metrology", "Field standards", "Certificates", "Lab QA"],
    dashboardMetricTargets: { customers: 22, equipment: 44, workOrders: 36, maintenancePlans: 14 },
  },

  elevator_service: {
    industry: "elevator_service",
    demoCompanyName: "Summit Vertical Systems",
    customerTypes: [
      "Harborview Medical Center Towers",
      "Summit Financial Plaza",
      "Northlake University STEM Tower",
      "Willowbrook County Government Center",
      "Granite Peak Transit Hub",
      "Aspen Resort Gondola Base",
      "BlueSprings Parking Structure P3",
      "Ironhorse Distribution High-rise",
      "Trailhead Luxury Condominiums",
      "Foxtrot Stadium Elevator Bank",
      "Evergreen Historic Courthouse Retrofit",
      "Stonebridge Hotel & Spa",
      "Silverline Data Center Lift Lobby",
      "Lakeshore Airport Terminal Connector",
      "Pioneer Public Library Annex",
      "Ridgeline Biotech Campus Tower B",
      "Cedarcrest Senior Living Tower",
      "Blackrock R&D Elevator Modernization",
      "Highline Mixed-Use Tower",
      "Meadowlark School District Admin",
      "Driftwood Marina Parking Tower",
      "Copperfield Logistics Sort Tower",
    ],
    equipmentAssetTypes: [
      { name: "Otis Gen2 Traction Elevator — Bank A", category: "Elevator", manufacturer: "Otis" },
      { name: "KONE EcoSpace MRL Car #2", category: "Elevator", manufacturer: "KONE" },
      { name: "ThyssenKrupp Evolution Hydraulic Elevator", category: "Elevator", manufacturer: "ThyssenKrupp" },
      { name: "Schindler 3300 MRL — Retail podium", category: "Elevator", manufacturer: "Schindler" },
      { name: "Garaventa Artira Inclined Platform Lift", category: "Accessibility", manufacturer: "Garaventa" },
      { name: "Savaria Telecab Home Lift — VIP suite", category: "Accessibility", manufacturer: "Savaria" },
      { name: "Elevator machine room HVAC package", category: "Support systems", manufacturer: "Carrier" },
      { name: "Controller modernization kit — relay bank", category: "Modernization", manufacturer: "MCE" },
      { name: "Door operator upgrade — GAL MOVFR", category: "Door equipment", manufacturer: "GAL" },
      { name: "Governor rope replacement assembly", category: "Safety", manufacturer: "Otis" },
      { name: "Buffer spring inspection set — car & counterweight", category: "Safety", manufacturer: "Generic" },
      { name: "Traction sheave groove wear measurement", category: "Mechanical", manufacturer: "Generic" },
      { name: "Hydraulic jack seal replacement kit", category: "Hydraulic", manufacturer: "Blain" },
      { name: "Cab interior panel refresh — lobby car", category: "Cab", manufacturer: "Internal" },
      { name: "Firefighters' service phase II test", category: "Code compliance", manufacturer: "Internal" },
      { name: "Escalator step chain tension inspection", category: "Escalator", manufacturer: "Schindler" },
    ],
    workOrderTitleExamples: [
      "Annual CAT 1 inspection — Otis Gen2 Bank A",
      "Door reopening fault — KONE EcoSpace lobby",
      "Governor trip test documentation — hydraulic unit",
      "Controller fault log download — Schindler 3300",
      "Machine room HVAC high temp alarm follow-up",
      "Rope grip inspection — traction modernization",
      "Inclined platform annual load test — Garaventa",
      "Hydraulic oil analysis — ThyssenKrupp Evolution",
      "Fire service recall test — phase I & II",
      "Step chain lubrication — retail escalator",
      "Buffer inspection — parking tower cars",
      "Cab lighting retrofit — LED driver fault",
      "Sheave regroove assessment — traction unit",
      "Door clutch adjustment — GAL operator",
      "Pit flood sensor test — seasonal checklist",
      "Annunciator fault — fire recall interface",
    ],
    maintenancePlanExamples: mp([
      { name: "Monthly maintenance control program", intervalValue: 1, intervalUnit: "month" },
      { name: "Quarterly safety test documentation batch", intervalValue: 3, intervalUnit: "month" },
      { name: "Semi-annual machine room rounds", intervalValue: 6, intervalUnit: "month" },
      { name: "Annual CAT 1 inspection package", intervalValue: 1, intervalUnit: "year" },
    ]),
    technicianSpecialties: ["Traction systems", "Hydraulic elevators", "Code testing", "Modernization"],
    dashboardMetricTargets: { customers: 22, equipment: 42, workOrders: 34, maintenancePlans: 14 },
  },

  generator_power: {
    industry: "generator_power",
    demoCompanyName: "GridGuard Generator Services",
    customerTypes: [
      "Harborview Medical Center Campus",
      "Summit Data Center Colocation East",
      "Northlake Wastewater Treatment Plant",
      "Willowbrook Telecom Switch Site",
      "Granite Peak Casino & Hotel",
      "Aspen Ski Resort Base Power",
      "BlueSprings Water Pump Station #4",
      "Ironhorse Pipeline Compressor Station",
      "Trailhead County Emergency Services HQ",
      "Foxtrot Broadcast Tower Site",
      "Evergreen School District Bus Yard",
      "Stonebridge Logistics Freezer Plant",
      "Silverline Pharma Cold Chain Hub",
      "Lakeshore Port Crane Power",
      "Pioneer Military Reserve Center",
      "Ridgeline Chemical Plant Critical Loads",
      "Cedarcrest Senior Living Campus",
      "Blackrock R&D Battery Lab",
      "Highline Airport ARFF Building",
      "Meadowlark Courthouse Annex",
      "Driftwood Marina Fuel Dock",
      "Copperfield Microgrid Pilot Site",
    ],
    equipmentAssetTypes: [
      { name: "Kohler 500REOZT4 Standby Generator", category: "Generator", manufacturer: "Kohler" },
      { name: "Cummins C500D6 Diesel Generator", category: "Generator", manufacturer: "Cummins" },
      { name: "Generac SG625 625kW Unit", category: "Generator", manufacturer: "Generac" },
      { name: "Asco 300 Series ATS — 800A", category: "Transfer Switch", manufacturer: "Asco" },
      { name: "Zenith ZTG8 Automatic Transfer Switch", category: "Transfer Switch", manufacturer: "Zenith" },
      { name: "Deep Sea DSE8610 MKII Genset Controller", category: "Controls", manufacturer: "Deep Sea" },
      { name: "Basler DECS-250 AVR Excitation", category: "Excitation", manufacturer: "Basler" },
      { name: "Enersys 4x8V battery string — 1250Ah", category: "DC Plant", manufacturer: "Enersys" },
      { name: "Caterpillar SR4B Generator End", category: "Generator", manufacturer: "Caterpillar" },
      { name: "Load bank resistive element bank — 500kW", category: "Testing", manufacturer: "Avtron" },
      { name: "Belimo damper actuator — gen room ventilation", category: "HVAC", manufacturer: "Belimo" },
      { name: "Day tank fuel polish skid", category: "Fuel", manufacturer: "Axius" },
      { name: "Radiator core replacement assembly", category: "Cooling", manufacturer: "Generic" },
      { name: "Coolant heater block — winter package", category: "Cold weather", manufacturer: "Phillips & Temro" },
      { name: "Emergency stop mushroom & safety chain", category: "Safety", manufacturer: "Allen-Bradley" },
      { name: "Exhaust silencer spark arrestor service", category: "Exhaust", manufacturer: "Generic" },
    ],
    workOrderTitleExamples: [
      "Monthly load bank test — Kohler 500kW",
      "ATS transfer test — Asco 300 series",
      "Battery string impedance test — Enersys bank",
      "Coolant leak repair — Cummins C500 lower hose",
      "Exercise log review & alarm history download",
      "AVR stability check after utility sag event",
      "Fuel filter change & water drain — day tank",
      "Radiator fin cleaning — high ambient derate",
      "Controller firmware update — Deep Sea DSE8610",
      "Block heater circuit fault — winter package",
      "Oil sample analysis — iron ppm trending",
      "Belimo actuator replacement — gen room damper",
      "Spark arrestor inspection — exhaust stack",
      "Emergency stop chain adjustment",
      "Gen room ventilation interlock test",
      "Parallel sync commissioning support — microgrid pilot",
    ],
    maintenancePlanExamples: mp([
      { name: "Monthly generator exercise PM", intervalValue: 1, intervalUnit: "month" },
      { name: "Quarterly battery inspection & torque check", intervalValue: 3, intervalUnit: "month" },
      { name: "Semi-annual load bank documentation package", intervalValue: 6, intervalUnit: "month" },
      { name: "Annual fuel system & ATS inspection", intervalValue: 1, intervalUnit: "year" },
    ]),
    technicianSpecialties: ["Generator PM", "ATS testing", "Battery systems", "Load banking"],
    dashboardMetricTargets: { customers: 22, equipment: 44, workOrders: 36, maintenancePlans: 15 },
  },
}

export const RICH_DEMO_INDUSTRY_KEYS = new Set<WorkspaceIndustryKey>(
  (Object.keys(DEMO_PROFILE_OVERRIDES) as WorkspaceIndustryKey[]).filter((k) => DEMO_PROFILE_OVERRIDES[k] != null)
)

export function isRichDemoProfileIndustry(key: WorkspaceIndustryKey): boolean {
  return RICH_DEMO_INDUSTRY_KEYS.has(key)
}
