import type { WorkspaceIndustryKey } from "@/lib/workspace-industry-registry"
import type { GoldenPathActionDefinition } from "@/lib/onboarding-industry/golden-path-types"

export const GOLDEN_PATH_REGISTRY_VERSION = 1 as const

const DEFAULT_PATH: GoldenPathActionDefinition[] = [
  {
    id: "add_first_customer",
    label: "Add your first customer",
    description: "Create a real account so jobs, assets, and billing stay linked.",
    href: "/customers",
    ctaLabel: "Open customers",
    completionRule: { kind: "customers_non_sample_gte", n: 1 },
    sampleDataHint: "Compare against a demo customer, then add your own.",
    priority: 1,
  },
  {
    id: "register_first_asset",
    label: "Register your first equipment",
    description: "Attach at least one asset so work history and PM schedules have a home.",
    href: "/equipment",
    ctaLabel: "Open equipment",
    completionRule: { kind: "equipment_non_sample_gte", n: 1 },
    sampleDataHint: "Browse demo equipment, then register your own.",
    priority: 2,
  },
  {
    id: "create_first_job",
    label: "Create your first work order",
    description: "Log or schedule work so dispatch and billing reflect reality.",
    href: "/work-orders",
    ctaLabel: "Open work orders",
    completionRule: { kind: "work_orders_non_sample_gte", n: 1 },
    sampleDataHint: "Open a demo job to see the flow, then create your own.",
    priority: 3,
  },
]

const BY_INDUSTRY: Partial<Record<WorkspaceIndustryKey, GoldenPathActionDefinition[]>> = {
  hvac_r: [
    {
      id: "hvac_pm_agreement",
      label: "Create your first PM agreement",
      description: "Put contract coverage on file so seasonal PM and RTU rounds are trackable.",
      href: "/maintenance-plans",
      ctaLabel: "Maintenance plans",
      completionRule: { kind: "maintenance_plans_non_sample_gte", n: 1 },
      sampleDataHint: "Review a demo plan, then add your own agreement.",
      priority: 1,
    },
    {
      id: "hvac_seasonal_maintenance",
      label: "Schedule seasonal maintenance",
      description: "Book PM or seasonal visits against rooftop or packaged equipment.",
      href: "/service-schedule",
      ctaLabel: "Service schedule",
      completionRule: { kind: "work_orders_non_sample_gte", n: 1 },
      sampleDataHint: "Use demo jobs as a template for your first seasonal visit.",
      priority: 2,
    },
    {
      id: "hvac_rooftop_unit",
      label: "Add a rooftop or packaged unit",
      description: "Register RTUs or splits so refrigerant and PM history stay on the right asset.",
      href: "/equipment",
      ctaLabel: "Equipment",
      completionRule: { kind: "equipment_non_sample_gte", n: 1 },
      sampleDataHint: "Mirror demo rooftop assets with your own registers.",
      priority: 3,
    },
  ],
  equipment_rental: [
    {
      id: "rental_inspect_asset",
      label: "Inspect a rental asset",
      description: "Log inspection work between turns so damage and readiness are documented.",
      href: "/work-orders",
      ctaLabel: "Work orders",
      completionRule: { kind: "work_orders_non_sample_gte", n: 1 },
      sampleDataHint: "Try a demo inspection-style job, then log your own.",
      priority: 1,
    },
    {
      id: "rental_mark_ready",
      label: "Mark equipment rental-ready",
      description: "Keep staged units and readiness visible on the equipment register.",
      href: "/equipment",
      ctaLabel: "Equipment",
      completionRule: { kind: "equipment_non_sample_gte", n: 1 },
      sampleDataHint: "Use demo SKUs as examples for your yard inventory.",
      priority: 2,
    },
    {
      id: "rental_turnaround",
      label: "Create a turnaround work order",
      description: "Track prep, damage review, and rent-ready handoff in one job.",
      href: "/dispatch",
      ctaLabel: "Dispatch",
      completionRule: { kind: "work_orders_non_sample_gte", n: 2 },
      sampleDataHint: "Follow demo turnaround density on the board.",
      priority: 3,
    },
  ],
  refrigeration_service: [
    {
      id: "ref_emergency_cooling",
      label: "Log an emergency cooling issue",
      description: "Capture walk-in or rack down events as structured work orders.",
      href: "/work-orders",
      ctaLabel: "Work orders",
      completionRule: { kind: "work_orders_non_sample_gte", n: 1 },
      sampleDataHint: "Open a demo emergency-style job first.",
      priority: 1,
    },
    {
      id: "ref_pm_schedule",
      label: "Schedule refrigeration PM",
      description: "Align compressor and rack PM with your contract cadence.",
      href: "/maintenance-plans",
      ctaLabel: "Maintenance plans",
      completionRule: { kind: "maintenance_plans_non_sample_gte", n: 1 },
      sampleDataHint: "Review demo PM templates, then publish your own.",
      priority: 2,
    },
    {
      id: "ref_walkin_asset",
      label: "Add walk-in or compressor assets",
      description: "Register rack lines and walk-ins so history stays asset-accurate.",
      href: "/equipment",
      ctaLabel: "Equipment",
      completionRule: { kind: "equipment_non_sample_gte", n: 1 },
      sampleDataHint: "Mirror demo rack assets with your own records.",
      priority: 3,
    },
  ],
  material_handling: [
    {
      id: "mh_forklift_inspection",
      label: "Complete a forklift inspection",
      description: "Use work orders to capture inspection findings and follow-ups.",
      href: "/work-orders",
      ctaLabel: "Work orders",
      completionRule: { kind: "work_orders_non_sample_gte", n: 1 },
      sampleDataHint: "Start from a demo MHE inspection pattern.",
      priority: 1,
    },
    {
      id: "mh_battery_pm",
      label: "Schedule battery maintenance",
      description: "Track industrial battery PM alongside truck service intervals.",
      href: "/maintenance-plans",
      ctaLabel: "Maintenance plans",
      completionRule: { kind: "maintenance_plans_non_sample_gte", n: 1 },
      sampleDataHint: "Compare to demo PM rows for batteries.",
      priority: 2,
    },
    {
      id: "mh_warehouse_route",
      label: "Create a warehouse PM route",
      description: "Bundle recurring rounds so technicians move efficiently across assets.",
      href: "/service-schedule",
      ctaLabel: "Service schedule",
      completionRule: { kind: "work_orders_non_sample_gte", n: 1 },
      sampleDataHint: "Use the service schedule to mirror demo route density.",
      priority: 3,
    },
  ],
  calibration_inspection: [
    {
      id: "cal_add_asset",
      label: "Add a calibration asset",
      description: "Register traceable instruments so due windows stay visible.",
      href: "/equipment",
      ctaLabel: "Equipment",
      completionRule: { kind: "equipment_non_sample_gte", n: 1 },
      sampleDataHint: "Review demo calibration assets, then add yours.",
      priority: 1,
    },
    {
      id: "cal_inspection_job",
      label: "Create an inspection checklist job",
      description: "Run field inspections as work orders tied to the right asset.",
      href: "/work-orders",
      ctaLabel: "Work orders",
      completionRule: { kind: "work_orders_non_sample_gte", n: 1 },
      sampleDataHint: "Open a demo inspection-style work order.",
      priority: 2,
    },
    {
      id: "cal_certificate_ready",
      label: "Review certificate-ready service",
      description: "Close the loop on certificate issuance from completed service work.",
      href: "/settings/imports/certificates",
      ctaLabel: "Certificates",
      completionRule: { kind: "invoices_sent_non_sample_gte", n: 1 },
      sampleDataHint: "Follow demo billing + certificate paths when ready.",
      priority: 3,
    },
  ],
  generator_power: [
    {
      id: "gen_pm_schedule",
      label: "Schedule generator PM",
      description: "Keep prime and standby units on a disciplined PM calendar.",
      href: "/maintenance-plans",
      ctaLabel: "Maintenance plans",
      completionRule: { kind: "maintenance_plans_non_sample_gte", n: 1 },
      sampleDataHint: "Use demo PM rows as a baseline.",
      priority: 1,
    },
    {
      id: "gen_ats_inspection",
      label: "Log an ATS inspection",
      description: "Track transfer switch inspections alongside generator service.",
      href: "/work-orders",
      ctaLabel: "Work orders",
      completionRule: { kind: "work_orders_non_sample_gte", n: 1 },
      sampleDataHint: "Inspect demo ATS-style jobs first.",
      priority: 2,
    },
    {
      id: "gen_load_bank",
      label: "Review load-bank / test workflow",
      description: "Document load tests and commissioning handoffs in quotes or invoices.",
      href: "/quotes",
      ctaLabel: "Quotes",
      completionRule: { kind: "quotes_non_sample_gte", n: 1 },
      sampleDataHint: "Mirror demo quoting for complex test workflows.",
      priority: 3,
    },
  ],
}

export function goldenPathActionsForIndustry(key: WorkspaceIndustryKey): GoldenPathActionDefinition[] {
  return BY_INDUSTRY[key] ?? DEFAULT_PATH
}
