"use client"

import type { LucideIcon } from "lucide-react"
import {
Activity,
AirVent,
AlertTriangle,
Ambulance,
Anchor,
Anvil,
Archive,
ArrowUpDown,
Axe,
BadgeCheck,
BadgePercent,
Battery,
BatteryCharging,
BatteryFull,
BatteryMedium,
BatteryWarning,
Beaker,
Bed,
BedDouble,
Bell,
Bike,
Binoculars,
Box,
Boxes,
Braces,
Building2,
Bus,
Cable,
Camera,
Car,
ChefHat,
CircleDot,
CircleGauge,
CircleParking,
CircuitBoard,
ClipboardCheck,
ClipboardList,
ClipboardType,
Cloud,
CloudRain,
Coffee,
Cog,
Compass,
Container,
Cpu,
Database,
Dna,
DoorClosed,
DoorOpen,
Drill,
Droplet,
Droplets,
EthernetPort,
Eye,
Factory,
Fan,
Fence,
FileCode,
FileHeart,
FireExtinguisher,
Flame,
FlaskConical,
Forklift,
Fuel,
Gauge,
Gem,
Hammer,
HardHat,
Headphones,
HeartPulse,
Heater,
Hospital,
Key,
KeyRound,
Landmark,
Layers,
LayoutGrid,
LeafyGreen,
Lightbulb,
ListChecks,
Lock,
MapPin,
Microscope,
Microwave,
Monitor,
Music2,
Navigation,
Network,
OctagonAlert,
Package,
Package2,
Paintbrush,
ParkingMeter,
PcCase,
Pickaxe,
Pill,
Pipette,
Plane,
Plug,
Plug2,
PlugZap,
Power,
Printer,
Projector,
QrCode,
Radar,
Radiation,
Radio,
Refrigerator,
Rocket,
Route,
Router,
Ruler,
Satellite,
Scan,
ScanBarcode,
ScanLine,
Server,
Settings,
Shield,
ShieldAlert,
ShieldCheck,
ShieldHalf,
Ship,
Shovel,
ShowerHead,
Siren,
Smartphone,
Snowflake,
Speaker,
SprayCan,
Stethoscope,
Sun,
Syringe,
Telescope,
TestTube,
Thermometer,
ThermometerSun,
Timer,
TowerControl,
Tractor,
TrainFront,
TriangleAlert,
Truck,
TruckElectric,
Tv,
UtensilsCrossed,
Vibrate,
Video,
Warehouse,
WashingMachine,
Waves,
Wifi,
Wind,
WindArrowDown,
Wine,
Wrench,
Zap,
ZapOff
} from "lucide-react"

/** Stable section order in the icon picker (unknown categories sort last). */
export const EQUIPMENT_TYPE_ICON_CATEGORY_ORDER = [
  "HVAC & refrigeration",
  "Electrical & lighting",
  "Plumbing & water",
  "Medical & diagnostics",
  "Fire & security",
  "Fleet & field service",
  "Industrial & manufacturing",
  "Food service",
  "Appliances & home",
  "IT & networking",
  "Audio / video",
  "Power & energy",
  "Logistics & storage",
  "Tools & site work",
  "Safety & compliance",
  "Building & access",
  "General",
] as const

type IconRow = readonly [string, string, string, LucideIcon]

const ICON_ROWS: IconRow[] = [
  ["Thermometer", "HVAC & refrigeration", "temperature thermostat heating cooling climate", Thermometer],
  ["Snowflake", "HVAC & refrigeration", "refrigeration cold ac ice freezer", Snowflake],
  ["Wind", "HVAC & refrigeration", "airflow ventilation blower duct", Wind],
  ["Fan", "HVAC & refrigeration", "blower motor exhaust intake", Fan],
  ["AirVent", "HVAC & refrigeration", "duct register grille diffuser", AirVent],
  ["ThermometerSun", "HVAC & refrigeration", "heat hot summer cooling load", ThermometerSun],
  ["Heater", "HVAC & refrigeration", "furnace boiler heat pump", Heater],
  ["CloudRain", "HVAC & refrigeration", "humidity dehumidifier moisture", CloudRain],
  ["WindArrowDown", "HVAC & refrigeration", "draft airflow damper", WindArrowDown],
  ["Zap", "Electrical & lighting", "electric voltage spark wiring", Zap],
  ["ZapOff", "Electrical & lighting", "disconnect outage breaker", ZapOff],
  ["Plug", "Electrical & lighting", "outlet receptacle cord", Plug],
  ["Plug2", "Electrical & lighting", "twist lock connector", Plug2],
  ["PlugZap", "Electrical & lighting", "ev charger high voltage", PlugZap],
  ["Cable", "Electrical & lighting", "wire harness conduit", Cable],
  ["Lightbulb", "Electrical & lighting", "lamp fixture led", Lightbulb],
  ["CircuitBoard", "Electrical & lighting", "pcb control board electronics", CircuitBoard],
  ["Battery", "Electrical & lighting", "ups storage backup", Battery],
  ["BatteryCharging", "Electrical & lighting", "charge inverter", BatteryCharging],
  ["BatteryWarning", "Electrical & lighting", "fault low voltage", BatteryWarning],
  ["BatteryMedium", "Electrical & lighting", "state of charge", BatteryMedium],
  ["BatteryFull", "Electrical & lighting", "full charge", BatteryFull],
  ["EthernetPort", "IT & networking", "lan switch patch panel", EthernetPort],
  ["Router", "IT & networking", "wifi gateway network", Router],
  ["Network", "IT & networking", "topology vlan", Network],
  ["Wifi", "IT & networking", "wireless access point", Wifi],
  ["Server", "IT & networking", "rack data center host", Server],
  ["Cloud", "IT & networking", "hosted saas sync", Cloud],
  ["Database", "IT & networking", "sql records backup", Database],
  ["Cpu", "IT & networking", "compute processor edge", Cpu],
  ["PcCase", "IT & networking", "workstation desktop tower", PcCase],
  ["Monitor", "IT & networking", "display kvm", Monitor],
  ["Printer", "IT & networking", "mfp label", Printer],
  ["Smartphone", "IT & networking", "mobile mdm", Smartphone],
  ["QrCode", "IT & networking", "asset tag scan", QrCode],
  ["ScanBarcode", "IT & networking", "inventory sku", ScanBarcode],
  ["FileCode", "IT & networking", "script automation api", FileCode],
  ["Braces", "IT & networking", "json config developer", Braces],
  ["Droplets", "Plumbing & water", "water leak flow", Droplets],
  ["Droplet", "Plumbing & water", "moisture drip", Droplet],
  ["Waves", "Plumbing & water", "fluid circulation pump", Waves],
  ["ShowerHead", "Plumbing & water", "fixture bath", ShowerHead],
  ["ArrowUpDown", "Plumbing & water", "pressure balancing mixing valve", ArrowUpDown],
  ["Stethoscope", "Medical & diagnostics", "clinical patient vitals", Stethoscope],
  ["HeartPulse", "Medical & diagnostics", "ecg cardiac monitor", HeartPulse],
  ["Syringe", "Medical & diagnostics", "injection vaccine", Syringe],
  ["Pill", "Medical & diagnostics", "pharmacy medication", Pill],
  ["Microscope", "Medical & diagnostics", "pathology lab", Microscope],
  ["ScanLine", "Medical & diagnostics", "mri ct imaging", ScanLine],
  ["Scan", "Medical & diagnostics", "ultrasound diagnostic", Scan],
  ["Hospital", "Medical & diagnostics", "clinic ward", Hospital],
  ["Ambulance", "Medical & diagnostics", "ems transport", Ambulance],
  ["BedDouble", "Medical & diagnostics", "patient bed", BedDouble],
  ["Activity", "Medical & diagnostics", "vitals telemetry", Activity],
  ["Dna", "Medical & diagnostics", "genomics research", Dna],
  ["Pipette", "Medical & diagnostics", "liquid handling assay", Pipette],
  ["Beaker", "Medical & diagnostics", "chemistry buffer", Beaker],
  ["FlaskConical", "Medical & diagnostics", "titration lab", FlaskConical],
  ["TestTube", "Medical & diagnostics", "sample qc", TestTube],
  ["Radiation", "Medical & diagnostics", "radiology imaging hazmat signage", Radiation],
  ["FileHeart", "Medical & diagnostics", "records hipaa", FileHeart],
  ["Flame", "Fire & security", "fire suppression detection", Flame],
  ["FireExtinguisher", "Fire & security", "portable extinguisher", FireExtinguisher],
  ["Siren", "Fire & security", "alarm notification", Siren],
  ["ShieldAlert", "Fire & security", "intrusion breach", ShieldAlert],
  ["Shield", "Fire & security", "perimeter hardening", Shield],
  ["ShieldHalf", "Fire & security", "policy segmentation", ShieldHalf],
  ["ShieldCheck", "Fire & security", "verified protection", ShieldCheck],
  ["Lock", "Fire & security", "access control door", Lock],
  ["Key", "Fire & security", "master keying rekey", Key],
  ["KeyRound", "Fire & security", "fob credential", KeyRound],
  ["Camera", "Fire & security", "cctv video surveillance", Camera],
  ["Eye", "Fire & security", "monitoring audit", Eye],
  ["Bell", "Fire & security", "notification pager", Bell],
  ["Truck", "Fleet & field service", "service van dispatch", Truck],
  ["TruckElectric", "Fleet & field service", "ev fleet charging", TruckElectric],
  ["Car", "Fleet & field service", "light duty vehicle", Car],
  ["Bus", "Fleet & field service", "shuttle transit", Bus],
  ["Bike", "Fleet & field service", "ebike courier", Bike],
  ["Tractor", "Fleet & field service", "ag equipment", Tractor],
  ["TrainFront", "Fleet & field service", "rail logistics", TrainFront],
  ["Plane", "Fleet & field service", "air cargo gse", Plane],
  ["Ship", "Fleet & field service", "marine port", Ship],
  ["Anchor", "Fleet & field service", "mooring dock", Anchor],
  ["MapPin", "Fleet & field service", "route geofence", MapPin],
  ["Route", "Fleet & field service", "routing stops", Route],
  ["Navigation", "Fleet & field service", "gps guidance", Navigation],
  ["ClipboardList", "Fleet & field service", "job checklist", ClipboardList],
  ["ClipboardCheck", "Fleet & field service", "closeout signoff jsa permit checklist", ClipboardCheck],
  ["ClipboardType", "Fleet & field service", "forms paperwork", ClipboardType],
  ["ListChecks", "Fleet & field service", "punch list qa", ListChecks],
  ["HardHat", "Fleet & field service", "technician jobsite", HardHat],
  ["Timer", "Fleet & field service", "sla response", Timer],
  ["Factory", "Industrial & manufacturing", "plant production line", Factory],
  ["Cog", "Industrial & manufacturing", "machine gearbox drive", Cog],
  ["Anvil", "Industrial & manufacturing", "metal fab forging", Anvil],
  ["Forklift", "Industrial & manufacturing", "warehouse lift", Forklift],
  ["TowerControl", "Industrial & manufacturing", "plc scada controls", TowerControl],
  ["Gauge", "Industrial & manufacturing", "instrumentation dial", Gauge],
  ["CircleGauge", "Industrial & manufacturing", "pressure vacuum", CircleGauge],
  ["Vibrate", "Industrial & manufacturing", "vibration analysis", Vibrate],
  ["Drill", "Industrial & manufacturing", "machining spindle", Drill],
  ["Pickaxe", "Industrial & manufacturing", "mining heavy", Pickaxe],
  ["Container", "Industrial & manufacturing", "iso tank intermodal", Container],
  ["Layers", "Industrial & manufacturing", "stack lamination", Layers],
  ["LayoutGrid", "Industrial & manufacturing", "cells line balance", LayoutGrid],
  ["Rocket", "Industrial & manufacturing", "aerospace tooling", Rocket],
  ["Satellite", "Industrial & manufacturing", "telemetry remote", Satellite],
  ["Radar", "Industrial & manufacturing", "motion detection", Radar],
  ["ChefHat", "Food service", "kitchen restaurant", ChefHat],
  ["UtensilsCrossed", "Food service", "dining servery", UtensilsCrossed],
  ["Coffee", "Food service", "espresso hot beverage", Coffee],
  ["Wine", "Food service", "bar cellar", Wine],
  ["Microwave", "Appliances & home", "countertop cook", Microwave],
  ["Refrigerator", "Appliances & home", "cold storage reach in", Refrigerator],
  ["WashingMachine", "Appliances & home", "laundry opl", WashingMachine],
  ["Tv", "Audio / video", "display signage", Tv],
  ["Video", "Audio / video", "conferencing av", Video],
  ["Speaker", "Audio / video", "pa sound", Speaker],
  ["Headphones", "Audio / video", "headset comms", Headphones],
  ["Music2", "Audio / video", "media playback", Music2],
  ["Projector", "Audio / video", "cinema boardroom", Projector],
  ["Radio", "Audio / video", "two way wireless", Radio],
  ["Power", "Power & energy", "mains distribution", Power],
  ["Sun", "Power & energy", "solar pv inverter", Sun],
  ["Fuel", "Power & energy", "diesel propane tank", Fuel],
  ["CircleParking", "Logistics & storage", "yard staging", CircleParking],
  ["ParkingMeter", "Logistics & storage", "curb equipment", ParkingMeter],
  ["Package", "Logistics & storage", "parcel carton", Package],
  ["Package2", "Logistics & storage", "bulk pallet", Package2],
  ["Box", "Logistics & storage", "crate tote", Box],
  ["Boxes", "Logistics & storage", "inventory sku", Boxes],
  ["Warehouse", "Logistics & storage", "dc storage rack", Warehouse],
  ["Fence", "Logistics & storage", "yard perimeter", Fence],
  ["Hammer", "Tools & site work", "carpentry repair", Hammer],
  ["Axe", "Tools & site work", "tree trim", Axe],
  ["Shovel", "Tools & site work", "excavation trench", Shovel],
  ["Ruler", "Tools & site work", "measure layout", Ruler],
  ["Wrench", "Tools & site work", "mechanical service", Wrench],
  ["SprayCan", "Tools & site work", "paint coating", SprayCan],
  ["Paintbrush", "Tools & site work", "finishing touchup", Paintbrush],
  ["Compass", "Tools & site work", "survey layout", Compass],
  ["Telescope", "Tools & site work", "alignment optics", Telescope],
  ["Binoculars", "Tools & site work", "inspection locate", Binoculars],
  ["BadgeCheck", "Safety & compliance", "certified inspection", BadgeCheck],
  ["BadgePercent", "Safety & compliance", "warranty terms", BadgePercent],
  ["TriangleAlert", "Safety & compliance", "hazard warning", TriangleAlert],
  ["AlertTriangle", "Safety & compliance", "incident caution", AlertTriangle],
  ["OctagonAlert", "Safety & compliance", "stop lockout tagout", OctagonAlert],
  ["DoorClosed", "Building & access", "entry secure", DoorClosed],
  ["DoorOpen", "Building & access", "access egress", DoorOpen],
  ["Building2", "Building & access", "facilities bms", Building2],
  ["Landmark", "Building & access", "public campus", Landmark],
  ["Bed", "Building & access", "lodging hospitality", Bed],
  ["LeafyGreen", "Building & access", "grounds irrigation", LeafyGreen],
  ["Gem", "General", "high value jewelry asset", Gem],
  ["Archive", "General", "records retention", Archive],
  ["CircleDot", "General", "status point io", CircleDot],
  ["Settings", "General", "configuration tune", Settings],
]

export const EQUIPMENT_TYPE_ICON_CATALOG = ICON_ROWS.map(([name, category, keywords]) => ({
  name,
  category,
  keywords,
}))

export const ICON_OPTIONS = ICON_ROWS.map(([name]) => name) as readonly string[]

export type IconName = string

const EQUIPMENT_TYPE_ICON_MAP = Object.fromEntries(ICON_ROWS.map(([name, , , Icon]) => [name, Icon])) as Record<
  string,
  LucideIcon
>

export function EquipmentTypeIcon({
  name,
  size = 16,
  className,
}: {
  name: string
  size?: number
  className?: string
}) {
  const Icon = EQUIPMENT_TYPE_ICON_MAP[name] ?? Wrench
  return <Icon size={size} className={className} />
}

export function getEquipmentTypeLucideIcon(name: string): LucideIcon {
  return EQUIPMENT_TYPE_ICON_MAP[name] ?? Wrench
}
