/**
 * medology-data.ts
 * All mock data for the Medology Solutions workspace (audiology equipment service).
 * Territory: California — serving audiology clinics, ENT groups, and hearing centers statewide.
 * Shape matches the same interfaces used in mock-data.ts so stores can hot-swap.
 */

import type {
  Customer,
  Equipment,
  WorkOrder,
  MaintenancePlan,
  Technician,
  AdminQuote,
  AdminInvoice,
  NotificationLogEntry,
  AiInsight,
} from "@/lib/mock-data"

// ─── Helpers ──────────────────────────────────────────────────────────────────

function buildRules(emails: string[], phones: string[]) {
  const days = [30, 14, 7, 1] as const
  const rules: MaintenancePlan["notificationRules"] = []
  days.forEach((d) => {
    rules.push({ id: `r-email-${d}`, channel: "Email", triggerDays: d, enabled: true, recipients: emails })
    rules.push({ id: `r-internal-${d}`, channel: "Internal Alert", triggerDays: d, enabled: d <= 7, recipients: ["admin@equipify.ai"] })
    if (phones.length) {
      rules.push({ id: `r-sms-${d}`, channel: "SMS", triggerDays: d, enabled: d <= 7, recipients: phones })
    }
  })
  return rules
}

// ─── Customers ────────────────────────────────────────────────────────────────

export const medCustomers: Customer[] = [
  {
    id: "MC-001",
    name: "Sarah Mitchell",
    company: "Los Angeles Hearing Center",
    status: "Active",
    equipmentCount: 6,
    openWorkOrders: 2,
    joinedDate: "2021-03-12",
    locations: [
      { id: "ML-001", name: "Westside Clinic", address: "8500 Wilshire Blvd, Ste 210", city: "Los Angeles", state: "CA", zip: "90211" },
      { id: "ML-001B", name: "Downtown Location", address: "445 S Figueroa St, Ste 1100", city: "Los Angeles", state: "CA", zip: "90071" },
    ],
    contacts: [
      { name: "Sarah Mitchell", role: "Audiologist / Owner", email: "s.mitchell@lahearingcenter.com", phone: "(310) 555-0181" },
      { name: "Kevin Ortega", role: "Office Manager", email: "k.ortega@lahearingcenter.com", phone: "(310) 555-0182" },
    ],
    notes: "Top account — annual calibration package in place. Preferred morning appointments. Two locations served.",
    contracts: [
      { id: "MC-CON-101", name: "Annual Calibration Package", type: "PM Plan", startDate: "2026-01-01", endDate: "2026-12-31", value: 9800 },
    ],
  },
  {
    id: "MC-002",
    name: "Dr. James Carter",
    company: "San Diego Audiology Clinic",
    status: "Active",
    equipmentCount: 5,
    openWorkOrders: 3,
    joinedDate: "2022-06-01",
    locations: [
      { id: "ML-002", name: "Mission Valley Clinic", address: "6755 Mira Mesa Blvd, Ste 123", city: "San Diego", state: "CA", zip: "92121" },
    ],
    contacts: [
      { name: "Dr. James Carter", role: "Lead Audiologist", email: "j.carter@sdaudiology.com", phone: "(619) 555-0245" },
    ],
    notes: "3 devices due within 30 days. Confirm appointments 48 hours in advance.",
    contracts: [
      { id: "MC-CON-102", name: "Equipment Service Agreement", type: "Full Coverage", startDate: "2025-07-01", endDate: "2026-06-30", value: 7200 },
    ],
  },
  {
    id: "MC-003",
    name: "Melissa Vaughn",
    company: "Bay Area ENT Group",
    status: "Active",
    equipmentCount: 8,
    openWorkOrders: 1,
    joinedDate: "2020-10-05",
    locations: [
      { id: "ML-003", name: "San Jose Medical Center", address: "2400 Moorpark Ave, Ste 300", city: "San Jose", state: "CA", zip: "95128" },
      { id: "ML-003B", name: "Oakland Office", address: "3300 Webster St, Ste 410", city: "Oakland", state: "CA", zip: "94609" },
    ],
    contacts: [
      { name: "Melissa Vaughn", role: "Practice Manager", email: "m.vaughn@bayareaentgroup.com", phone: "(408) 555-0312" },
      { name: "Dr. Alan Cho", role: "ENT Physician", email: "a.cho@bayareaentgroup.com", phone: "(408) 555-0313" },
    ],
    notes: "Multi-physician practice. ABR system is primary diagnostic tool. HIPAA-compliant service documentation required.",
    contracts: [
      { id: "MC-CON-103", name: "ENT Diagnostic Service Plan", type: "Full Coverage", startDate: "2026-01-01", endDate: "2026-12-31", value: 14200 },
    ],
  },
  {
    id: "MC-004",
    name: "Amanda Foster",
    company: "Orange County Hearing Care",
    status: "Active",
    equipmentCount: 4,
    openWorkOrders: 1,
    joinedDate: "2023-02-19",
    locations: [
      { id: "ML-004", name: "Irvine Clinic", address: "18500 Von Karman Ave, Ste 150", city: "Irvine", state: "CA", zip: "92612" },
    ],
    contacts: [
      { name: "Amanda Foster", role: "Audiologist / Owner", email: "a.foster@ochearingcare.com", phone: "(949) 555-0417" },
    ],
    notes: "Growing practice — strong candidate for multi-year service agreement and REM system upgrade.",
    contracts: [
      { id: "MC-CON-104", name: "Annual Verification Plan", type: "PM Plan", startDate: "2026-03-01", endDate: "2027-02-28", value: 4400 },
    ],
  },
  {
    id: "MC-005",
    name: "Dr. Ryan Keller",
    company: "Sacramento Pediatric Audiology",
    status: "Active",
    equipmentCount: 5,
    openWorkOrders: 2,
    joinedDate: "2022-08-15",
    locations: [
      { id: "ML-005", name: "Midtown Clinic", address: "1020 29th St, Ste 200", city: "Sacramento", state: "CA", zip: "95816" },
    ],
    contacts: [
      { name: "Dr. Ryan Keller", role: "Pediatric Audiologist", email: "r.keller@sacpedaud.com", phone: "(916) 555-0528" },
    ],
    notes: "Pediatric compliance standards apply (JCAHO). OAE system overdue — priority scheduling required.",
    contracts: [
      { id: "MC-CON-105", name: "Pediatric Compliance Plan", type: "Full Coverage", startDate: "2026-01-01", endDate: "2026-12-31", value: 8100 },
    ],
  },
  {
    id: "MC-006",
    name: "Lauren Hayes",
    company: "Central Valley Diagnostic Hearing",
    status: "Active",
    equipmentCount: 5,
    openWorkOrders: 1,
    joinedDate: "2021-09-20",
    locations: [
      { id: "ML-006", name: "Fresno Main Office", address: "6445 N First St, Ste 105", city: "Fresno", state: "CA", zip: "93710" },
    ],
    contacts: [
      { name: "Lauren Hayes", role: "Audiologist / Owner", email: "l.hayes@cvdiaghearing.com", phone: "(559) 555-0634" },
    ],
    notes: "IAC Sound Booth due for annual acoustic inspection. ASHA compliance documentation required.",
    contracts: [
      { id: "MC-CON-106", name: "Annual Sound Booth Inspection Plan", type: "PM Plan", startDate: "2026-01-01", endDate: "2026-12-31", value: 3200 },
    ],
  },
  {
    id: "MC-007",
    name: "Daniel Brooks",
    company: "Coastal Hearing Institute",
    status: "Active",
    equipmentCount: 4,
    openWorkOrders: 1,
    joinedDate: "2023-01-10",
    locations: [
      { id: "ML-007", name: "Santa Barbara Office", address: "215 W Pueblo St, Ste 110", city: "Santa Barbara", state: "CA", zip: "93105" },
    ],
    contacts: [
      { name: "Daniel Brooks", role: "Audiologist / Owner", email: "d.brooks@coastalhearinginst.com", phone: "(805) 555-0741" },
    ],
    notes: "Welch Allyn Video Otoscope due for annual inspection. New client — build strong service relationship.",
    contracts: [
      { id: "MC-CON-107", name: "Annual Inspection Plan", type: "PM Plan", startDate: "2026-02-01", endDate: "2027-01-31", value: 2800 },
    ],
  },
  {
    id: "MC-008",
    name: "Erin Lawson",
    company: "Sierra Balance Center",
    status: "Active",
    equipmentCount: 3,
    openWorkOrders: 1,
    joinedDate: "2023-05-08",
    locations: [
      { id: "ML-008", name: "Riverside Clinic", address: "3801 University Ave, Ste 260", city: "Riverside", state: "CA", zip: "92501" },
    ],
    contacts: [
      { name: "Erin Lawson", role: "Vestibular Specialist", email: "e.lawson@sierrabalancecenter.com", phone: "(951) 555-0852" },
    ],
    notes: "VNG system is critical — semi-annual PM required for vestibular lab accreditation. Repeat camera alignment pattern flagged.",
    contracts: [
      { id: "MC-CON-108", name: "Semi-Annual Balance Equipment PM", type: "PM Plan", startDate: "2026-01-01", endDate: "2026-12-31", value: 5600 },
    ],
  },
]

// ─── Equipment ────────────────────────────────────────────────────────────────

export const medEquipment: Equipment[] = [
  {
    id: "ME-001",
    customerId: "MC-001",
    customerName: "Los Angeles Hearing Center",
    model: "AudioStar Pro",
    manufacturer: "GSI",
    category: "Audiometer",
    serialNumber: "GSI-AUD-10482",
    installDate: "2021-04-15",
    warrantyExpiration: "2024-04-15",
    lastServiceDate: "2025-05-14",
    nextDueDate: "2026-05-14",
    status: "Active",
    notes: "Annual calibration. Primary audiometer for speech and pure-tone testing.",
    location: "Westside Clinic",
    photos: [],
    manuals: [],
    serviceHistory: [
      { id: "SH-M001", date: "2025-05-14", type: "PM", technician: "Emily Carter", workOrderId: "MWO-1010", description: "Annual calibration — all channels within ANSI spec.", cost: 480, status: "Completed" },
      { id: "SH-M002", date: "2024-05-09", type: "PM", technician: "Emily Carter", workOrderId: "MWO-0881", description: "Annual calibration completed.", cost: 480, status: "Completed" },
    ],
  },
  {
    id: "ME-002",
    customerId: "MC-002",
    customerName: "San Diego Audiology Clinic",
    model: "Titan Tympanometer",
    manufacturer: "Interacoustics",
    category: "Tympanometer",
    serialNumber: "TIT-88241",
    installDate: "2021-08-15",
    warrantyExpiration: "2024-08-15",
    lastServiceDate: "2025-05-03",
    nextDueDate: "2026-05-03",
    status: "Needs Service",
    notes: "Annual calibration. Probe tip replaced at last service.",
    location: "Mission Valley Clinic",
    photos: [],
    manuals: [],
    serviceHistory: [
      { id: "SH-M003", date: "2025-05-03", type: "PM", technician: "Emily Carter", workOrderId: "MWO-1020", description: "Annual calibration. Probe tip replaced.", cost: 380, status: "Completed" },
    ],
  },
  {
    id: "ME-003",
    customerId: "MC-003",
    customerName: "Bay Area ENT Group",
    model: "Bio-logic ABR System",
    manufacturer: "Natus",
    category: "ABR System",
    serialNumber: "ABR-55029",
    installDate: "2020-11-20",
    warrantyExpiration: "2023-11-20",
    lastServiceDate: "2025-07-19",
    nextDueDate: "2026-07-19",
    status: "Active",
    notes: "Annual PM + calibration. Electrode cables replaced at last service.",
    location: "San Jose Medical Center",
    photos: [],
    manuals: [],
    serviceHistory: [
      { id: "SH-M004", date: "2025-07-19", type: "PM", technician: "Josh Reynolds", workOrderId: "MWO-1030", description: "Annual PM and calibration. Electrode cables replaced.", cost: 620, status: "Completed" },
    ],
  },
  {
    id: "ME-004",
    customerId: "MC-005",
    customerName: "Sacramento Pediatric Audiology",
    model: "ILO292 OAE System",
    manufacturer: "Otodynamics",
    category: "OAE System",
    serialNumber: "OAE-21044",
    installDate: "2021-04-05",
    warrantyExpiration: "2024-04-05",
    lastServiceDate: "2025-04-10",
    nextDueDate: "2026-04-10",
    status: "Needs Service",
    notes: "Annual calibration. Overdue — priority scheduling required.",
    location: "Midtown Clinic",
    photos: [],
    manuals: [],
    serviceHistory: [
      { id: "SH-M005", date: "2025-04-10", type: "PM", technician: "Josh Reynolds", workOrderId: "MWO-1040", description: "Annual calibration completed.", cost: 390, status: "Completed" },
    ],
  },
  {
    id: "ME-005",
    customerId: "MC-008",
    customerName: "Sierra Balance Center",
    model: "EyeSeeCam VNG System",
    manufacturer: "Interacoustics",
    category: "VNG System",
    serialNumber: "VNG-77218",
    installDate: "2022-09-01",
    warrantyExpiration: "2025-09-01",
    lastServiceDate: "2025-12-21",
    nextDueDate: "2026-06-21",
    status: "Active",
    notes: "Semi-annual PM. Camera alignment critical. Repeat alignment pattern — 3 of last 4 visits.",
    location: "Riverside Clinic",
    photos: [],
    manuals: [],
    serviceHistory: [
      { id: "SH-M006", date: "2025-12-21", type: "PM", technician: "Brandon Ellis", workOrderId: "MWO-1050", description: "Semi-annual PM. Camera alignment within spec.", cost: 540, status: "Completed" },
      { id: "SH-M006B", date: "2025-06-14", type: "PM", technician: "Brandon Ellis", workOrderId: "MWO-0940", description: "Camera re-alignment required. Caloric irrigator verified.", cost: 540, status: "Completed" },
    ],
  },
  {
    id: "ME-006",
    customerId: "MC-004",
    customerName: "Orange County Hearing Care",
    model: "AVANT REM System",
    manufacturer: "MedRx",
    category: "Real Ear Measurement System",
    serialNumber: "REM-44191",
    installDate: "2023-02-10",
    warrantyExpiration: "2026-02-10",
    lastServiceDate: "2025-08-08",
    nextDueDate: "2026-08-08",
    status: "Active",
    notes: "Annual verification. Under warranty through Feb 2026.",
    location: "Irvine Clinic",
    photos: [],
    manuals: [],
    serviceHistory: [
      { id: "SH-M007", date: "2025-08-08", type: "PM", technician: "Emily Carter", workOrderId: "MWO-1060", description: "Annual verification pass.", cost: 320, status: "Completed" },
    ],
  },
  {
    id: "ME-007",
    customerId: "MC-006",
    customerName: "Central Valley Diagnostic Hearing",
    model: "Acoustic Systems Room",
    manufacturer: "IAC",
    category: "Sound Booth / Sound Room",
    serialNumber: "SB-90312",
    installDate: "2019-06-15",
    warrantyExpiration: "2022-06-15",
    lastServiceDate: "2025-09-12",
    nextDueDate: "2026-09-12",
    status: "Active",
    notes: "Annual acoustic inspection. Room attenuation verified at last service.",
    location: "Fresno Main Office",
    photos: [],
    manuals: [],
    serviceHistory: [
      { id: "SH-M008", date: "2025-09-12", type: "Inspection", technician: "Emily Carter", workOrderId: "MWO-1070", description: "Annual acoustic inspection — attenuation within ANSI S3.1 limits.", cost: 750, status: "Completed" },
    ],
  },
  {
    id: "ME-008",
    customerId: "MC-007",
    customerName: "Coastal Hearing Institute",
    model: "MacroView Video Otoscope",
    manufacturer: "Welch Allyn",
    category: "Otoscope / Video Otoscope",
    serialNumber: "OTO-78440",
    installDate: "2023-05-22",
    warrantyExpiration: "2026-05-22",
    lastServiceDate: "2025-05-22",
    nextDueDate: "2026-05-22",
    status: "Needs Service",
    notes: "Annual inspection. Under warranty.",
    location: "Santa Barbara Office",
    photos: [],
    manuals: [],
    serviceHistory: [
      { id: "SH-M009", date: "2025-05-22", type: "Inspection", technician: "Brandon Ellis", workOrderId: "MWO-1080", description: "Annual inspection. Tip and light source checked.", cost: 180, status: "Completed" },
    ],
  },
]

// ─── Work Orders ──────────────────────────────────────────────────────────────

export const medWorkOrders: WorkOrder[] = [
  {
    id: "MWO-2041",
    customerId: "MC-001",
    customerName: "Los Angeles Hearing Center",
    equipmentId: "ME-001",
    equipmentName: "GSI AudioStar Pro Audiometer",
    location: "Westside Clinic",
    type: "PM",
    status: "Scheduled",
    priority: "Normal",
    technicianId: "MT-02",
    technicianName: "Emily Carter",
    scheduledDate: "2026-05-14",
    scheduledTime: "09:00",
    completedDate: "",
    createdAt: "2026-04-28T08:00:00Z",
    createdBy: "Megan Brooks",
    description: "Annual audiometer calibration — GSI AudioStar Pro. ANSI S3.6 protocol.",
    totalLaborCost: 0,
    totalPartsCost: 0,
    invoiceNumber: "",
    repairLog: { problemReported: "Annual calibration due.", diagnosis: "", partsUsed: [], laborHours: 0, technicianNotes: "", photos: [], signatureDataUrl: "", signedBy: "", signedAt: "" },
  },
  {
    id: "MWO-2040",
    customerId: "MC-002",
    customerName: "San Diego Audiology Clinic",
    equipmentId: "ME-002",
    equipmentName: "Interacoustics Titan Tympanometer",
    location: "Mission Valley Clinic",
    type: "Repair",
    status: "In Progress",
    priority: "High",
    technicianId: "MT-02",
    technicianName: "Emily Carter",
    scheduledDate: "2026-05-03",
    scheduledTime: "10:00",
    completedDate: "",
    createdAt: "2026-04-25T09:00:00Z",
    createdBy: "Megan Brooks",
    description: "Probe tip issue — intermittent seal failure affecting tympanogram readings.",
    totalLaborCost: 180,
    totalPartsCost: 45,
    invoiceNumber: "",
    repairLog: { problemReported: "Probe tip seal intermittently failing. Readings inconsistent.", diagnosis: "Worn probe tip assembly. Seal degraded.", partsUsed: [{ id: "MP-001", name: "Probe Tip Assembly", partNumber: "TIT-PROBE-KIT", quantity: 1, unitCost: 45 }], laborHours: 1.5, technicianNotes: "Replaced probe tip. Will verify seal integrity at next calibration.", photos: [], signatureDataUrl: "", signedBy: "", signedAt: "" },
  },
  {
    id: "MWO-2039",
    customerId: "MC-003",
    customerName: "Bay Area ENT Group",
    equipmentId: "ME-003",
    equipmentName: "Natus Bio-logic ABR System",
    location: "San Jose Medical Center",
    type: "Repair",
    status: "In Progress",
    priority: "High",
    technicianId: "MT-01",
    technicianName: "Josh Reynolds",
    scheduledDate: "2026-05-02",
    scheduledTime: "08:00",
    completedDate: "",
    createdAt: "2026-04-22T11:00:00Z",
    createdBy: "Megan Brooks",
    description: "ABR electrode cable replacement — channels 2 and 3 showing impedance errors.",
    totalLaborCost: 0,
    totalPartsCost: 0,
    invoiceNumber: "",
    repairLog: { problemReported: "Channels 2 and 3 showing high impedance. Suspected cable fault.", diagnosis: "Cable insulation breach on CH2 and CH3 leads.", partsUsed: [], laborHours: 0, technicianNotes: "Awaiting Natus electrode cable kit. ETA 2026-05-01.", photos: [], signatureDataUrl: "", signedBy: "", signedAt: "" },
  },
  {
    id: "MWO-2038",
    customerId: "MC-005",
    customerName: "Sacramento Pediatric Audiology",
    equipmentId: "ME-004",
    equipmentName: "Otodynamics ILO292 OAE System",
    location: "Midtown Clinic",
    type: "PM",
    status: "Open",
    priority: "Critical",
    technicianId: "MT-01",
    technicianName: "Josh Reynolds",
    scheduledDate: "2026-05-01",
    scheduledTime: "08:30",
    completedDate: "",
    createdAt: "2026-04-28T14:00:00Z",
    createdBy: "Megan Brooks",
    description: "OAE probe calibration — overdue since April 10. Pediatric compliance risk.",
    totalLaborCost: 0,
    totalPartsCost: 0,
    invoiceNumber: "",
    repairLog: { problemReported: "Annual calibration overdue. Pediatric compliance at risk.", diagnosis: "", partsUsed: [], laborHours: 0, technicianNotes: "", photos: [], signatureDataUrl: "", signedBy: "", signedAt: "" },
  },
  {
    id: "MWO-2037",
    customerId: "MC-008",
    customerName: "Sierra Balance Center",
    equipmentId: "ME-005",
    equipmentName: "Interacoustics EyeSeeCam VNG System",
    location: "Riverside Clinic",
    type: "PM",
    status: "Scheduled",
    priority: "Normal",
    technicianId: "MT-03",
    technicianName: "Brandon Ellis",
    scheduledDate: "2026-06-21",
    scheduledTime: "09:30",
    completedDate: "",
    createdAt: "2026-04-29T08:00:00Z",
    createdBy: "Megan Brooks",
    description: "VNG camera alignment and semi-annual PM.",
    totalLaborCost: 0,
    totalPartsCost: 0,
    invoiceNumber: "",
    repairLog: { problemReported: "Semi-annual PM due.", diagnosis: "", partsUsed: [], laborHours: 0, technicianNotes: "", photos: [], signatureDataUrl: "", signedBy: "", signedAt: "" },
  },
  {
    id: "MWO-2036",
    customerId: "MC-006",
    customerName: "Central Valley Diagnostic Hearing",
    equipmentId: "ME-007",
    equipmentName: "IAC Sound Booth",
    location: "Fresno Main Office",
    type: "Inspection",
    status: "Scheduled",
    priority: "Normal",
    technicianId: "MT-02",
    technicianName: "Emily Carter",
    scheduledDate: "2026-09-12",
    scheduledTime: "08:00",
    completedDate: "",
    createdAt: "2026-04-15T08:00:00Z",
    createdBy: "Megan Brooks",
    description: "Annual acoustic inspection. Verify room attenuation per ANSI S3.1.",
    totalLaborCost: 0,
    totalPartsCost: 0,
    invoiceNumber: "",
    repairLog: { problemReported: "Annual acoustic inspection due.", diagnosis: "", partsUsed: [], laborHours: 0, technicianNotes: "", photos: [], signatureDataUrl: "", signedBy: "", signedAt: "" },
  },
  {
    id: "MWO-2035",
    customerId: "MC-004",
    customerName: "Orange County Hearing Care",
    equipmentId: "ME-006",
    equipmentName: "MedRx AVANT REM System",
    location: "Irvine Clinic",
    type: "PM",
    status: "Scheduled",
    priority: "Normal",
    technicianId: "MT-02",
    technicianName: "Emily Carter",
    scheduledDate: "2026-08-08",
    scheduledTime: "10:00",
    completedDate: "",
    createdAt: "2026-04-15T09:00:00Z",
    createdBy: "Megan Brooks",
    description: "Annual real ear system verification.",
    totalLaborCost: 0,
    totalPartsCost: 0,
    invoiceNumber: "",
    repairLog: { problemReported: "Annual verification due.", diagnosis: "", partsUsed: [], laborHours: 0, technicianNotes: "", photos: [], signatureDataUrl: "", signedBy: "", signedAt: "" },
  },
  {
    id: "MWO-2034",
    customerId: "MC-001",
    customerName: "Los Angeles Hearing Center",
    equipmentId: "ME-001",
    equipmentName: "GSI AudioStar Pro Audiometer",
    location: "Westside Clinic",
    type: "Repair",
    status: "Completed",
    priority: "High",
    technicianId: "MT-02",
    technicianName: "Emily Carter",
    scheduledDate: "2026-04-10",
    scheduledTime: "09:00",
    completedDate: "2026-04-10",
    createdAt: "2026-04-08T09:00:00Z",
    createdBy: "Megan Brooks",
    description: "Audiometer output error — channel 4 reading 8 dB below calibration spec.",
    totalLaborCost: 320,
    totalPartsCost: 0,
    invoiceNumber: "MINV-3001",
    repairLog: {
      problemReported: "Channel 4 output error. Readings 8 dB below spec.",
      diagnosis: "Attenuator board calibration drift. Recalibrated to ANSI S3.6.",
      partsUsed: [],
      laborHours: 2.5,
      technicianNotes: "Emergency visit. Board recalibrated, all channels now within ±1 dB. Follow-up annual cal still due May 14.",
      photos: [],
      signatureDataUrl: "SIGNED",
      signedBy: "Sarah Mitchell",
      signedAt: "2026-04-10T14:30:00Z",
    },
  },
]

// ─── Maintenance Plans ────────────────────────────────────────────────────────

export const medMaintenancePlans: MaintenancePlan[] = [
  {
    id: "MMP-001",
    name: "Annual Audiometer Calibration Plan",
    customerId: "MC-001",
    customerName: "Los Angeles Hearing Center",
    equipmentId: "ME-001",
    equipmentName: "GSI AudioStar Pro Audiometer",
    equipmentCategory: "Audiometer",
    location: "Westside Clinic",
    technicianId: "MT-02",
    technicianName: "Emily Carter",
    interval: "Annual",
    customIntervalDays: 0,
    status: "Active",
    startDate: "2021-05-14",
    lastServiceDate: "2025-05-14",
    nextDueDate: "2026-05-14",
    services: [
      { id: "MSVC-001", name: "Pure-Tone Calibration", description: "Calibrate all frequencies per ANSI S3.6", estimatedHours: 1.5, estimatedCost: 280 },
      { id: "MSVC-002", name: "Speech Output Verification", description: "Verify speech levels and distortion", estimatedHours: 0.5, estimatedCost: 100 },
      { id: "MSVC-003", name: "Headphone & Bone Conductor Check", description: "Verify transducer output", estimatedHours: 0.5, estimatedCost: 100 },
    ],
    notificationRules: buildRules(["s.mitchell@lahearingcenter.com", "k.ortega@lahearingcenter.com"], ["(310) 555-0181"]),
    autoCreateWorkOrder: true,
    workOrderType: "PM",
    workOrderPriority: "Normal",
    notes: "ANSI S3.6 compliance required. Bring calibration certificate.",
    createdAt: "2021-05-14T08:00:00Z",
    totalServicesCompleted: 4,
  },
  {
    id: "MMP-002",
    name: "Semi-Annual Balance Equipment PM",
    customerId: "MC-008",
    customerName: "Sierra Balance Center",
    equipmentId: "ME-005",
    equipmentName: "Interacoustics EyeSeeCam VNG System",
    equipmentCategory: "VNG System",
    location: "Riverside Clinic",
    technicianId: "MT-03",
    technicianName: "Brandon Ellis",
    interval: "Semi-Annual",
    customIntervalDays: 0,
    status: "Active",
    startDate: "2022-09-01",
    lastServiceDate: "2025-12-21",
    nextDueDate: "2026-06-21",
    services: [
      { id: "MSVC-004", name: "VNG Camera Alignment", description: "Align IR cameras to ANSI protocol", estimatedHours: 1, estimatedCost: 200 },
      { id: "MSVC-005", name: "Caloric Irrigator Check", description: "Verify temperature accuracy and flow rate", estimatedHours: 0.5, estimatedCost: 80 },
      { id: "MSVC-006", name: "Software Diagnostic Check", description: "Run system self-test suite", estimatedHours: 0.5, estimatedCost: 60 },
    ],
    notificationRules: buildRules(["e.lawson@sierrabalancecenter.com"], ["(951) 555-0852"]),
    autoCreateWorkOrder: true,
    workOrderType: "PM",
    workOrderPriority: "Normal",
    notes: "Semi-annual required for vestibular lab accreditation.",
    createdAt: "2022-09-01T08:00:00Z",
    totalServicesCompleted: 6,
  },
  {
    id: "MMP-003",
    name: "Pediatric Audiology Equipment Compliance Plan",
    customerId: "MC-005",
    customerName: "Sacramento Pediatric Audiology",
    equipmentId: "ME-004",
    equipmentName: "Otodynamics ILO292 OAE System",
    equipmentCategory: "OAE System",
    location: "Midtown Clinic",
    technicianId: "MT-01",
    technicianName: "Josh Reynolds",
    interval: "Annual",
    customIntervalDays: 0,
    status: "Active",
    startDate: "2022-04-10",
    lastServiceDate: "2025-04-10",
    nextDueDate: "2026-04-10",
    services: [
      { id: "MSVC-007", name: "OAE Probe Calibration", description: "Calibrate probe microphone per ANSI S3.39", estimatedHours: 1, estimatedCost: 180 },
      { id: "MSVC-008", name: "Stimulus Level Verification", description: "Verify DPOAE and TEOAE stimulus levels", estimatedHours: 0.5, estimatedCost: 90 },
    ],
    notificationRules: buildRules(["r.keller@sacpedaud.com"], ["(916) 555-0528"]),
    autoCreateWorkOrder: true,
    workOrderType: "PM",
    workOrderPriority: "High",
    notes: "Pediatric compliance — JCAHO standards. Must provide calibration certificate.",
    createdAt: "2022-04-10T08:00:00Z",
    totalServicesCompleted: 3,
  },
  {
    id: "MMP-004",
    name: "ENT Diagnostic Equipment Service Plan",
    customerId: "MC-003",
    customerName: "Bay Area ENT Group",
    equipmentId: "ME-003",
    equipmentName: "Natus Bio-logic ABR System",
    equipmentCategory: "ABR System",
    location: "San Jose Medical Center",
    technicianId: "MT-01",
    technicianName: "Josh Reynolds",
    interval: "Annual",
    customIntervalDays: 0,
    status: "Active",
    startDate: "2021-07-19",
    lastServiceDate: "2025-07-19",
    nextDueDate: "2026-07-19",
    services: [
      { id: "MSVC-009", name: "ABR System PM", description: "Full PM including electrode cable check", estimatedHours: 2, estimatedCost: 380 },
      { id: "MSVC-010", name: "Calibration Verification", description: "Verify click and tone-burst stimuli", estimatedHours: 1, estimatedCost: 200 },
    ],
    notificationRules: buildRules(["m.vaughn@bayareaentgroup.com"], ["(408) 555-0312"]),
    autoCreateWorkOrder: true,
    workOrderType: "PM",
    workOrderPriority: "Normal",
    notes: "HIPAA-compliant service documentation required.",
    createdAt: "2021-07-19T08:00:00Z",
    totalServicesCompleted: 4,
  },
  {
    id: "MMP-005",
    name: "Sound Booth Annual Inspection Plan",
    customerId: "MC-006",
    customerName: "Central Valley Diagnostic Hearing",
    equipmentId: "ME-007",
    equipmentName: "IAC Sound Booth",
    equipmentCategory: "Sound Booth / Sound Room",
    location: "Fresno Main Office",
    technicianId: "MT-02",
    technicianName: "Emily Carter",
    interval: "Annual",
    customIntervalDays: 0,
    status: "Active",
    startDate: "2020-09-12",
    lastServiceDate: "2025-09-12",
    nextDueDate: "2026-09-12",
    services: [
      { id: "MSVC-011", name: "Acoustic Attenuation Test", description: "Measure room attenuation per ANSI S3.1", estimatedHours: 2, estimatedCost: 450 },
      { id: "MSVC-012", name: "Seal & Door Inspection", description: "Inspect acoustic seals and door gaskets", estimatedHours: 0.5, estimatedCost: 80 },
      { id: "MSVC-013", name: "Ambient Noise Level Check", description: "Measure background noise levels in all octave bands", estimatedHours: 0.5, estimatedCost: 80 },
    ],
    notificationRules: buildRules(["l.hayes@cvdiaghearing.com"], ["(559) 555-0634"]),
    autoCreateWorkOrder: true,
    workOrderType: "Inspection",
    workOrderPriority: "Normal",
    notes: "ANSI S3.1 and ASHA compliance. Provide acoustic report.",
    createdAt: "2020-09-12T08:00:00Z",
    totalServicesCompleted: 5,
  },
]

export const medNotificationLog: NotificationLogEntry[] = [
  {
    id: "MNL-001", planId: "MMP-003", planName: "Pediatric Audiology Equipment Compliance Plan",
    equipmentName: "Otodynamics ILO292 OAE System", customerName: "Sacramento Pediatric Audiology",
    channel: "Email", triggerDays: 30, sentAt: "2026-03-11T08:00:00Z",
    recipient: "r.keller@sacpedaud.com",
    message: "Reminder: OAE System calibration is due in 30 days (2026-04-10).",
    status: "Sent",
  },
  {
    id: "MNL-002", planId: "MMP-003", planName: "Pediatric Audiology Equipment Compliance Plan",
    equipmentName: "Otodynamics ILO292 OAE System", customerName: "Sacramento Pediatric Audiology",
    channel: "SMS", triggerDays: 7, sentAt: "2026-04-03T08:00:00Z",
    recipient: "(916) 555-0528",
    message: "Equipify: OAE System calibration due in 7 days (2026-04-10).",
    status: "Sent",
  },
]

// ─── Technicians ──────────────────────────────────────────────────────────────

export const medTechnicians: Technician[] = [
  {
    id: "MT-01",
    name: "Josh Reynolds",
    avatar: "JR",
    role: "Senior Audiology Equipment Technician",
    region: "Northern California",
    email: "j.reynolds@medology.com",
    phone: "(415) 555-1001",
    hireDate: "2019-04-08",
    status: "On Job",
    skills: ["Audiometers", "ABR Systems", "Tympanometers", "OAE Systems"],
    jobsThisWeek: 5,
    completionPct: 97,
    rating: 4.9,
    utilizationPct: 91,
    totalCompleted: 284,
    avgJobDurationHrs: 2.8,
    bio: "Josh is a senior audiology equipment technician with 7 years of field experience. He specializes in diagnostic audiology instrumentation across the Bay Area, Sacramento, and San Diego territories. ACAE and ISO 17025 certified.",
    certifications: [
      { name: "ACAE Certified Electroacoustic Technician", issuer: "ACAE", issuedDate: "2021-06-01", expiryDate: "2027-06-01" },
      { name: "ISO 17025 Internal Auditor", issuer: "ANSI", issuedDate: "2022-03-15", expiryDate: "2027-03-15" },
      { name: "OSHA 10", issuer: "OSHA", issuedDate: "2020-08-10", expiryDate: "2026-08-10" },
    ],
    schedule: [
      { date: "2026-05-01", time: "08:30 AM", customer: "Sacramento Pediatric Audiology", jobType: "OAE Probe Calibration", woId: "MWO-2038", status: "Confirmed" },
      { date: "2026-05-02", time: "08:00 AM", customer: "Bay Area ENT Group", jobType: "ABR Cable Replacement", woId: "MWO-2039", status: "Confirmed" },
    ],
    history: [
      { woId: "MWO-1030", customer: "Bay Area ENT Group", jobType: "ABR Annual PM", completedDate: "2025-07-19", duration: "4.0 hrs", rating: 5 },
      { woId: "MWO-1040", customer: "Sacramento Pediatric Audiology", jobType: "OAE Annual Calibration", completedDate: "2025-04-10", duration: "2.5 hrs", rating: 5 },
    ],
  },
  {
    id: "MT-02",
    name: "Emily Carter",
    avatar: "EC",
    role: "Calibration Specialist",
    region: "Southern California",
    email: "e.carter@medology.com",
    phone: "(213) 555-1002",
    hireDate: "2020-09-14",
    status: "Available",
    skills: ["Audiometers", "Sound Booths", "Real Ear Systems", "Calibration"],
    jobsThisWeek: 4,
    completionPct: 99,
    rating: 4.9,
    utilizationPct: 82,
    totalCompleted: 210,
    avgJobDurationHrs: 3.1,
    bio: "Emily specializes in precision calibration of audiometers, real-ear systems, and acoustic enclosures. She is the primary technician for Los Angeles, Orange County, and Central Valley accounts, and leads all ANSI compliance work.",
    certifications: [
      { name: "ISO 17025 Lead Auditor", issuer: "ANSI", issuedDate: "2021-11-20", expiryDate: "2026-11-20" },
      { name: "ACAE Certified Electroacoustic Technician", issuer: "ACAE", issuedDate: "2022-01-05", expiryDate: "2027-01-05" },
    ],
    schedule: [
      { date: "2026-05-03", time: "10:00 AM", customer: "San Diego Audiology Clinic", jobType: "Tympanometer Probe Issue", woId: "MWO-2040", status: "Confirmed" },
      { date: "2026-05-14", time: "09:00 AM", customer: "Los Angeles Hearing Center", jobType: "Annual Audiometer Calibration", woId: "MWO-2041", status: "Confirmed" },
    ],
    history: [
      { woId: "MWO-1010", customer: "Los Angeles Hearing Center", jobType: "Annual Audiometer Calibration", completedDate: "2025-05-14", duration: "2.5 hrs", rating: 5 },
      { woId: "MWO-1060", customer: "Orange County Hearing Care", jobType: "REM Annual Verification", completedDate: "2025-08-08", duration: "2.0 hrs", rating: 5 },
      { woId: "MWO-1070", customer: "Central Valley Diagnostic Hearing", jobType: "Sound Booth Acoustic Inspection", completedDate: "2025-09-12", duration: "3.5 hrs", rating: 5 },
    ],
  },
  {
    id: "MT-03",
    name: "Brandon Ellis",
    avatar: "BE",
    role: "Field Service Technician",
    region: "Inland Empire / Central Coast",
    email: "b.ellis@medology.com",
    phone: "(951) 555-1003",
    hireDate: "2021-06-07",
    status: "Available",
    skills: ["VNG Systems", "Balance Systems", "Otoscopes", "Field Service"],
    jobsThisWeek: 3,
    completionPct: 94,
    rating: 4.7,
    utilizationPct: 74,
    totalCompleted: 152,
    avgJobDurationHrs: 2.6,
    bio: "Brandon handles field service for VNG/balance systems and otoscope maintenance across the Inland Empire, Central Coast, and Fresno territories. He is the primary technician for Sierra Balance Center.",
    certifications: [
      { name: "OSHA 10", issuer: "OSHA", issuedDate: "2021-07-01", expiryDate: "2027-07-01" },
    ],
    schedule: [
      { date: "2026-06-21", time: "09:30 AM", customer: "Sierra Balance Center", jobType: "VNG Camera Alignment", woId: "MWO-2037", status: "Confirmed" },
    ],
    history: [
      { woId: "MWO-1050", customer: "Sierra Balance Center", jobType: "VNG Semi-Annual PM", completedDate: "2025-12-21", duration: "3.0 hrs", rating: 5 },
      { woId: "MWO-1080", customer: "Coastal Hearing Institute", jobType: "Video Otoscope Annual Inspection", completedDate: "2025-05-22", duration: "1.5 hrs", rating: 4 },
    ],
  },
  {
    id: "MT-04",
    name: "Megan Brooks",
    avatar: "MB",
    role: "Service Coordinator",
    region: "California Statewide",
    email: "m.brooks@medology.com",
    phone: "(424) 555-1004",
    hireDate: "2022-02-28",
    status: "Available",
    skills: ["Scheduling", "Customer Communication", "PM Plans", "Invoicing"],
    jobsThisWeek: 0,
    completionPct: 100,
    rating: 5.0,
    utilizationPct: 60,
    totalCompleted: 0,
    avgJobDurationHrs: 0,
    bio: "Megan coordinates all scheduling, customer communications, and maintenance plan management for Medology Solutions' California territory. She ensures compliance deadlines are met and clients receive timely updates.",
    certifications: [],
    schedule: [],
    history: [],
  },
]

// ─── Quotes ───────────────────────────────────────────────────────────────────

export const medQuotes: AdminQuote[] = [
  {
    id: "MQT-001",
    customerId: "MC-001",
    customerName: "Los Angeles Hearing Center",
    equipmentId: "ME-001",
    equipmentName: "GSI AudioStar Pro Audiometer",
    createdDate: "2026-04-25",
    expiresDate: "2026-05-25",
    sentDate: "2026-04-25",
    amount: 9800,
    status: "Sent",
    description: "Annual Calibration Package — covers all 6 devices at Los Angeles Hearing Center for 2026.",
    createdBy: "Megan Brooks",
    workOrderId: "",
    notes: "Package rate. Includes calibration certificates for all devices. Both Westside and Downtown locations covered.",
    lineItems: [
      { description: "GSI AudioStar Pro — Annual Calibration", qty: 1, unit: 2200 },
      { description: "Interacoustics Titan — Annual Calibration", qty: 1, unit: 1800 },
      { description: "Otodynamics OAE — Annual Calibration", qty: 1, unit: 1600 },
      { description: "MedRx AVANT REM — Annual Verification", qty: 1, unit: 1400 },
      { description: "Travel & Documentation", qty: 1, unit: 800 },
      { description: "Package Discount", qty: 1, unit: -2000 },
      { description: "Calibration Certificate Bundle", qty: 1, unit: 2000 },
    ],
  },
  {
    id: "MQT-002",
    customerId: "MC-003",
    customerName: "Bay Area ENT Group",
    equipmentId: "ME-003",
    equipmentName: "Natus Bio-logic ABR System",
    createdDate: "2026-04-22",
    expiresDate: "2026-05-22",
    sentDate: "2026-04-23",
    amount: 840,
    status: "Pending Approval",
    description: "Multi-site PM Agreement — Bay Area ENT Group San Jose and Oakland locations.",
    createdBy: "Josh Reynolds",
    workOrderId: "MWO-2039",
    notes: "Covers ABR cable replacement plus annual PM for both locations. HIPAA documentation included.",
    lineItems: [
      { description: "Natus ABR Electrode Cable Kit (CH2 + CH3)", qty: 1, unit: 480 },
      { description: "Cable Replacement Labor", qty: 2, unit: 140 },
      { description: "Post-Repair Impedance Verification", qty: 1, unit: 80 },
    ],
  },
  {
    id: "MQT-003",
    customerId: "MC-006",
    customerName: "Central Valley Diagnostic Hearing",
    equipmentId: "ME-007",
    equipmentName: "IAC Sound Booth",
    createdDate: "2026-04-15",
    expiresDate: "2026-05-15",
    sentDate: "2026-04-15",
    amount: 1380,
    status: "Draft",
    description: "Sound booth annual acoustic inspection — ANSI S3.1 attenuation report for Fresno clinic.",
    createdBy: "Emily Carter",
    workOrderId: "MWO-2036",
    notes: "Full acoustic report included. ASHA compliance documentation provided.",
    lineItems: [
      { description: "Acoustic Attenuation Test (ANSI S3.1)", qty: 1, unit: 750 },
      { description: "Seal & Door Inspection", qty: 1, unit: 220 },
      { description: "Ambient Noise Level Survey", qty: 1, unit: 280 },
      { description: "ANSI Compliance Report", qty: 1, unit: 130 },
    ],
  },
  {
    id: "MQT-004",
    customerId: "MC-004",
    customerName: "Orange County Hearing Care",
    equipmentId: "ME-006",
    equipmentName: "MedRx AVANT REM System",
    createdDate: "2026-04-28",
    expiresDate: "2026-05-28",
    sentDate: "2026-04-29",
    amount: 4800,
    status: "Sent",
    description: "New audiometer installation quote — Orange County Hearing Care Irvine clinic.",
    createdBy: "Megan Brooks",
    workOrderId: "",
    notes: "Includes Grason-Stadler GSI61 audiometer, installation, and first-year calibration. Strong upsell candidate.",
    lineItems: [
      { description: "GSI61 Clinical Audiometer (GSI-AUD-61)", qty: 1, unit: 3200 },
      { description: "Installation & Setup Labor", qty: 2, unit: 200 },
      { description: "First-Year Calibration & Certification", qty: 1, unit: 480 },
      { description: "Travel (Irvine)", qty: 1, unit: 120 },
    ],
  },
]

// ─── Invoices ─────────────────────────────────────────────────────────────────

export const medInvoices: AdminInvoice[] = [
  {
    id: "MINV-3001",
    customerId: "MC-001",
    customerName: "Los Angeles Hearing Center",
    equipmentName: "GSI AudioStar Pro Audiometer",
    workOrderId: "MWO-2034",
    issueDate: "2026-04-10",
    dueDate: "2026-05-10",
    paidDate: "2026-04-18",
    amount: 320,
    status: "Paid",
    createdBy: "Megan Brooks",
    notes: "Emergency repair — audiometer output error. Paid via ACH on 2026-04-18.",
    lineItems: [
      { description: "Emergency Calibration Labor (2.5 hrs)", qty: 2.5, unit: 128 },
    ],
  },
  {
    id: "MINV-3002",
    customerId: "MC-002",
    customerName: "San Diego Audiology Clinic",
    equipmentName: "Interacoustics Titan Tympanometer",
    workOrderId: "MWO-2040",
    issueDate: "2026-05-03",
    dueDate: "2026-06-03",
    paidDate: "",
    amount: 225,
    status: "Sent",
    createdBy: "Megan Brooks",
    notes: "Tympanometer probe tip replacement and partial labor. Net-30.",
    lineItems: [
      { description: "Probe Tip Assembly (TIT-PROBE-KIT)", qty: 1, unit: 45 },
      { description: "Repair Labor (1.5 hrs)", qty: 1.5, unit: 120 },
    ],
  },
  {
    id: "MINV-3003",
    customerId: "MC-005",
    customerName: "Sacramento Pediatric Audiology",
    equipmentName: "Otodynamics ILO292 OAE System",
    workOrderId: "MWO-1040",
    issueDate: "2025-04-10",
    dueDate: "2025-05-10",
    paidDate: "",
    amount: 390,
    status: "Overdue",
    createdBy: "Megan Brooks",
    notes: "Annual OAE system calibration. Overdue 55 days. Second notice sent 2025-05-25.",
    lineItems: [
      { description: "OAE Probe Calibration Labor", qty: 1, unit: 180 },
      { description: "Stimulus Level Verification", qty: 1, unit: 90 },
      { description: "Calibration Certificate", qty: 1, unit: 120 },
    ],
  },
  {
    id: "MINV-3004",
    customerId: "MC-008",
    customerName: "Sierra Balance Center",
    equipmentName: "Interacoustics EyeSeeCam VNG System",
    workOrderId: "MWO-1050",
    issueDate: "2025-12-21",
    dueDate: "2026-01-21",
    paidDate: "2026-01-10",
    amount: 540,
    status: "Paid",
    createdBy: "Brandon Ellis",
    notes: "Semi-annual VNG PM — camera alignment and caloric irrigator verification. Paid in full.",
    lineItems: [
      { description: "VNG Camera Alignment Labor", qty: 2, unit: 150 },
      { description: "Caloric Irrigator Verification", qty: 1, unit: 120 },
      { description: "PM Documentation & Report", qty: 1, unit: 120 },
    ],
  },
]

// ─── Dashboard Stats ──────────────────────────────────────────────────────────

export const medStats = {
  equipmentDueThisMonth: 14,
  overdueService: 3,
  openWorkOrders: 24,
  monthlyRevenue: "$38K",
  revenueSubtitle: "April 2026 — California",
  revenueTrend: "+12.4% vs March",
  expiringWarranties: 3,
  warrantyTrend: "1 expires this week",
  repeatRepairAlerts: 1,
}

export const medRevenueData = [
  { month: "Nov", revenue: 28500 },
  { month: "Dec", revenue: 31200 },
  { month: "Jan", revenue: 27400 },
  { month: "Feb", revenue: 33800 },
  { month: "Mar", revenue: 35600 },
  { month: "Apr", revenue: 38400 },
]

export const medWorkOrdersByStatus = [
  { status: "Open", count: 24, color: "var(--color-chart-1)" },
  { status: "In Progress", count: 8, color: "var(--color-chart-2)" },
  { status: "Completed", count: 62, color: "var(--color-status-success)" },
  { status: "On Hold", count: 4, color: "var(--color-status-warning)" },
]

export const medRecentWorkOrders = [
  {
    id: "MWO-2041",
    customer: "Los Angeles Hearing Center",
    equipment: "GSI AudioStar Pro Audiometer",
    type: "PM",
    technician: "Emily Carter",
    status: "Scheduled",
    priority: "Normal",
    due: "2026-05-14",
  },
  {
    id: "MWO-2040",
    customer: "San Diego Audiology Clinic",
    equipment: "Interacoustics Titan Tympanometer",
    type: "Repair",
    technician: "Emily Carter",
    status: "In Progress",
    priority: "High",
    due: "2026-05-03",
  },
  {
    id: "MWO-2039",
    customer: "Bay Area ENT Group",
    equipment: "Natus Bio-logic ABR System",
    type: "Repair",
    technician: "Josh Reynolds",
    status: "In Progress",
    priority: "High",
    due: "2026-05-02",
  },
  {
    id: "MWO-2038",
    customer: "Sacramento Pediatric Audiology",
    equipment: "Otodynamics ILO292 OAE System",
    type: "PM",
    technician: "Josh Reynolds",
    status: "Open",
    priority: "Critical",
    due: "2026-05-01",
  },
  {
    id: "MWO-2037",
    customer: "Sierra Balance Center",
    equipment: "Interacoustics EyeSeeCam VNG System",
    type: "PM",
    technician: "Brandon Ellis",
    status: "Scheduled",
    priority: "Normal",
    due: "2026-06-21",
  },
]

export const medEquipmentDueSoon = [
  { id: "ME-004", name: "Otodynamics ILO292 OAE System", customer: "Sacramento Pediatric Audiology", nextService: "2026-04-10", type: "Annual Calibration" },
  { id: "ME-002", name: "Interacoustics Titan Tympanometer", customer: "San Diego Audiology Clinic", nextService: "2026-05-03", type: "Annual Calibration" },
  { id: "ME-001", name: "GSI AudioStar Pro Audiometer", customer: "Los Angeles Hearing Center", nextService: "2026-05-14", type: "Annual Calibration" },
  { id: "ME-008", name: "Welch Allyn MacroView Otoscope", customer: "Coastal Hearing Institute", nextService: "2026-05-22", type: "Annual Inspection" },
]

export const medRepeatRepairs = [
  { equipment: "Interacoustics EyeSeeCam VNG System", customer: "Sierra Balance Center", repairs: 3, lastRepair: "2025-12-21", issue: "Camera Alignment Drift" },
]

export const medExpiringWarranties = [
  { equipment: "MedRx AVANT REM System", customer: "Orange County Hearing Care", expires: "2026-02-10", daysLeft: 0 },
  { equipment: "Welch Allyn MacroView Otoscope", customer: "Coastal Hearing Institute", expires: "2026-05-22", daysLeft: 22 },
  { equipment: "Interacoustics EyeSeeCam VNG", customer: "Sierra Balance Center", expires: "2025-09-01", daysLeft: 0 },
]

// ─── AI Insights ──────────────────────────────────────────────────────────────

export const medInsights: AiInsight[] = [
  {
    id: "mi-1",
    category: "overdue_client",
    severity: "critical",
    title: "Sacramento Pediatric Audiology OAE System overdue for calibration",
    description: "The Otodynamics ILO292 OAE System has missed its April 10 calibration deadline. Pediatric compliance standards (JCAHO) require current calibration certificates. Immediate scheduling recommended.",
    meta: "Overdue since Apr 10",
    value: "20+ days overdue",
    actionLabel: "Schedule now",
    actionHref: "/work-orders",
  },
  {
    id: "mi-2",
    category: "overdue_client",
    severity: "high",
    title: "Los Angeles Hearing Center has 4 devices due in the next 30 days",
    description: "The GSI AudioStar Pro (due May 14), a tympanometer calibration, a REM verification, and an OAE probe check are all converging. Bundling the Westside and Downtown visits could reduce travel cost by an estimated 20%.",
    meta: "4 items due before Jun 1",
    value: "4 devices",
    actionLabel: "View schedule",
    actionHref: "/service-schedule",
  },
  {
    id: "mi-3",
    category: "revenue_opportunity",
    severity: "medium",
    title: "Bay Area ENT Group is a strong PM contract expansion opportunity",
    description: "With 8 devices across two Bay Area locations and a history of timely contract renewal, a multi-site PM agreement could increase annual contract value by an estimated 22%. Prior engagement shows 96% renewal rate for accounts with 4+ completed PMs.",
    meta: "8 devices | 2 locations",
    value: "+$3,100 ARR est.",
    actionLabel: "View quotes",
    actionHref: "/quotes",
  },
  {
    id: "mi-4",
    category: "repeat_failure",
    severity: "high",
    title: "Sierra Balance Center has repeat VNG camera alignment activity",
    description: "The Interacoustics EyeSeeCam VNG system at Sierra Balance Center has required camera re-alignment at 3 of the last 4 visits. A formal semi-annual PM contract would reduce unplanned service events and strengthen compliance documentation.",
    meta: "3 of 4 visits required alignment",
    value: "Pattern detected",
    actionLabel: "View equipment",
    actionHref: "/equipment",
  },
  {
    id: "mi-5",
    category: "upsell",
    severity: "medium",
    title: "Orange County Hearing Care is a likely candidate for a multi-year service agreement",
    description: "Amanda Foster's practice has grown to 4 devices and is inquiring about a new audiometer installation. A 3-year service agreement now would lock in preferred pricing and increase total account value by an estimated $12,800.",
    meta: "Growing practice | 4 devices",
    value: "+$12,800 over 3 yrs",
    actionLabel: "View account",
    actionHref: "/customers",
  },
]
