import type { AiTaskDefinition, AiTaskId } from "@/lib/ai/types"

/** Central registry — router resolves models from here (never scatter literals in features). */
export const AI_TASK_REGISTRY: Record<AiTaskId, AiTaskDefinition> = {
  catalog_extraction: {
    id: "catalog_extraction",
    label: "Catalog / price list extraction",
    costTier: "medium",
    modelTier: "balanced",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "openai", model: "gpt-4o" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.15,
    maxOutputTokens: 16384,
    structuredMode: "json_object",
    timeoutMs: 180_000,
    maxRetries: 2,
    confidenceThreshold: 0.65,
  },
  work_order_summary: {
    id: "work_order_summary",
    label: "Work order summarization",
    costTier: "low",
    modelTier: "fast",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.2,
    maxOutputTokens: 4096,
    structuredMode: "json_object",
    timeoutMs: 60_000,
    maxRetries: 2,
    confidenceThreshold: null,
  },
  dispatch_recommendation: {
    id: "dispatch_recommendation",
    label: "Dispatch recommendation",
    costTier: "medium",
    modelTier: "balanced",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "openai", model: "gpt-4o" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.25,
    maxOutputTokens: 8192,
    structuredMode: "json_object",
    timeoutMs: 90_000,
    maxRetries: 2,
    confidenceThreshold: 0.7,
  },
  quote_generation: {
    id: "quote_generation",
    label: "Quote draft generation",
    costTier: "medium",
    modelTier: "balanced",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.3,
    maxOutputTokens: 8192,
    structuredMode: "json_object",
    timeoutMs: 120_000,
    maxRetries: 2,
    confidenceThreshold: null,
  },
  invoice_summary: {
    id: "invoice_summary",
    label: "Invoice summary",
    costTier: "low",
    modelTier: "fast",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "google", model: "gemini-1.5-flash" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.2,
    maxOutputTokens: 4096,
    structuredMode: "json_object",
    timeoutMs: 60_000,
    maxRetries: 2,
    confidenceThreshold: null,
  },
  certificate_cleanup: {
    id: "certificate_cleanup",
    label: "Certificate / calibration cleanup",
    costTier: "medium",
    modelTier: "balanced",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "openai", model: "gpt-4o" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.1,
    maxOutputTokens: 8192,
    structuredMode: "json_object",
    timeoutMs: 120_000,
    maxRetries: 2,
    confidenceThreshold: 0.75,
  },
  maintenance_prediction: {
    id: "maintenance_prediction",
    label: "Maintenance prediction",
    costTier: "medium",
    modelTier: "reasoning",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "openai", model: "gpt-4o" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.2,
    maxOutputTokens: 4096,
    structuredMode: "json_object",
    timeoutMs: 90_000,
    maxRetries: 2,
    confidenceThreshold: 0.6,
  },
  customer_email: {
    id: "customer_email",
    label: "Customer-facing email drafting",
    costTier: "low",
    modelTier: "fast",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.4,
    maxOutputTokens: 4096,
    structuredMode: "none",
    timeoutMs: 60_000,
    maxRetries: 2,
    confidenceThreshold: null,
  },
  workflow_builder: {
    id: "workflow_builder",
    label: "Workflow builder assistance",
    costTier: "high",
    modelTier: "reasoning",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "openai", model: "gpt-4o" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.15,
    maxOutputTokens: 8192,
    structuredMode: "json_object",
    timeoutMs: 120_000,
    maxRetries: 2,
    confidenceThreshold: null,
  },
  scheduling_assistant: {
    id: "scheduling_assistant",
    label: "Scheduling assistant",
    costTier: "medium",
    modelTier: "balanced",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "openai", model: "gpt-4o" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.25,
    maxOutputTokens: 8192,
    structuredMode: "json_object",
    timeoutMs: 90_000,
    maxRetries: 2,
    confidenceThreshold: null,
  },
  OCR_cleanup: {
    id: "OCR_cleanup",
    label: "OCR cleanup / normalization",
    costTier: "low",
    modelTier: "fast",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "google", model: "gemini-1.5-flash" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.1,
    maxOutputTokens: 8192,
    structuredMode: "json_object",
    timeoutMs: 90_000,
    maxRetries: 2,
    confidenceThreshold: null,
  },
  classification: {
    id: "classification",
    label: "Classification",
    costTier: "low",
    modelTier: "fast",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "google", model: "gemini-1.5-flash" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0,
    maxOutputTokens: 2048,
    structuredMode: "json_object",
    timeoutMs: 45_000,
    maxRetries: 2,
    confidenceThreshold: 0.85,
  },
  tagging: {
    id: "tagging",
    label: "Tagging / labeling",
    costTier: "low",
    modelTier: "fast",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.15,
    maxOutputTokens: 2048,
    structuredMode: "json_object",
    timeoutMs: 45_000,
    maxRetries: 2,
    confidenceThreshold: 0.8,
  },
}

export function getTaskDefinition(id: AiTaskId): AiTaskDefinition {
  const def = AI_TASK_REGISTRY[id]
  if (!def) throw new Error(`Unknown AI task: ${id}`)
  return def
}
