import type { AiTaskDefinition, AiTaskId } from "@/lib/ai/types"

/**
 * Central registry — router resolves models from here (never scatter literals in features).
 * TODO(ai-prompts): Add `promptId` + `AI_PROMPT_REGISTRY` rows for remaining tasks when their prompts stabilize.
 */
export const AI_TASK_REGISTRY: Record<AiTaskId, AiTaskDefinition> = {
  insights_generation: {
    id: "insights_generation",
    label: "Operational AI insights",
    promptId: "equipify.insights.operational_snapshot",
    requiredPlan: "core",
    costTier: "medium",
    modelTier: "balanced",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.35,
    maxOutputTokens: 8192,
    structuredMode: "json_object",
    timeoutMs: 120_000,
    maxRetries: 2,
    confidenceThreshold: null,
  },
  catalog_extraction: {
    id: "catalog_extraction",
    label: "Catalog / price list extraction",
    promptId: "equipify.catalog.price_list_extraction",
    requiredPlan: "growth",
    costTier: "medium",
    modelTier: "balanced",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "openai", model: "gpt-4o" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.15,
    maxOutputTokens: 16384,
    structuredMode: "json_object",
    timeoutMs: 180_000,
    maxRetries: 2,
    confidenceThreshold: 0.65,
    cacheable: true,
    cacheTtlSeconds: 604800,
  },
  work_order_summary: {
    id: "work_order_summary",
    label: "Work order summarization",
    requiredPlan: "core",
    costTier: "low",
    modelTier: "fast",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.2,
    maxOutputTokens: 4096,
    structuredMode: "json_object",
    timeoutMs: 60_000,
    maxRetries: 2,
    confidenceThreshold: null,
    cacheable: true,
    cacheTtlSeconds: 86400,
  },
  work_order_technician_assist: {
    id: "work_order_technician_assist",
    label: "Work order technician assistance",
    requiredPlan: "core",
    costTier: "low",
    modelTier: "fast",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.25,
    maxOutputTokens: 4096,
    structuredMode: "json_object",
    timeoutMs: 60_000,
    maxRetries: 2,
    confidenceThreshold: null,
    cacheable: true,
    cacheTtlSeconds: 86400,
  },
  work_order_parts_suggest: {
    id: "work_order_parts_suggest",
    label: "Work order parts / catalog suggestions",
    requiredPlan: "core",
    costTier: "low",
    modelTier: "fast",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.2,
    maxOutputTokens: 4096,
    structuredMode: "json_object",
    timeoutMs: 60_000,
    maxRetries: 2,
    confidenceThreshold: null,
    cacheable: true,
    cacheTtlSeconds: 86400,
  },
  dispatch_recommendation: {
    id: "dispatch_recommendation",
    label: "Dispatch recommendation",
    requiredPlan: "core",
    costTier: "medium",
    modelTier: "balanced",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "openai", model: "gpt-4o" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.25,
    maxOutputTokens: 8192,
    structuredMode: "json_object",
    timeoutMs: 90_000,
    maxRetries: 2,
    confidenceThreshold: 0.7,
  },
  quote_generation: {
    id: "quote_generation",
    label: "Quote draft generation",
    requiredPlan: "core",
    costTier: "medium",
    modelTier: "balanced",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.3,
    maxOutputTokens: 8192,
    structuredMode: "json_object",
    timeoutMs: 120_000,
    maxRetries: 2,
    confidenceThreshold: null,
  },
  invoice_summary: {
    id: "invoice_summary",
    label: "Invoice summary",
    requiredPlan: "core",
    costTier: "low",
    modelTier: "fast",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "google", model: "gemini-1.5-flash" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.2,
    maxOutputTokens: 4096,
    structuredMode: "json_object",
    timeoutMs: 60_000,
    maxRetries: 2,
    confidenceThreshold: null,
  },
  certificate_cleanup: {
    id: "certificate_cleanup",
    label: "Certificate / calibration cleanup",
    promptId: "equipify.certificate.template_extraction",
    requiredPlan: "growth",
    costTier: "medium",
    modelTier: "balanced",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "openai", model: "gpt-4o" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.1,
    maxOutputTokens: 8192,
    structuredMode: "json_object",
    timeoutMs: 120_000,
    maxRetries: 2,
    confidenceThreshold: 0.75,
    cacheable: true,
    cacheTtlSeconds: 604800,
  },
  equipment_ai_scan: {
    id: "equipment_ai_scan",
    label: "Equipment photo / document scan",
    promptId: "equipify.equipment.ai_scan_extraction",
    requiredPlan: "growth",
    costTier: "medium",
    modelTier: "balanced",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "openai", model: "gpt-4o" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.15,
    maxOutputTokens: 8192,
    structuredMode: "json_object",
    timeoutMs: 120_000,
    maxRetries: 2,
    confidenceThreshold: null,
    cacheable: true,
    cacheTtlSeconds: 86_400,
  },
  prospect_business_card_scan: {
    id: "prospect_business_card_scan",
    label: "Prospect business card scan",
    promptId: "equipify.prospects.business_card_scan_extraction",
    requiredPlan: "growth",
    costTier: "medium",
    modelTier: "balanced",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "openai", model: "gpt-4o" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.1,
    maxOutputTokens: 4096,
    structuredMode: "json_object",
    timeoutMs: 90_000,
    maxRetries: 2,
    confidenceThreshold: null,
    cacheable: true,
    cacheTtlSeconds: 86_400,
  },
  maintenance_prediction: {
    id: "maintenance_prediction",
    label: "Maintenance prediction",
    requiredPlan: "core",
    costTier: "medium",
    modelTier: "reasoning",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "openai", model: "gpt-4o" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.2,
    maxOutputTokens: 4096,
    structuredMode: "json_object",
    timeoutMs: 90_000,
    maxRetries: 2,
    confidenceThreshold: 0.6,
  },
  customer_email: {
    id: "customer_email",
    label: "Customer-facing email drafting",
    promptId: "equipify.email.customer_followup_draft",
    requiredPlan: "core",
    costTier: "low",
    modelTier: "fast",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.4,
    maxOutputTokens: 4096,
    structuredMode: "none",
    timeoutMs: 60_000,
    maxRetries: 2,
    confidenceThreshold: null,
  },
  workflow_builder: {
    id: "workflow_builder",
    label: "Workflow builder assistance",
    requiredPlan: "growth",
    costTier: "high",
    modelTier: "reasoning",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "openai", model: "gpt-4o" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.15,
    maxOutputTokens: 8192,
    structuredMode: "json_object",
    timeoutMs: 120_000,
    maxRetries: 2,
    confidenceThreshold: null,
  },
  scheduling_assistant: {
    id: "scheduling_assistant",
    label: "Scheduling assistant",
    requiredPlan: "core",
    costTier: "medium",
    modelTier: "balanced",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "openai", model: "gpt-4o" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.25,
    maxOutputTokens: 8192,
    structuredMode: "json_object",
    timeoutMs: 90_000,
    maxRetries: 2,
    confidenceThreshold: null,
  },
  OCR_cleanup: {
    id: "OCR_cleanup",
    label: "OCR cleanup / normalization",
    promptId: "equipify.ocr.plaintext_cleanup",
    requiredPlan: "core",
    costTier: "low",
    modelTier: "fast",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "google", model: "gemini-1.5-flash" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.1,
    maxOutputTokens: 8192,
    structuredMode: "json_object",
    timeoutMs: 90_000,
    maxRetries: 2,
    confidenceThreshold: null,
    cacheable: true,
    cacheTtlSeconds: 604800,
  },
  classification: {
    id: "classification",
    label: "Classification",
    requiredPlan: "core",
    costTier: "low",
    modelTier: "fast",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "google", model: "gemini-1.5-flash" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0,
    maxOutputTokens: 2048,
    structuredMode: "json_object",
    timeoutMs: 45_000,
    maxRetries: 2,
    confidenceThreshold: 0.85,
    cacheable: true,
    cacheTtlSeconds: 86400,
  },
  tagging: {
    id: "tagging",
    label: "Tagging / labeling",
    requiredPlan: "core",
    costTier: "low",
    modelTier: "fast",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.15,
    maxOutputTokens: 2048,
    structuredMode: "json_object",
    timeoutMs: 45_000,
    maxRetries: 2,
    confidenceThreshold: 0.8,
    cacheable: true,
    cacheTtlSeconds: 86400,
  },
  inventory_operations: {
    id: "inventory_operations",
    label: "Inventory operations assistant",
    requiredPlan: "core",
    costTier: "medium",
    modelTier: "balanced",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "openai", model: "gpt-4o" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.2,
    maxOutputTokens: 4096,
    structuredMode: "json_object",
    timeoutMs: 90_000,
    maxRetries: 2,
    confidenceThreshold: null,
  },
  aiden_help: {
    id: "aiden_help",
    label: "AIden in-app help chat",
    requiredPlan: "solo",
    costTier: "low",
    modelTier: "fast",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.2,
    maxOutputTokens: 2048,
    structuredMode: "json_object",
    timeoutMs: 45_000,
    maxRetries: 2,
    confidenceThreshold: null,
  },
  aiden_customer_summary: {
    id: "aiden_customer_summary",
    label: "AIden customer productivity summary",
    requiredPlan: "growth",
    costTier: "low",
    modelTier: "fast",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.25,
    maxOutputTokens: 3072,
    structuredMode: "json_object",
    timeoutMs: 60_000,
    maxRetries: 2,
    confidenceThreshold: null,
  },
  aiden_work_order_productivity: {
    id: "aiden_work_order_productivity",
    label: "AIden work order productivity summary",
    requiredPlan: "growth",
    costTier: "low",
    modelTier: "fast",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.25,
    maxOutputTokens: 4096,
    structuredMode: "json_object",
    timeoutMs: 60_000,
    maxRetries: 2,
    confidenceThreshold: null,
  },
  aiden_draft_generation: {
    id: "aiden_draft_generation",
    label: "AIden productivity draft generation",
    requiredPlan: "growth",
    costTier: "low",
    modelTier: "fast",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.35,
    maxOutputTokens: 4096,
    structuredMode: "json_object",
    timeoutMs: 60_000,
    maxRetries: 2,
    confidenceThreshold: null,
  },
  aiden_operational_recommendations: {
    id: "aiden_operational_recommendations",
    label: "AIden operational recommendations (Scale)",
    requiredPlan: "scale",
    costTier: "medium",
    modelTier: "balanced",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.25,
    maxOutputTokens: 4096,
    structuredMode: "json_object",
    timeoutMs: 90_000,
    maxRetries: 2,
    confidenceThreshold: null,
  },
  aiden_safe_action_prepare: {
    id: "aiden_safe_action_prepare",
    label: "AIden safe workspace action (prepare)",
    requiredPlan: "scale",
    costTier: "medium",
    modelTier: "balanced",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.2,
    maxOutputTokens: 3072,
    structuredMode: "json_object",
    timeoutMs: 60_000,
    maxRetries: 2,
    confidenceThreshold: null,
  },
  aiden_prepared_workspace_intent_llm: {
    id: "aiden_prepared_workspace_intent_llm",
    label: "AIden prepared workspace intent (LLM assist)",
    requiredPlan: "core",
    costTier: "low",
    modelTier: "fast",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.1,
    maxOutputTokens: 2048,
    structuredMode: "json_object",
    timeoutMs: 45_000,
    maxRetries: 2,
    confidenceThreshold: null,
  },
  growth_lead_research: {
    id: "growth_lead_research",
    label: "Growth Engine lead research (internal)",
    requiredPlan: "growth",
    costTier: "medium",
    modelTier: "balanced",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.25,
    maxOutputTokens: 4096,
    structuredMode: "json_object",
    timeoutMs: 90_000,
    maxRetries: 2,
    confidenceThreshold: 0.5,
    cacheable: true,
    cacheTtlSeconds: 86400,
  },
  growth_copilot_generation: {
    id: "growth_copilot_generation",
    label: "Growth Engine AI communication copilot",
    requiredPlan: "growth",
    costTier: "medium",
    modelTier: "balanced",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.35,
    maxOutputTokens: 2048,
    structuredMode: "json_object",
    timeoutMs: 60_000,
    maxRetries: 2,
    confidenceThreshold: null,
    cacheable: true,
    cacheTtlSeconds: 3600,
  },
  growth_copilot_playbook_extraction: {
    id: "growth_copilot_playbook_extraction",
    label: "Growth Engine AI copilot playbook extraction",
    requiredPlan: "growth",
    costTier: "medium",
    modelTier: "balanced",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.2,
    maxOutputTokens: 4096,
    structuredMode: "json_object",
    timeoutMs: 90_000,
    maxRetries: 2,
    confidenceThreshold: null,
    cacheable: true,
    cacheTtlSeconds: 86400,
  },
  growth_live_turn_coach: {
    id: "growth_live_turn_coach",
    label: "Growth Engine live sales turn coach",
    requiredPlan: "growth",
    costTier: "low",
    modelTier: "fast",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.4,
    maxOutputTokens: 512,
    structuredMode: "json_object",
    timeoutMs: 12_000,
    maxRetries: 1,
    confidenceThreshold: null,
    cacheable: false,
    cacheTtlSeconds: 0,
  },
  growth_reply_draft_generation: {
    id: "growth_reply_draft_generation",
    label: "Growth Engine inbox reply draft generation",
    requiredPlan: "growth",
    costTier: "medium",
    modelTier: "balanced",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.35,
    maxOutputTokens: 2048,
    structuredMode: "json_object",
    timeoutMs: 60_000,
    maxRetries: 2,
    confidenceThreshold: null,
    cacheable: true,
    cacheTtlSeconds: 3600,
  },
  growth_video_script_generation: {
    id: "growth_video_script_generation",
    label: "Growth Engine personalized video script generation",
    requiredPlan: "growth",
    costTier: "medium",
    modelTier: "balanced",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.35,
    maxOutputTokens: 4096,
    structuredMode: "json_object",
    timeoutMs: 90_000,
    maxRetries: 2,
    confidenceThreshold: null,
    cacheable: true,
    cacheTtlSeconds: 3600,
  },
  growth_business_profile_draft: {
    id: "growth_business_profile_draft",
    label: "Growth Engine Business Profile draft generation",
    requiredPlan: "growth",
    costTier: "medium",
    modelTier: "balanced",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.25,
    maxOutputTokens: 4096,
    structuredMode: "json_object",
    timeoutMs: 60_000,
    maxRetries: 2,
    confidenceThreshold: null,
    cacheable: true,
    cacheTtlSeconds: 3600,
  },
  growth_business_intelligence_recommendations: {
    id: "growth_business_intelligence_recommendations",
    label: "Growth Engine Business Intelligence evidence-constrained recommendations",
    requiredPlan: "growth",
    costTier: "medium",
    modelTier: "balanced",
    primaryModel: { provider: "openai", model: "gpt-4o-mini" },
    fallbackModel: { provider: "anthropic", model: "claude-3-5-haiku-20241022" },
    escalationModel: { provider: "openai", model: "gpt-4o" },
    temperature: 0.2,
    maxOutputTokens: 4096,
    structuredMode: "json_object",
    timeoutMs: 60_000,
    maxRetries: 2,
    confidenceThreshold: null,
    cacheable: true,
    cacheTtlSeconds: 3600,
  },
}

export function getTaskDefinition(id: AiTaskId): AiTaskDefinition {
  const def = AI_TASK_REGISTRY[id]
  if (!def) throw new Error(`Unknown AI task: ${id}`)
  return {
    ...def,
    cacheable: def.cacheable ?? false,
    allowResponseCaching: def.allowResponseCaching ?? false,
    cacheTtlSeconds: def.cacheTtlSeconds ?? null,
    requiredPlan: def.requiredPlan ?? "solo",
    enabledPlans: def.enabledPlans,
    monthlyRequestLimit: def.monthlyRequestLimit ?? null,
    monthlyCostLimitCents: def.monthlyCostLimitCents ?? null,
    promptId: def.promptId,
  }
}
