/**
 * AUTO-GENERATED by `pnpm update:master-context` — do not edit by hand.
 * TODO: Wire deeper automation (optional AST/OpenAPI) without embedding secrets.
 */

export const MCG_SCAN_COUNTS = {
  apiRouteHandlers: 215,
  sqlMigrations: 143,
  dashboardPages: 59,
  componentsTsx: 233,
  libTsFiles: 425,
} as const

export const MCG_SCAN_SECTION = `## Repository scan (auto-generated)

_Regenerate with \`pnpm update:master-context\` after meaningful changes._

| Metric | Count |
|--------|------:|
| API route handlers (\`app/api/**/route.ts\`) | **215** |
| SQL migrations (\`supabase/migrations/*.sql\`) | **143** |
| Dashboard pages (\`app/(dashboard)/**/page.tsx\`) | **59** |
| \`components/**/*.tsx\` | **233** |
| \`lib/**/*.ts\` | **425** |

### Vercel crons

- \`/api/cron/maintenance-due\` — cron: \`0 6 * * *\`
- \`/api/cron/process-ai-jobs\` — cron: \`* * * * *\`
- \`/api/cron/process-import-runs\` — cron: \`*/5 * * * *\`
- \`/api/cron/ai-ops-digest\` — cron: \`0 * * * *\`

### API routes (relative to \`app/api\`)

\`\`\`
archived/restore/route.ts
archived/route.ts
billing/checkout/route.ts
certificates/import-template/route.ts
cron/ai-ops-digest/route.ts
cron/maintenance-due/route.ts
cron/process-ai-jobs/route.ts
cron/process-import-runs/route.ts
demo-data/import/route.ts
demo-data/reset/route.ts
demo-data/route.ts
dev/work-order-query-log/route.ts
email/certificate/route.ts
email/invoice/route.ts
email/quote/route.ts
email/work-order-summary/route.ts
insights/draft-email/route.ts
insights/generate/route.ts
insights/org-tasks/route.ts
integrations/quickbooks/authorize/route.ts
integrations/quickbooks/callback/route.ts
invites/accept/route.ts
invites/create/route.ts
invites/validate/route.ts
invoices/send-email/route.ts
maintenance/process-due/route.ts
onboarding/provision/route.ts
organizations/[organizationId]/ai-assistants/[assistantId]/enqueue/route.ts
organizations/[organizationId]/ai-assistants/[assistantId]/run/route.ts
organizations/[organizationId]/ai-assistants/route.ts
organizations/[organizationId]/ai-jobs/[jobId]/route.ts
organizations/[organizationId]/ai-ops/digest/preview/route.ts
organizations/[organizationId]/ai-ops/digest/runs/route.ts
organizations/[organizationId]/ai-ops/digest/send/route.ts
organizations/[organizationId]/ai-ops/digest/settings/route.ts
organizations/[organizationId]/ai-ops/digest/test-destination/route.ts
organizations/[organizationId]/ai-ops/dismissals/route.ts
organizations/[organizationId]/ai-ops/outcomes/route.ts
organizations/[organizationId]/ai-ops/recommendations/[recommendationKey]/execute-action/route.ts
organizations/[organizationId]/ai-ops/recommendations/[recommendationKey]/lifecycle/route.ts
organizations/[organizationId]/ai-ops/recommendations/[recommendationKey]/narrate/route.ts
organizations/[organizationId]/ai-ops/recommendations/[recommendationKey]/timeline/route.ts
organizations/[organizationId]/ai-ops/recommendations/route.ts
organizations/[organizationId]/ai-usage/route.ts
organizations/[organizationId]/aiden/actions/cancel/route.ts
organizations/[organizationId]/aiden/actions/confirm/route.ts
organizations/[organizationId]/aiden/actions/execute/route.ts
organizations/[organizationId]/aiden/actions/prepare/route.ts
organizations/[organizationId]/aiden/chat/route.ts
organizations/[organizationId]/aiden/feature-requests/route.ts
organizations/[organizationId]/aiden/operational-recommendations/route.ts
organizations/[organizationId]/aiden/productivity/customer-summary/route.ts
organizations/[organizationId]/aiden/productivity/draft/route.ts
organizations/[organizationId]/aiden/productivity/eligibility/route.ts
organizations/[organizationId]/aiden/productivity/work-order-summary/route.ts
organizations/[organizationId]/attachments/[attachmentId]/route.ts
organizations/[organizationId]/attachments/route.ts
organizations/[organizationId]/billing/default-invoice-terms/route.ts
organizations/[organizationId]/calibration-records/[recordId]/portal-release/route.ts
organizations/[organizationId]/calibration-templates/import-commit/route.ts
organizations/[organizationId]/catalog-items/[itemId]/attachments/route.ts
organizations/[organizationId]/catalog-items/[itemId]/route.ts
organizations/[organizationId]/catalog-items/[itemId]/usage/route.ts
organizations/[organizationId]/catalog-items/[itemId]/verification/route.ts
organizations/[organizationId]/catalog-items/route.ts
organizations/[organizationId]/communications/[communicationId]/ai-assist/route.ts
organizations/[organizationId]/communications/[communicationId]/route.ts
organizations/[organizationId]/communications/[communicationId]/send/route.ts
organizations/[organizationId]/communications/[eventId]/read/route.ts
organizations/[organizationId]/communications/[eventId]/retry/route.ts
organizations/[organizationId]/communications/automations/route.ts
organizations/[organizationId]/communications/drafts/route.ts
organizations/[organizationId]/communications/feed/route.ts
organizations/[organizationId]/communications/metrics/route.ts
organizations/[organizationId]/communications/route.ts
organizations/[organizationId]/communications/suggestions/route.ts
organizations/[organizationId]/communications/templates/[templateId]/route.ts
organizations/[organizationId]/communications/templates/route.ts
organizations/[organizationId]/customers/[customerId]/locations/[locationId]/route.ts
organizations/[organizationId]/customers/[customerId]/locations/route.ts
organizations/[organizationId]/customers/[customerId]/portal-certificate-release/route.ts
organizations/[organizationId]/customers/[customerId]/portal-consolidated-documents/route.ts
organizations/[organizationId]/equipment-warranties/[warrantyId]/route.ts
organizations/[organizationId]/equipment-warranties/route.ts
organizations/[organizationId]/follow-up-automation/settings/route.ts
organizations/[organizationId]/follow-up-tasks/[taskId]/approve/route.ts
organizations/[organizationId]/follow-up-tasks/[taskId]/dismiss/route.ts
organizations/[organizationId]/follow-up-tasks/[taskId]/handoff/route.ts
organizations/[organizationId]/follow-up-tasks/[taskId]/regenerate-draft/route.ts
organizations/[organizationId]/follow-up-tasks/evaluate/route.ts
organizations/[organizationId]/follow-up-tasks/route.ts
organizations/[organizationId]/follow-up-tasks/stats/route.ts
organizations/[organizationId]/integrations/quickbooks/apply-inbound-paid/route.ts
organizations/[organizationId]/integrations/quickbooks/invoice-auto-sync/route.ts
organizations/[organizationId]/integrations/quickbooks/route.ts
organizations/[organizationId]/inventory/adjust/route.ts
organizations/[organizationId]/inventory/allocate/route.ts
organizations/[organizationId]/inventory/consume/route.ts
organizations/[organizationId]/inventory/deallocate/route.ts
organizations/[organizationId]/inventory/draft-po-from-reorder/route.ts
organizations/[organizationId]/inventory/locations/route.ts
organizations/[organizationId]/inventory/low-stock/route.ts
organizations/[organizationId]/inventory/my-vehicle-location/route.ts
organizations/[organizationId]/inventory/receive/route.ts
organizations/[organizationId]/inventory/reorder-center/route.ts
organizations/[organizationId]/inventory/reorder-record/route.ts
organizations/[organizationId]/inventory/restock-request/route.ts
organizations/[organizationId]/inventory/stock/route.ts
organizations/[organizationId]/inventory/technician-truck-stock/route.ts
organizations/[organizationId]/inventory/thresholds/route.ts
organizations/[organizationId]/inventory/transactions/route.ts
organizations/[organizationId]/inventory/transfer/route.ts
organizations/[organizationId]/inventory/truck-restock-complete/route.ts
organizations/[organizationId]/inventory/truck-transfer/route.ts
organizations/[organizationId]/inventory/vehicle-stock/route.ts
organizations/[organizationId]/invite-member/route.ts
organizations/[organizationId]/invoices/[invoiceId]/certificate-release-override/route.ts
organizations/[organizationId]/invoices/[invoiceId]/quickbooks-sync/route.ts
organizations/[organizationId]/members/[userId]/avatar/route.ts
organizations/[organizationId]/migration-imports/[jobId]/async/route.ts
organizations/[organizationId]/migration-imports/[jobId]/commit/route.ts
organizations/[organizationId]/migration-imports/[jobId]/export/route.ts
organizations/[organizationId]/migration-imports/[jobId]/preview/route.ts
organizations/[organizationId]/migration-imports/[jobId]/route.ts
organizations/[organizationId]/migration-imports/quickbooks/commit/route.ts
organizations/[organizationId]/migration-imports/quickbooks/preview/route.ts
organizations/[organizationId]/migration-imports/route.ts
organizations/[organizationId]/portal-invites/route.ts
organizations/[organizationId]/portal/certificate-release-default/route.ts
organizations/[organizationId]/portal/consolidated-documents-default/route.ts
organizations/[organizationId]/portal/document-access-activity/route.ts
organizations/[organizationId]/price-list-imports/[importId]/cancel/route.ts
organizations/[organizationId]/price-list-imports/[importId]/commit/route.ts
organizations/[organizationId]/price-list-imports/[importId]/duplicate-preview/route.ts
organizations/[organizationId]/price-list-imports/[importId]/extract/route.ts
organizations/[organizationId]/price-list-imports/[importId]/route.ts
organizations/[organizationId]/price-list-imports/route.ts
organizations/[organizationId]/prospect-assignees/route.ts
organizations/[organizationId]/prospects/[prospectId]/ai-brief/route.ts
organizations/[organizationId]/prospects/[prospectId]/convert/route.ts
organizations/[organizationId]/prospects/[prospectId]/draft-followup/route.ts
organizations/[organizationId]/prospects/[prospectId]/follow-up/route.ts
organizations/[organizationId]/prospects/[prospectId]/route.ts
organizations/[organizationId]/prospects/[prospectId]/timeline/route.ts
organizations/[organizationId]/prospects/route.ts
organizations/[organizationId]/reports/analytics/route.ts
organizations/[organizationId]/reports/financial-invoices/route.ts
organizations/[organizationId]/service-contracts/[contractId]/route.ts
organizations/[organizationId]/service-contracts/route.ts
organizations/[organizationId]/service-requests/[requestId]/ai-assist/route.ts
organizations/[organizationId]/service-requests/[requestId]/convert/route.ts
organizations/[organizationId]/service-requests/[requestId]/route.ts
organizations/[organizationId]/service-requests/dedupe/route.ts
organizations/[organizationId]/service-requests/route.ts
organizations/[organizationId]/service-requests/stats/route.ts
organizations/[organizationId]/technician-skill-tags/[tagId]/route.ts
organizations/[organizationId]/technician-skill-tags/route.ts
organizations/[organizationId]/workflow-automations/[automationId]/duplicate/route.ts
organizations/[organizationId]/workflow-automations/[automationId]/route.ts
organizations/[organizationId]/workflow-automations/[automationId]/runs/route.ts
organizations/[organizationId]/workflow-automations/[automationId]/test/route.ts
organizations/[organizationId]/workflow-automations/route.ts
organizations/[organizationId]/workflows/emit/route.ts
organizations/[organizationId]/workspace/document-logo/route.ts
organizations/[organizationId]/workspace/logo/route.ts
organizations/[organizationId]/workspace/route.ts
platform/accounts/[organizationId]/archive/route.ts
platform/accounts/[organizationId]/discount/route.ts
platform/accounts/[organizationId]/features/route.ts
platform/accounts/[organizationId]/members/route.ts
platform/accounts/[organizationId]/plan/route.ts
platform/accounts/[organizationId]/reactivate/route.ts
platform/accounts/[organizationId]/route.ts
platform/accounts/route.ts
platform/ai-alerts/[alertId]/route.ts
platform/ai-operations/route.ts
platform/ai-profitability/route.ts
platform/analytics/route.ts
platform/analytics/snapshot/route.ts
platform/feature-requests/route.ts
platform/import-operations/bulk-recover/route.ts
platform/import-operations/bulk-retry/route.ts
platform/import-operations/route.ts
platform/import-operations/runs/[runId]/notes/route.ts
portal/access/exchange/route.ts
portal/attachments/[attachmentId]/download/route.ts
portal/bootstrap/route.ts
portal/certificate-attachments/[attachmentId]/download/route.ts
portal/certificates/[recordId]/download/route.ts
portal/certificates/route.ts
portal/dashboard/route.ts
portal/documents/route.ts
portal/equipment/[equipmentId]/route.ts
portal/equipment/route.ts
portal/invoices/[invoiceId]/route.ts
portal/invoices/route.ts
portal/locations/route.ts
portal/maintenance/route.ts
portal/preview/start/route.ts
portal/public-branding/route.ts
portal/quotes/[quoteId]/approve/route.ts
portal/quotes/[quoteId]/decline/route.ts
portal/quotes/route.ts
portal/service-contracts/route.ts
portal/service-requests/route.ts
portal/session/logout/route.ts
portal/work-orders/route.ts
session/account-summary/route.ts
session/archive-access/route.ts
session/organization-subscription/route.ts
session/profile/route.ts
stripe/webhook/route.ts
team/members/[userId]/route.ts
team/members/route.ts
work-orders/scheduling-events/route.ts
\`\`\`

### Scanned roots

- \`app/\` — Next.js App Router routes and handlers
- \`components/\` — React UI
- \`lib/\` — domain logic, integrations, workflows
- \`supabase/migrations/\` — Postgres schema & RLS
`
