import { NextResponse } from "next/server"
import { z } from "zod"
import { AidenChatMessageSchema, AidenFeatureRequestDraftSchema } from "@/lib/aiden/aiden-response-rules"
import { createServerSupabaseClient } from "@/lib/supabase/server"

export const runtime = "nodejs"

const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i

const BodySchema = z.object({
  draft: AidenFeatureRequestDraftSchema,
  currentPath: z.string().trim().max(300).optional().nullable(),
  module: z.string().trim().max(120).optional().nullable(),
  chatContext: z.array(AidenChatMessageSchema).max(8).optional().default([]),
})

function jsonError(code: string, message: string, status: number) {
  return NextResponse.json({ ok: false, error: code, message }, { status })
}

function sanitizeText(value: string | null | undefined, max: number): string | null {
  const trimmed = value?.trim()
  if (!trimmed) return null
  return trimmed
    .replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi, "[email]")
    .replace(/\b(?:\+?1[-.\s]?)?\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}\b/g, "[phone]")
    .replace(/\b(?:sk|pk|rk|api|key|secret|token)_[A-Za-z0-9_-]{12,}\b/g, "[secret]")
    .slice(0, max)
}

function normalizeForDedupe(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
}

export async function POST(
  request: Request,
  context: { params: Promise<{ organizationId: string }> },
) {
  const { organizationId } = await context.params
  if (!UUID_RE.test(organizationId)) {
    return jsonError("invalid_organization", "Invalid organization id.", 400)
  }

  const rawBody = await request.json().catch(() => null)
  const parsed = BodySchema.safeParse(rawBody)
  if (!parsed.success) {
    return jsonError("invalid_body", "Send a feature request draft generated by AIden.", 400)
  }

  const supabase = await createServerSupabaseClient()
  const {
    data: { user },
    error: authErr,
  } = await supabase.auth.getUser()

  if (authErr || !user?.id) {
    return jsonError("unauthorized", "Sign in required.", 401)
  }

  const { data: member, error: memberErr } = await supabase
    .from("organization_members")
    .select("user_id")
    .eq("organization_id", organizationId)
    .eq("user_id", user.id)
    .eq("status", "active")
    .maybeSingle()

  if (memberErr || !member) {
    return jsonError("forbidden", "You do not have access to this organization.", 403)
  }

  const draft = parsed.data.draft
  const title = sanitizeText(draft.title, 120)
  const originalQuestion = sanitizeText(draft.originalQuestion, 1000)
  if (!title || !originalQuestion) {
    return jsonError("invalid_draft", "Feature request title and original question are required.", 400)
  }

  const dedupeQuestion = normalizeForDedupe(originalQuestion)
  const dedupeTitle = normalizeForDedupe(title)
  const { data: recent } = await supabase
    .from("product_feature_requests")
    .select("id, title, original_question, status, created_at")
    .eq("organization_id", organizationId)
    .eq("submitted_by", user.id)
    .in("status", ["new", "reviewed", "planned", "in_progress"])
    .order("created_at", { ascending: false })
    .limit(25)

  const duplicate = (recent ?? []).find((row) => {
    const existingTitle = normalizeForDedupe(String(row.title ?? ""))
    const existingQuestion = normalizeForDedupe(String(row.original_question ?? ""))
    return existingTitle === dedupeTitle || existingQuestion === dedupeQuestion
  })

  if (duplicate?.id) {
    return NextResponse.json({ ok: true, duplicate: true, requestId: duplicate.id })
  }

  const chatContext = parsed.data.chatContext.slice(-6).map((message) => ({
    role: message.role,
    content: sanitizeText(message.content, 800),
  }))

  const { data: inserted, error: insertErr } = await supabase
    .from("product_feature_requests")
    .insert({
      organization_id: organizationId,
      submitted_by: user.id,
      source: "aiden",
      title,
      original_question: originalQuestion,
      module: sanitizeText(draft.module ?? parsed.data.module, 120),
      current_path: sanitizeText(draft.currentPath ?? parsed.data.currentPath, 300),
      current_limitation: sanitizeText(draft.currentLimitation, 600),
      suggested_improvement: sanitizeText(draft.suggestedImprovement, 800),
      business_value: sanitizeText(draft.businessValue, 800),
      status: "new",
      priority: "unreviewed",
      chat_context: {
        submittedAt: new Date().toISOString(),
        messages: chatContext,
      },
    })
    .select("id")
    .single()

  if (insertErr || !inserted?.id) {
    return jsonError("insert_failed", insertErr?.message ?? "Could not save feature request.", 500)
  }

  return NextResponse.json({ ok: true, duplicate: false, requestId: inserted.id })
}
