/** Phase GS-3B — Knowledge retrieval contracts (client-safe). */

export {
  PLATFORM_KNOWLEDGE_CONSUMER_DEFAULT_CATEGORIES as KNOWLEDGE_CONSUMER_DEFAULT_CATEGORIES,
  PLATFORM_KNOWLEDGE_CONSUMER_DEFAULT_TAGS as KNOWLEDGE_CONSUMER_DEFAULT_TAGS,
  PLATFORM_KNOWLEDGE_CONSUMER_LABELS as KNOWLEDGE_CONSUMER_LABELS,
  PLATFORM_KNOWLEDGE_CONSUMERS as KNOWLEDGE_CONSUMERS,
  PLATFORM_KNOWLEDGE_EXCLUDED_RETRIEVAL_STATUSES as KNOWLEDGE_EXCLUDED_RETRIEVAL_STATUSES,
  PLATFORM_KNOWLEDGE_RETRIEVAL_CONFIRM as KNOWLEDGE_RETRIEVAL_CONFIRM,
  PLATFORM_KNOWLEDGE_RETRIEVAL_QA_MARKER as KNOWLEDGE_RETRIEVAL_QA_MARKER,
  PLATFORM_KNOWLEDGE_RETRIEVAL_RELEVANCE_WEIGHTS as KNOWLEDGE_RETRIEVAL_RELEVANCE_WEIGHTS,
} from "@fuzor/knowledge"

export type {
  PlatformKnowledgeConsumer as KnowledgeConsumer,
  PlatformKnowledgeRetrievalRequest as KnowledgeRetrievalRequest,
  PlatformKnowledgeRetrievalResult as KnowledgeRetrievalResult,
  PlatformKnowledgeRetrievalScoredDocument as KnowledgeRetrievalScoredDocument,
} from "@fuzor/knowledge"
