/**
 * Regenerates `lib/admin/master-context.generated.ts` from repository scans and bumps
 * `MASTER_CONTEXT_LAST_UPDATED_ISO` in `lib/admin/master-context.ts`.
 *
 * Safe: reads only source paths — no env vars, secrets, or DB credentials.
 *
 * Usage (from `equipify-app`): `pnpm update:master-context`
 */
import * as fs from "node:fs"
import * as path from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, "..")

function walkFiles(rootDir: string, fileName: string): string[] {
  const out: string[] = []
  function walk(dir: string) {
    if (!fs.existsSync(dir)) return
    const entries = fs.readdirSync(dir, { withFileTypes: true })
    for (const e of entries) {
      const full = path.join(dir, e.name)
      if (e.isDirectory()) {
        if (e.name === "node_modules" || e.name === ".next" || e.name === "dist") continue
        walk(full)
      } else if (e.isFile() && e.name === fileName) {
        out.push(full)
      }
    }
  }
  walk(rootDir)
  return out
}

/** Count files whose basename ends with the given suffix (e.g. `.tsx`). */
function countFilesEnding(rootDir: string, suffix: string): number {
  let n = 0
  function walk(dir: string) {
    if (!fs.existsSync(dir)) return
    const entries = fs.readdirSync(dir, { withFileTypes: true })
    for (const e of entries) {
      const full = path.join(dir, e.name)
      if (e.isDirectory()) {
        if (e.name === "node_modules" || e.name === ".next" || e.name === "dist") continue
        walk(full)
      } else if (e.isFile() && e.name.endsWith(suffix)) {
        n++
      }
    }
  }
  walk(rootDir)
  return n
}

function escapeTemplateLiteralChunk(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${")
}

function readVercelCrons(): string {
  try {
    const raw = fs.readFileSync(path.join(ROOT, "vercel.json"), "utf8")
    const j = JSON.parse(raw) as { crons?: Array<{ path: string; schedule: string }> }
    const rows = j.crons ?? []
    if (rows.length === 0) return "- _(no crons in vercel.json)_"
    return rows.map((c) => `- \`${c.path}\` — cron: \`${c.schedule}\``).join("\n")
  } catch {
    return "- _(could not read vercel.json)_"
  }
}

function main() {
  const apiRoot = path.join(ROOT, "app", "api")
  const apiRoutes = walkFiles(apiRoot, "route.ts")
    .map((abs) => path.relative(apiRoot, abs).split(path.sep).join("/"))
    .sort()

  const migrationDir = path.join(ROOT, "supabase", "migrations")
  const migrationCount = fs.existsSync(migrationDir)
    ? fs.readdirSync(migrationDir).filter((f) => f.endsWith(".sql")).length
    : 0

  const dashRoot = path.join(ROOT, "app", "(dashboard)")
  const dashboardPages = walkFiles(dashRoot, "page.tsx").length

  const componentsCount = countFilesEnding(path.join(ROOT, "components"), ".tsx")
  const libTsCount = countFilesEnding(path.join(ROOT, "lib"), ".ts")

  const lines: string[] = [
    "## Repository scan (auto-generated)",
    "",
    "_Regenerate with `pnpm update:master-context` after meaningful changes._",
    "",
    "| Metric | Count |",
    "|--------|------:|",
    "| API route handlers (`app/api/**/route.ts`) | **" + String(apiRoutes.length) + "** |",
    "| SQL migrations (`supabase/migrations/*.sql`) | **" + String(migrationCount) + "** |",
    "| Dashboard pages (`app/(dashboard)/**/page.tsx`) | **" + String(dashboardPages) + "** |",
    "| `components/**/*.tsx` | **" + String(componentsCount) + "** |",
    "| `lib/**/*.ts` | **" + String(libTsCount) + "** |",
    "",
    "### Vercel crons",
    "",
    readVercelCrons(),
    "",
    "### API routes (relative to `app/api`)",
    "",
    "```",
    ...apiRoutes,
    "```",
    "",
    "### Scanned roots",
    "",
    "- `app/` — Next.js App Router routes and handlers",
    "- `components/` — React UI",
    "- `lib/` — domain logic, integrations, workflows",
    "- `supabase/migrations/` — Postgres schema & RLS",
    "",
  ]

  const body = lines.join("\n")
  const escaped = escapeTemplateLiteralChunk(body)

  const genPath = path.join(ROOT, "lib", "admin", "master-context.generated.ts")
  const banner =
    "/**\n" +
    " * AUTO-GENERATED by `pnpm update:master-context` — do not edit by hand.\n" +
    " * TODO: Wire deeper automation (optional AST/OpenAPI) without embedding secrets.\n" +
    " */\n\n"

  const countsBlock =
    "export const MCG_SCAN_COUNTS = {\n" +
    `  apiRouteHandlers: ${apiRoutes.length},\n` +
    `  sqlMigrations: ${migrationCount},\n` +
    `  dashboardPages: ${dashboardPages},\n` +
    `  componentsTsx: ${componentsCount},\n` +
    `  libTsFiles: ${libTsCount},\n` +
    "} as const\n"

  fs.writeFileSync(genPath, `${banner}${countsBlock}\nexport const MCG_SCAN_SECTION = \`${escaped}\`\n`, "utf8")

  const iso = new Date().toISOString()
  const mcPath = path.join(ROOT, "lib", "admin", "master-context.ts")
  let mc = fs.readFileSync(mcPath, "utf8")
  const replaced = mc.replace(
    /export const MASTER_CONTEXT_LAST_UPDATED_ISO = "[^"]*"/,
    `export const MASTER_CONTEXT_LAST_UPDATED_ISO = "${iso}"`,
  )
  if (replaced === mc) {
    console.warn("warning: MASTER_CONTEXT_LAST_UPDATED_ISO pattern not found — timestamp not updated.")
  } else {
    fs.writeFileSync(mcPath, replaced, "utf8")
  }

  console.log(
    `Updated ${path.relative(ROOT, genPath)} (${apiRoutes.length} API routes, ${migrationCount} migrations).`,
  )
  console.log(`Set MASTER_CONTEXT_LAST_UPDATED_ISO = ${iso}`)
}

main()
