-- PM automation: flag auto-created work orders + append-only plan automation history.

alter table public.work_orders
  add column if not exists created_by_pm_automation boolean not null default false;

comment on column public.work_orders.created_by_pm_automation is
  'True when this work order was generated by preventive maintenance nightly automation.';

create table if not exists public.maintenance_plan_automation_events (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  maintenance_plan_id uuid not null references public.maintenance_plans(id) on delete cascade,
  work_order_id uuid references public.work_orders(id) on delete set null,
  event_type text not null
    check (event_type in (
      'wo_created',
      'skipped_duplicate',
      'run_error',
      'plan_paused',
      'plan_resumed'
    )),
  message text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

comment on table public.maintenance_plan_automation_events is
  'Audit trail for PM automation (work order generation, skips, errors, pause/resume).';

create index if not exists idx_mp_automation_events_org_plan_created
  on public.maintenance_plan_automation_events (organization_id, maintenance_plan_id, created_at desc);

alter table public.maintenance_plan_automation_events enable row level security;
alter table public.maintenance_plan_automation_events force row level security;

revoke all on table public.maintenance_plan_automation_events from public, anon;
grant select, insert on table public.maintenance_plan_automation_events to authenticated;

drop policy if exists "mp_automation_events_select_member" on public.maintenance_plan_automation_events;
create policy "mp_automation_events_select_member"
on public.maintenance_plan_automation_events
for select
to authenticated
using (public.is_org_member(organization_id));

drop policy if exists "mp_automation_events_insert_member" on public.maintenance_plan_automation_events;
create policy "mp_automation_events_insert_member"
on public.maintenance_plan_automation_events
for insert
to authenticated
with check (public.is_org_member(organization_id));
