-- Phase 23 — Follow-up & reminder automation foundation (human-in-the-loop).
-- Queue tasks are generated by server-side evaluation; no autonomous outbound sends.

-- -----------------------------------------------------------------------------
-- Per-organization automation configuration (thresholds + category toggles).
-- -----------------------------------------------------------------------------

create table if not exists public.follow_up_automation_settings (
  organization_id uuid primary key references public.organizations (id) on delete cascade,
  config jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

comment on table public.follow_up_automation_settings is
  'Reminder automation configuration (thresholds, categories, channels, AI draft toggle). App merges with conservative defaults.';

do $$
begin
  if to_regprocedure('public.set_updated_at()') is not null then
    drop trigger if exists trg_follow_up_automation_settings_updated_at on public.follow_up_automation_settings;
    create trigger trg_follow_up_automation_settings_updated_at
    before update on public.follow_up_automation_settings
    for each row execute function public.set_updated_at();
  end if;
end $$;

create index if not exists idx_follow_up_automation_settings_org
  on public.follow_up_automation_settings (organization_id);

alter table public.follow_up_automation_settings enable row level security;
alter table public.follow_up_automation_settings force row level security;

revoke all on table public.follow_up_automation_settings from public, anon;
grant select, insert, update, delete on table public.follow_up_automation_settings to authenticated;

drop policy if exists "follow_up_automation_settings_select_member" on public.follow_up_automation_settings;
create policy "follow_up_automation_settings_select_member"
on public.follow_up_automation_settings for select to authenticated
using (public.is_org_member (organization_id));

drop policy if exists "follow_up_automation_settings_write_roles" on public.follow_up_automation_settings;
create policy "follow_up_automation_settings_write_roles"
on public.follow_up_automation_settings for all to authenticated
using (public.has_org_role (organization_id, array['owner', 'admin', 'manager']))
with check (public.has_org_role (organization_id, array['owner', 'admin', 'manager']));

-- -----------------------------------------------------------------------------
-- Follow-up queue tasks (suggested reminders — pending human approval).
-- -----------------------------------------------------------------------------

create table if not exists public.follow_up_tasks (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  entity_type text not null
    check (entity_type in ('prospect', 'work_order', 'invoice', 'customer', 'equipment')),
  entity_id uuid not null,
  rule_key text not null,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'sent', 'dismissed', 'failed')),
  priority text not null default 'normal'
    check (priority in ('low', 'normal', 'high')),
  assigned_to_user_id uuid references auth.users (id) on delete set null,
  dedupe_key text not null,
  generated_at timestamptz not null default now(),
  scheduled_for timestamptz,
  completed_at timestamptz,
  dismissed_at timestamptz,
  draft_payload jsonb not null default '{}'::jsonb,
  communication_event_id uuid references public.communication_events (id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint follow_up_tasks_dedupe_key_nonempty check (char_length(trim(dedupe_key)) > 0)
);

comment on table public.follow_up_tasks is
  'Automation-suggested follow-ups; inserted by evaluator (service role). Humans approve/dismiss; sent = handed off to communications as draft/pending.';

create index if not exists idx_follow_up_tasks_org_status_created
  on public.follow_up_tasks (organization_id, status, created_at desc);

create index if not exists idx_follow_up_tasks_org_entity
  on public.follow_up_tasks (organization_id, entity_type, entity_id);

create index if not exists idx_follow_up_tasks_org_rule
  on public.follow_up_tasks (organization_id, rule_key);

create unique index if not exists idx_follow_up_tasks_open_dedupe
  on public.follow_up_tasks (organization_id, dedupe_key)
  where status in ('pending', 'approved');

do $$
begin
  if to_regprocedure('public.set_updated_at()') is not null then
    drop trigger if exists trg_follow_up_tasks_updated_at on public.follow_up_tasks;
    create trigger trg_follow_up_tasks_updated_at
    before update on public.follow_up_tasks
    for each row execute function public.set_updated_at();
  end if;
end $$;

alter table public.follow_up_tasks enable row level security;
alter table public.follow_up_tasks force row level security;

revoke all on table public.follow_up_tasks from public, anon;
grant select, update, delete on table public.follow_up_tasks to authenticated;
-- Inserts are performed by service role / automation jobs only.

drop policy if exists "follow_up_tasks_select_member" on public.follow_up_tasks;
create policy "follow_up_tasks_select_member"
on public.follow_up_tasks for select to authenticated
using (public.is_org_member (organization_id));

drop policy if exists "follow_up_tasks_update_managers" on public.follow_up_tasks;
create policy "follow_up_tasks_update_managers"
on public.follow_up_tasks for update to authenticated
using (public.has_org_role (organization_id, array['owner', 'admin', 'manager']))
with check (public.has_org_role (organization_id, array['owner', 'admin', 'manager']));

drop policy if exists "follow_up_tasks_delete_managers" on public.follow_up_tasks;
create policy "follow_up_tasks_delete_managers"
on public.follow_up_tasks for delete to authenticated
using (public.has_org_role (organization_id, array['owner', 'admin', 'manager']));

-- -----------------------------------------------------------------------------
-- Lightweight audit / usage for reminder automation (non-AI ops metrics).
-- -----------------------------------------------------------------------------

create table if not exists public.follow_up_automation_usage_events (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  event_type text not null
    check (event_type in ('evaluation_run', 'draft_generated', 'approved', 'dismissed', 'handoff')),
  user_id uuid references auth.users (id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

comment on table public.follow_up_automation_usage_events is
  'Audit counts for follow-up automation (evaluations, drafts, approvals, dismissals, handoffs).';

create index if not exists idx_follow_up_usage_org_created
  on public.follow_up_automation_usage_events (organization_id, created_at desc);

alter table public.follow_up_automation_usage_events enable row level security;
alter table public.follow_up_automation_usage_events force row level security;

revoke all on table public.follow_up_automation_usage_events from public, anon;
grant select, insert on table public.follow_up_automation_usage_events to authenticated;

drop policy if exists "follow_up_usage_select_member" on public.follow_up_automation_usage_events;
create policy "follow_up_usage_select_member"
on public.follow_up_automation_usage_events for select to authenticated
using (public.is_org_member (organization_id));

drop policy if exists "follow_up_usage_insert_member" on public.follow_up_automation_usage_events;
create policy "follow_up_usage_insert_member"
on public.follow_up_automation_usage_events for insert to authenticated
with check (public.is_org_member (organization_id));
